//! Bulk operations for DeliveryTier entities
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateDeliveryTierDto;
use crate::application::service::DeliveryTierService;
use crate::domain::entity::DeliveryTier;

/// Bulk operation handler for DeliveryTier entities.
///
/// Wraps `DeliveryTierService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type DeliveryTierBulkService = GenericBulkService<DeliveryTier, CreateDeliveryTierDto, DeliveryTierService>;

// <<< CUSTOM
// END CUSTOM
