//! Bulk operations
//!
//! Generated by backbone-schema. Do not edit manually.

pub mod shared_types;
pub use shared_types::*;

pub mod delivery_tier_bulk;
pub mod order_bulk;
pub mod order_delivery_bulk;
pub mod order_item_bulk;
pub mod order_pickup_bulk;
pub mod order_status_timeline_bulk;

pub use delivery_tier_bulk::DeliveryTierBulkService;
pub use order_bulk::OrderBulkService;
pub use order_delivery_bulk::OrderDeliveryBulkService;
pub use order_item_bulk::OrderItemBulkService;
pub use order_pickup_bulk::OrderPickupBulkService;
pub use order_status_timeline_bulk::OrderStatusTimelineBulkService;

// <<< CUSTOM
// END CUSTOM
