//! Bulk operations for OrderPickup entities
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateOrderPickupDto;
use crate::application::service::OrderPickupService;
use crate::domain::entity::OrderPickup;

/// Bulk operation handler for OrderPickup entities.
///
/// Wraps `OrderPickupService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type OrderPickupBulkService = GenericBulkService<OrderPickup, CreateOrderPickupDto, OrderPickupService>;

// <<< CUSTOM
// END CUSTOM
