//! Bulk operations for OrderItem entities
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateOrderItemDto;
use crate::application::service::OrderItemService;
use crate::domain::entity::OrderItem;

/// Bulk operation handler for OrderItem entities.
///
/// Wraps `OrderItemService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type OrderItemBulkService = GenericBulkService<OrderItem, CreateOrderItemDto, OrderItemService>;

// <<< CUSTOM
// END CUSTOM
