//! Bulk operations for OrderDelivery entities
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateOrderDeliveryDto;
use crate::application::service::OrderDeliveryService;
use crate::domain::entity::OrderDelivery;

/// Bulk operation handler for OrderDelivery entities.
///
/// Wraps `OrderDeliveryService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type OrderDeliveryBulkService = GenericBulkService<OrderDelivery, CreateOrderDeliveryDto, OrderDeliveryService>;

// <<< CUSTOM
// END CUSTOM
