//! Bulk operations for Order entities
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateOrderDto;
use crate::application::service::OrderService;
use crate::domain::entity::Order;

/// Bulk operation handler for Order entities.
///
/// Wraps `OrderService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type OrderBulkService = GenericBulkService<Order, CreateOrderDto, OrderService>;

// <<< CUSTOM
// END CUSTOM
