//! Bulk operations for OrderStatusTimeline entities
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateOrderStatusTimelineDto;
use crate::application::service::OrderStatusTimelineService;
use crate::domain::entity::OrderStatusTimeline;

/// Bulk operation handler for OrderStatusTimeline entities.
///
/// Wraps `OrderStatusTimelineService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type OrderStatusTimelineBulkService = GenericBulkService<OrderStatusTimeline, CreateOrderStatusTimelineDto, OrderStatusTimelineService>;

// <<< CUSTOM
// END CUSTOM
