//! DeliveryTier DTOs (Data Transfer Objects)
//!
//! Auto-generated by backbone-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::DeliveryTier;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new DeliveryTier
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateDeliveryTierDto {
    #[cfg_attr(feature = "validation", validate(length(max = 30)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub code: String,
    #[cfg_attr(feature = "validation", validate(length(max = 100)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[cfg_attr(feature = "validation", validate(range(max = 100)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name_en: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub duration_hours: i32,
    #[cfg_attr(feature = "validation", validate(length(max = 50)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub duration_label: String,
    #[cfg_attr(feature = "validation", validate(range(max = 20)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub color: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 50)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub icon: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_urgent: bool,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub sort_order: i32,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_active: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_default: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub provider_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub outlet_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub source_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_cloned: bool,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a DeliveryTier
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateDeliveryTierDto {
    #[cfg_attr(feature = "validation", validate(length(max = 30)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub code: String,
    #[cfg_attr(feature = "validation", validate(length(max = 100)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[cfg_attr(feature = "validation", validate(range(max = 100)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name_en: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub duration_hours: i32,
    #[cfg_attr(feature = "validation", validate(length(max = 50)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub duration_label: String,
    #[cfg_attr(feature = "validation", validate(range(max = 20)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub color: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 50)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub icon: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_urgent: bool,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub sort_order: i32,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_active: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_default: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub provider_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub outlet_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub source_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_cloned: bool,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a DeliveryTier
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchDeliveryTierDto {
    #[cfg_attr(feature = "validation", validate(nested))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name_en: Option<String>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub duration_hours: Option<i32>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub duration_label: Option<String>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub color: Option<String>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub icon: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub is_urgent: Option<bool>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sort_order: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub is_active: Option<bool>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub is_default: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub provider_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub outlet_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub source_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub is_cloned: Option<bool>,
}

impl PatchDeliveryTierDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.code.is_some() || self.name.is_some() || self.name_en.is_some() || self.description.is_some() || self.duration_hours.is_some() || self.duration_label.is_some() || self.color.is_some() || self.icon.is_some() || self.is_urgent.is_some() || self.sort_order.is_some() || self.is_active.is_some() || self.is_default.is_some() || self.provider_id.is_some() || self.outlet_id.is_some() || self.source_id.is_some() || self.is_cloned.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for DeliveryTier entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct DeliveryTierResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub code: String,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name_en: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub duration_hours: i32,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub duration_label: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub color: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub icon: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_urgent: bool,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub sort_order: i32,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_active: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_default: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub provider_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub outlet_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub source_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_cloned: bool,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for DeliveryTier entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct DeliveryTierListResponseDto {
    /// List of items
    pub items: Vec<DeliveryTierResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl DeliveryTierListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<DeliveryTierResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct DeliveryTierSummaryDto {
    pub id: Uuid,
    pub code: String,
    pub name: String,
    pub name_en: Option<String>,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<DeliveryTier> for DeliveryTierResponseDto {
    fn from(entity: DeliveryTier) -> Self {
        Self {
            id: entity.id,
            code: entity.code,
            name: entity.name,
            name_en: entity.name_en,
            description: entity.description,
            duration_hours: entity.duration_hours,
            duration_label: entity.duration_label,
            color: entity.color,
            icon: entity.icon,
            is_urgent: entity.is_urgent,
            sort_order: entity.sort_order,
            is_active: entity.is_active,
            is_default: entity.is_default,
            provider_id: entity.provider_id,
            outlet_id: entity.outlet_id,
            source_id: entity.source_id,
            is_cloned: entity.is_cloned,
            metadata: entity.metadata,
        }
    }
}

impl From<DeliveryTier> for DeliveryTierSummaryDto {
    fn from(entity: DeliveryTier) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            code: entity.code,
            name: entity.name,
            name_en: entity.name_en,
            created_at,
        }
    }
}

impl From<CreateDeliveryTierDto> for DeliveryTier {
    fn from(dto: CreateDeliveryTierDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            code: dto.code,
            name: dto.name,
            name_en: dto.name_en,
            description: dto.description,
            duration_hours: dto.duration_hours,
            duration_label: dto.duration_label,
            color: dto.color,
            icon: dto.icon,
            is_urgent: dto.is_urgent,
            sort_order: dto.sort_order,
            is_active: dto.is_active,
            is_default: dto.is_default,
            provider_id: dto.provider_id,
            outlet_id: dto.outlet_id,
            source_id: dto.source_id,
            is_cloned: dto.is_cloned,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&DeliveryTier> for DeliveryTierResponseDto {
    fn from(entity: &DeliveryTier) -> Self {
        Self {
            id: entity.id.clone(),
            code: entity.code.clone(),
            name: entity.name.clone(),
            name_en: entity.name_en.clone(),
            description: entity.description.clone(),
            duration_hours: entity.duration_hours.clone(),
            duration_label: entity.duration_label.clone(),
            color: entity.color.clone(),
            icon: entity.icon.clone(),
            is_urgent: entity.is_urgent.clone(),
            sort_order: entity.sort_order.clone(),
            is_active: entity.is_active.clone(),
            is_default: entity.is_default.clone(),
            provider_id: entity.provider_id.clone(),
            outlet_id: entity.outlet_id.clone(),
            source_id: entity.source_id.clone(),
            is_cloned: entity.is_cloned.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateDeliveryTierDto> for DeliveryTier {
    fn from_create_dto(dto: CreateDeliveryTierDto) -> backbone_core::ServiceResult<Self> {
        Ok(DeliveryTier::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateDeliveryTierDto> for DeliveryTier {
    fn apply_update(mut self, dto: UpdateDeliveryTierDto) -> backbone_core::ServiceResult<Self> {
        self.code = dto.code;
        self.name = dto.name;
        self.name_en = dto.name_en;
        self.description = dto.description;
        self.duration_hours = dto.duration_hours;
        self.duration_label = dto.duration_label;
        self.color = dto.color;
        self.icon = dto.icon;
        self.is_urgent = dto.is_urgent;
        self.sort_order = dto.sort_order;
        self.is_active = dto.is_active;
        self.is_default = dto.is_default;
        self.provider_id = dto.provider_id;
        self.outlet_id = dto.outlet_id;
        self.source_id = dto.source_id;
        self.is_cloned = dto.is_cloned;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to DeliveryTier here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

