//! DTOs (Data Transfer Objects)
//!
//! Auto-generated by backbone-schema. Do not edit manually.
//!
//! This module provides DTOs for the presentation layer,
//! with validation and OpenAPI schema support.

pub mod delivery_tier_dto;
pub mod order_dto;
pub mod order_delivery_dto;
pub mod order_item_dto;
pub mod order_pickup_dto;
pub mod order_status_timeline_dto;

// Re-exports
pub use delivery_tier_dto::{
    CreateDeliveryTierDto,
    UpdateDeliveryTierDto,
    PatchDeliveryTierDto,
    DeliveryTierResponseDto,
    DeliveryTierListResponseDto,
    DeliveryTierSummaryDto,
};
pub use order_dto::{
    CreateOrderDto,
    UpdateOrderDto,
    PatchOrderDto,
    OrderResponseDto,
    OrderListResponseDto,
    OrderSummaryDto,
};
pub use order_delivery_dto::{
    CreateOrderDeliveryDto,
    UpdateOrderDeliveryDto,
    PatchOrderDeliveryDto,
    OrderDeliveryResponseDto,
    OrderDeliveryListResponseDto,
    OrderDeliverySummaryDto,
};
pub use order_item_dto::{
    CreateOrderItemDto,
    UpdateOrderItemDto,
    PatchOrderItemDto,
    OrderItemResponseDto,
    OrderItemListResponseDto,
    OrderItemSummaryDto,
};
pub use order_pickup_dto::{
    CreateOrderPickupDto,
    UpdateOrderPickupDto,
    PatchOrderPickupDto,
    OrderPickupResponseDto,
    OrderPickupListResponseDto,
    OrderPickupSummaryDto,
};
pub use order_status_timeline_dto::{
    CreateOrderStatusTimelineDto,
    UpdateOrderStatusTimelineDto,
    PatchOrderStatusTimelineDto,
    OrderStatusTimelineResponseDto,
    OrderStatusTimelineListResponseDto,
    OrderStatusTimelineSummaryDto,
};

// Common pagination types
use serde::Serialize;

#[cfg(feature = "openapi")]
use utoipa::ToSchema;

/// Pagination parameters for list requests
#[derive(Debug, Clone, Default, serde::Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
pub struct PaginationParams {
    /// Page number (1-indexed)
    #[serde(default = "default_page")]
    pub page: u32,
    /// Items per page
    #[serde(default = "default_per_page")]
    pub per_page: u32,
    /// Field to sort by
    pub sort_by: Option<String>,
    /// Sort order (asc/desc)
    pub sort_order: Option<String>,
}

fn default_page() -> u32 { 1 }
fn default_per_page() -> u32 { 20 }

/// API response wrapper
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ApiResponse<T> {
    pub success: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data: Option<T>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<ApiError>,
}

#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
pub struct ApiError {
    pub code: String,
    pub message: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub details: Option<serde_json::Value>,
}

impl<T> ApiResponse<T> {
    pub fn ok(data: T) -> Self {
        Self { success: true, data: Some(data), error: None }
    }

    pub fn err(code: impl Into<String>, message: impl Into<String>) -> Self {
        Self {
            success: false,
            data: None,
            error: Some(ApiError {
                code: code.into(),
                message: message.into(),
                details: None,
            }),
        }
    }
}
