//! OrderItem DTOs (Data Transfer Objects)
//!
//! Auto-generated by backbone-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::OrderItem;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::ItemCondition;
use crate::domain::entity::ItemProcessingStatus;
use crate::domain::entity::UnitType;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new OrderItem
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateOrderItemDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub order_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub service_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(range(max = 100)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub item_name: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub quantity: i32,
    pub unit_type: UnitType,
    pub unit_price: Decimal,
    pub subtotal: Decimal,
    pub discount: Decimal,
    pub addon_total: Decimal,
    pub total: Decimal,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub currency: String,
    pub addons: serde_json::Value,
    pub condition_on_receipt: ItemCondition,
    #[cfg_attr(feature = "validation", validate(range(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub condition_notes: Option<String>,
    pub processing_status: ItemProcessingStatus,
    #[cfg_attr(feature = "validation", validate(range(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub special_instructions: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub processing_notes: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub delivery_tier_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub started_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub completed_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a OrderItem
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateOrderItemDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub order_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub service_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(range(max = 100)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub item_name: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub quantity: i32,
    pub unit_type: UnitType,
    pub unit_price: Decimal,
    pub subtotal: Decimal,
    pub discount: Decimal,
    pub addon_total: Decimal,
    pub total: Decimal,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub currency: String,
    pub addons: serde_json::Value,
    pub condition_on_receipt: ItemCondition,
    #[cfg_attr(feature = "validation", validate(range(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub condition_notes: Option<String>,
    pub processing_status: ItemProcessingStatus,
    #[cfg_attr(feature = "validation", validate(range(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub special_instructions: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub processing_notes: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub delivery_tier_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub started_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub completed_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a OrderItem
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchOrderItemDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub order_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub service_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub item_name: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub quantity: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub unit_type: Option<UnitType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub unit_price: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub subtotal: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub discount: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub addon_total: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub total: Option<Decimal>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub currency: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub addons: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub condition_on_receipt: Option<ItemCondition>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub condition_notes: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub processing_status: Option<ItemProcessingStatus>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub special_instructions: Option<String>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub processing_notes: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub delivery_tier_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub started_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub completed_at: Option<DateTime<Utc>>,
}

impl PatchOrderItemDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.order_id.is_some() || self.service_id.is_some() || self.item_name.is_some() || self.quantity.is_some() || self.unit_type.is_some() || self.unit_price.is_some() || self.subtotal.is_some() || self.discount.is_some() || self.addon_total.is_some() || self.total.is_some() || self.currency.is_some() || self.addons.is_some() || self.condition_on_receipt.is_some() || self.condition_notes.is_some() || self.processing_status.is_some() || self.special_instructions.is_some() || self.processing_notes.is_some() || self.delivery_tier_id.is_some() || self.started_at.is_some() || self.completed_at.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for OrderItem entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct OrderItemResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub order_id: Uuid,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub service_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub item_name: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub quantity: i32,
    pub unit_type: UnitType,
    pub unit_price: Decimal,
    pub subtotal: Decimal,
    pub discount: Decimal,
    pub addon_total: Decimal,
    pub total: Decimal,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub currency: String,
    pub addons: serde_json::Value,
    pub condition_on_receipt: ItemCondition,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub condition_notes: Option<String>,
    pub processing_status: ItemProcessingStatus,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub special_instructions: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub processing_notes: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub delivery_tier_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub started_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub completed_at: Option<DateTime<Utc>>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for OrderItem entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct OrderItemListResponseDto {
    /// List of items
    pub items: Vec<OrderItemResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl OrderItemListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<OrderItemResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct OrderItemSummaryDto {
    pub id: Uuid,
    pub order_id: Uuid,
    pub service_id: Option<Uuid>,
    pub item_name: Option<String>,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<OrderItem> for OrderItemResponseDto {
    fn from(entity: OrderItem) -> Self {
        Self {
            id: entity.id,
            order_id: entity.order_id,
            service_id: entity.service_id,
            item_name: entity.item_name,
            quantity: entity.quantity,
            unit_type: entity.unit_type,
            unit_price: entity.unit_price,
            subtotal: entity.subtotal,
            discount: entity.discount,
            addon_total: entity.addon_total,
            total: entity.total,
            currency: entity.currency,
            addons: entity.addons,
            condition_on_receipt: entity.condition_on_receipt,
            condition_notes: entity.condition_notes,
            processing_status: entity.processing_status,
            special_instructions: entity.special_instructions,
            processing_notes: entity.processing_notes,
            delivery_tier_id: entity.delivery_tier_id,
            started_at: entity.started_at,
            completed_at: entity.completed_at,
            metadata: entity.metadata,
        }
    }
}

impl From<OrderItem> for OrderItemSummaryDto {
    fn from(entity: OrderItem) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            order_id: entity.order_id,
            service_id: entity.service_id,
            item_name: entity.item_name,
            created_at,
        }
    }
}

impl From<CreateOrderItemDto> for OrderItem {
    fn from(dto: CreateOrderItemDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            order_id: dto.order_id,
            service_id: dto.service_id,
            item_name: dto.item_name,
            quantity: dto.quantity,
            unit_type: dto.unit_type,
            unit_price: dto.unit_price,
            subtotal: dto.subtotal,
            discount: dto.discount,
            addon_total: dto.addon_total,
            total: dto.total,
            currency: dto.currency,
            addons: dto.addons,
            condition_on_receipt: dto.condition_on_receipt,
            condition_notes: dto.condition_notes,
            processing_status: dto.processing_status,
            special_instructions: dto.special_instructions,
            processing_notes: dto.processing_notes,
            delivery_tier_id: dto.delivery_tier_id,
            started_at: dto.started_at,
            completed_at: dto.completed_at,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&OrderItem> for OrderItemResponseDto {
    fn from(entity: &OrderItem) -> Self {
        Self {
            id: entity.id.clone(),
            order_id: entity.order_id.clone(),
            service_id: entity.service_id.clone(),
            item_name: entity.item_name.clone(),
            quantity: entity.quantity.clone(),
            unit_type: entity.unit_type.clone(),
            unit_price: entity.unit_price.clone(),
            subtotal: entity.subtotal.clone(),
            discount: entity.discount.clone(),
            addon_total: entity.addon_total.clone(),
            total: entity.total.clone(),
            currency: entity.currency.clone(),
            addons: entity.addons.clone(),
            condition_on_receipt: entity.condition_on_receipt.clone(),
            condition_notes: entity.condition_notes.clone(),
            processing_status: entity.processing_status.clone(),
            special_instructions: entity.special_instructions.clone(),
            processing_notes: entity.processing_notes.clone(),
            delivery_tier_id: entity.delivery_tier_id.clone(),
            started_at: entity.started_at.clone(),
            completed_at: entity.completed_at.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateOrderItemDto> for OrderItem {
    fn from_create_dto(dto: CreateOrderItemDto) -> backbone_core::ServiceResult<Self> {
        Ok(OrderItem::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateOrderItemDto> for OrderItem {
    fn apply_update(mut self, dto: UpdateOrderItemDto) -> backbone_core::ServiceResult<Self> {
        self.order_id = dto.order_id;
        self.service_id = dto.service_id;
        self.item_name = dto.item_name;
        self.quantity = dto.quantity;
        self.unit_type = dto.unit_type;
        self.unit_price = dto.unit_price;
        self.subtotal = dto.subtotal;
        self.discount = dto.discount;
        self.addon_total = dto.addon_total;
        self.total = dto.total;
        self.currency = dto.currency;
        self.addons = dto.addons;
        self.condition_on_receipt = dto.condition_on_receipt;
        self.condition_notes = dto.condition_notes;
        self.processing_status = dto.processing_status;
        self.special_instructions = dto.special_instructions;
        self.processing_notes = dto.processing_notes;
        self.delivery_tier_id = dto.delivery_tier_id;
        self.started_at = dto.started_at;
        self.completed_at = dto.completed_at;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to OrderItem here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

