//! OrderPickup DTOs (Data Transfer Objects)
//!
//! Auto-generated by backbone-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc, NaiveDate};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::OrderPickup;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::PickupStatus;
use crate::domain::entity::PickupType;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new OrderPickup
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateOrderPickupDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub order_id: Uuid,
    pub pickup_type: PickupType,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    pub scheduled_date: NaiveDate,
    #[cfg_attr(feature = "validation", validate(range(max = 5)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub scheduled_time_start: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 5)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub scheduled_time_end: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 30)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub time_slot: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub customer_requested_date: Option<NaiveDate>,
    #[cfg_attr(feature = "validation", validate(range(max = 5)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub customer_requested_time_start: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 5)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub customer_requested_time_end: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub address_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 255)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub address_line: String,
    #[cfg_attr(feature = "validation", validate(range(max = 255)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub address_detail: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 100)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub landmark: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub latitude: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub longitude: Option<f64>,
    #[cfg_attr(feature = "validation", validate(length(max = 100)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub contact_name: String,
    #[cfg_attr(feature = "validation", validate(length(max = 20)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub contact_phone: String,
    #[cfg_attr(feature = "validation", validate(range(max = 20)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub contact_phone_alt: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub agent_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(range(max = 100)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub agent_name: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 20)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub agent_phone: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub assigned_at: Option<DateTime<Utc>>,
    pub status: PickupStatus,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub en_route_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arrived_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub started_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub completed_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub estimated_weight_kg: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub actual_weight_kg: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub estimated_items: Option<i32>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub actual_items: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub bag_count: i32,
    pub bag_numbers: serde_json::Value,
    pub photos: serde_json::Value,
    #[cfg_attr(feature = "validation", validate(range(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub signature_url: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 100)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub signed_by: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub pickup_latitude: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub pickup_longitude: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub distance_from_address_meters: Option<i32>,
    #[cfg_attr(feature = "validation", validate(range(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub customer_notes: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub agent_notes: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub internal_notes: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 255)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub failure_reason: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 30)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub failure_code: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub reschedule_count: i32,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub original_scheduled_date: Option<NaiveDate>,
    #[cfg_attr(feature = "validation", validate(range(max = 255)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reschedule_reason: Option<String>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a OrderPickup
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateOrderPickupDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub order_id: Uuid,
    pub pickup_type: PickupType,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    pub scheduled_date: NaiveDate,
    #[cfg_attr(feature = "validation", validate(range(max = 5)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub scheduled_time_start: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 5)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub scheduled_time_end: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 30)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub time_slot: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub customer_requested_date: Option<NaiveDate>,
    #[cfg_attr(feature = "validation", validate(range(max = 5)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub customer_requested_time_start: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 5)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub customer_requested_time_end: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub address_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 255)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub address_line: String,
    #[cfg_attr(feature = "validation", validate(range(max = 255)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub address_detail: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 100)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub landmark: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub latitude: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub longitude: Option<f64>,
    #[cfg_attr(feature = "validation", validate(length(max = 100)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub contact_name: String,
    #[cfg_attr(feature = "validation", validate(length(max = 20)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub contact_phone: String,
    #[cfg_attr(feature = "validation", validate(range(max = 20)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub contact_phone_alt: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub agent_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(range(max = 100)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub agent_name: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 20)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub agent_phone: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub assigned_at: Option<DateTime<Utc>>,
    pub status: PickupStatus,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub en_route_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arrived_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub started_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub completed_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub estimated_weight_kg: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub actual_weight_kg: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub estimated_items: Option<i32>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub actual_items: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub bag_count: i32,
    pub bag_numbers: serde_json::Value,
    pub photos: serde_json::Value,
    #[cfg_attr(feature = "validation", validate(range(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub signature_url: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 100)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub signed_by: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub pickup_latitude: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub pickup_longitude: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub distance_from_address_meters: Option<i32>,
    #[cfg_attr(feature = "validation", validate(range(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub customer_notes: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub agent_notes: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub internal_notes: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 255)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub failure_reason: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 30)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub failure_code: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub reschedule_count: i32,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub original_scheduled_date: Option<NaiveDate>,
    #[cfg_attr(feature = "validation", validate(range(max = 255)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reschedule_reason: Option<String>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a OrderPickup
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchOrderPickupDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub order_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub pickup_type: Option<PickupType>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub scheduled_date: Option<NaiveDate>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub scheduled_time_start: Option<String>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub scheduled_time_end: Option<String>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub time_slot: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub customer_requested_date: Option<NaiveDate>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub customer_requested_time_start: Option<String>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub customer_requested_time_end: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub address_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub address_line: Option<String>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub address_detail: Option<String>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub landmark: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub latitude: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub longitude: Option<f64>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub contact_name: Option<String>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub contact_phone: Option<String>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub contact_phone_alt: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub agent_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub agent_name: Option<String>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub agent_phone: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub assigned_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<PickupStatus>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub en_route_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub arrived_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub started_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub completed_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub estimated_weight_kg: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub actual_weight_kg: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub estimated_items: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub actual_items: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bag_count: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bag_numbers: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub photos: Option<serde_json::Value>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub signature_url: Option<String>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub signed_by: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub pickup_latitude: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub pickup_longitude: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub distance_from_address_meters: Option<i32>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub customer_notes: Option<String>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub agent_notes: Option<String>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub internal_notes: Option<String>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub failure_reason: Option<String>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub failure_code: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reschedule_count: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub original_scheduled_date: Option<NaiveDate>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reschedule_reason: Option<String>,
}

impl PatchOrderPickupDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.order_id.is_some() || self.pickup_type.is_some() || self.scheduled_date.is_some() || self.scheduled_time_start.is_some() || self.scheduled_time_end.is_some() || self.time_slot.is_some() || self.customer_requested_date.is_some() || self.customer_requested_time_start.is_some() || self.customer_requested_time_end.is_some() || self.address_id.is_some() || self.address_line.is_some() || self.address_detail.is_some() || self.landmark.is_some() || self.latitude.is_some() || self.longitude.is_some() || self.contact_name.is_some() || self.contact_phone.is_some() || self.contact_phone_alt.is_some() || self.agent_id.is_some() || self.agent_name.is_some() || self.agent_phone.is_some() || self.assigned_at.is_some() || self.status.is_some() || self.en_route_at.is_some() || self.arrived_at.is_some() || self.started_at.is_some() || self.completed_at.is_some() || self.estimated_weight_kg.is_some() || self.actual_weight_kg.is_some() || self.estimated_items.is_some() || self.actual_items.is_some() || self.bag_count.is_some() || self.bag_numbers.is_some() || self.photos.is_some() || self.signature_url.is_some() || self.signed_by.is_some() || self.pickup_latitude.is_some() || self.pickup_longitude.is_some() || self.distance_from_address_meters.is_some() || self.customer_notes.is_some() || self.agent_notes.is_some() || self.internal_notes.is_some() || self.failure_reason.is_some() || self.failure_code.is_some() || self.reschedule_count.is_some() || self.original_scheduled_date.is_some() || self.reschedule_reason.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for OrderPickup entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct OrderPickupResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub order_id: Uuid,
    pub pickup_type: PickupType,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    pub scheduled_date: NaiveDate,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub scheduled_time_start: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub scheduled_time_end: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub time_slot: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub customer_requested_date: Option<NaiveDate>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub customer_requested_time_start: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub customer_requested_time_end: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub address_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub address_line: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub address_detail: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub landmark: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub latitude: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub longitude: Option<f64>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub contact_name: String,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub contact_phone: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub contact_phone_alt: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub agent_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub agent_name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub agent_phone: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub assigned_at: Option<DateTime<Utc>>,
    pub status: PickupStatus,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub en_route_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub arrived_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub started_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub completed_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub estimated_weight_kg: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub actual_weight_kg: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub estimated_items: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub actual_items: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub bag_count: i32,
    pub bag_numbers: serde_json::Value,
    pub photos: serde_json::Value,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub signature_url: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub signed_by: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub pickup_latitude: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub pickup_longitude: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub distance_from_address_meters: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub customer_notes: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub agent_notes: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub internal_notes: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub failure_reason: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub failure_code: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub reschedule_count: i32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub original_scheduled_date: Option<NaiveDate>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reschedule_reason: Option<String>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for OrderPickup entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct OrderPickupListResponseDto {
    /// List of items
    pub items: Vec<OrderPickupResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl OrderPickupListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<OrderPickupResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct OrderPickupSummaryDto {
    pub id: Uuid,
    pub order_id: Uuid,
    pub pickup_type: PickupType,
    pub scheduled_date: NaiveDate,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<OrderPickup> for OrderPickupResponseDto {
    fn from(entity: OrderPickup) -> Self {
        Self {
            id: entity.id,
            order_id: entity.order_id,
            pickup_type: entity.pickup_type,
            scheduled_date: entity.scheduled_date,
            scheduled_time_start: entity.scheduled_time_start,
            scheduled_time_end: entity.scheduled_time_end,
            time_slot: entity.time_slot,
            customer_requested_date: entity.customer_requested_date,
            customer_requested_time_start: entity.customer_requested_time_start,
            customer_requested_time_end: entity.customer_requested_time_end,
            address_id: entity.address_id,
            address_line: entity.address_line,
            address_detail: entity.address_detail,
            landmark: entity.landmark,
            latitude: entity.latitude,
            longitude: entity.longitude,
            contact_name: entity.contact_name,
            contact_phone: entity.contact_phone,
            contact_phone_alt: entity.contact_phone_alt,
            agent_id: entity.agent_id,
            agent_name: entity.agent_name,
            agent_phone: entity.agent_phone,
            assigned_at: entity.assigned_at,
            status: entity.status,
            en_route_at: entity.en_route_at,
            arrived_at: entity.arrived_at,
            started_at: entity.started_at,
            completed_at: entity.completed_at,
            estimated_weight_kg: entity.estimated_weight_kg,
            actual_weight_kg: entity.actual_weight_kg,
            estimated_items: entity.estimated_items,
            actual_items: entity.actual_items,
            bag_count: entity.bag_count,
            bag_numbers: entity.bag_numbers,
            photos: entity.photos,
            signature_url: entity.signature_url,
            signed_by: entity.signed_by,
            pickup_latitude: entity.pickup_latitude,
            pickup_longitude: entity.pickup_longitude,
            distance_from_address_meters: entity.distance_from_address_meters,
            customer_notes: entity.customer_notes,
            agent_notes: entity.agent_notes,
            internal_notes: entity.internal_notes,
            failure_reason: entity.failure_reason,
            failure_code: entity.failure_code,
            reschedule_count: entity.reschedule_count,
            original_scheduled_date: entity.original_scheduled_date,
            reschedule_reason: entity.reschedule_reason,
            metadata: entity.metadata,
        }
    }
}

impl From<OrderPickup> for OrderPickupSummaryDto {
    fn from(entity: OrderPickup) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            order_id: entity.order_id,
            pickup_type: entity.pickup_type,
            scheduled_date: entity.scheduled_date,
            created_at,
        }
    }
}

impl From<CreateOrderPickupDto> for OrderPickup {
    fn from(dto: CreateOrderPickupDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            order_id: dto.order_id,
            pickup_type: dto.pickup_type,
            scheduled_date: dto.scheduled_date,
            scheduled_time_start: dto.scheduled_time_start,
            scheduled_time_end: dto.scheduled_time_end,
            time_slot: dto.time_slot,
            customer_requested_date: dto.customer_requested_date,
            customer_requested_time_start: dto.customer_requested_time_start,
            customer_requested_time_end: dto.customer_requested_time_end,
            address_id: dto.address_id,
            address_line: dto.address_line,
            address_detail: dto.address_detail,
            landmark: dto.landmark,
            latitude: dto.latitude,
            longitude: dto.longitude,
            contact_name: dto.contact_name,
            contact_phone: dto.contact_phone,
            contact_phone_alt: dto.contact_phone_alt,
            agent_id: dto.agent_id,
            agent_name: dto.agent_name,
            agent_phone: dto.agent_phone,
            assigned_at: dto.assigned_at,
            status: dto.status,
            en_route_at: dto.en_route_at,
            arrived_at: dto.arrived_at,
            started_at: dto.started_at,
            completed_at: dto.completed_at,
            estimated_weight_kg: dto.estimated_weight_kg,
            actual_weight_kg: dto.actual_weight_kg,
            estimated_items: dto.estimated_items,
            actual_items: dto.actual_items,
            bag_count: dto.bag_count,
            bag_numbers: dto.bag_numbers,
            photos: dto.photos,
            signature_url: dto.signature_url,
            signed_by: dto.signed_by,
            pickup_latitude: dto.pickup_latitude,
            pickup_longitude: dto.pickup_longitude,
            distance_from_address_meters: dto.distance_from_address_meters,
            customer_notes: dto.customer_notes,
            agent_notes: dto.agent_notes,
            internal_notes: dto.internal_notes,
            failure_reason: dto.failure_reason,
            failure_code: dto.failure_code,
            reschedule_count: dto.reschedule_count,
            original_scheduled_date: dto.original_scheduled_date,
            reschedule_reason: dto.reschedule_reason,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&OrderPickup> for OrderPickupResponseDto {
    fn from(entity: &OrderPickup) -> Self {
        Self {
            id: entity.id.clone(),
            order_id: entity.order_id.clone(),
            pickup_type: entity.pickup_type.clone(),
            scheduled_date: entity.scheduled_date.clone(),
            scheduled_time_start: entity.scheduled_time_start.clone(),
            scheduled_time_end: entity.scheduled_time_end.clone(),
            time_slot: entity.time_slot.clone(),
            customer_requested_date: entity.customer_requested_date.clone(),
            customer_requested_time_start: entity.customer_requested_time_start.clone(),
            customer_requested_time_end: entity.customer_requested_time_end.clone(),
            address_id: entity.address_id.clone(),
            address_line: entity.address_line.clone(),
            address_detail: entity.address_detail.clone(),
            landmark: entity.landmark.clone(),
            latitude: entity.latitude.clone(),
            longitude: entity.longitude.clone(),
            contact_name: entity.contact_name.clone(),
            contact_phone: entity.contact_phone.clone(),
            contact_phone_alt: entity.contact_phone_alt.clone(),
            agent_id: entity.agent_id.clone(),
            agent_name: entity.agent_name.clone(),
            agent_phone: entity.agent_phone.clone(),
            assigned_at: entity.assigned_at.clone(),
            status: entity.status.clone(),
            en_route_at: entity.en_route_at.clone(),
            arrived_at: entity.arrived_at.clone(),
            started_at: entity.started_at.clone(),
            completed_at: entity.completed_at.clone(),
            estimated_weight_kg: entity.estimated_weight_kg.clone(),
            actual_weight_kg: entity.actual_weight_kg.clone(),
            estimated_items: entity.estimated_items.clone(),
            actual_items: entity.actual_items.clone(),
            bag_count: entity.bag_count.clone(),
            bag_numbers: entity.bag_numbers.clone(),
            photos: entity.photos.clone(),
            signature_url: entity.signature_url.clone(),
            signed_by: entity.signed_by.clone(),
            pickup_latitude: entity.pickup_latitude.clone(),
            pickup_longitude: entity.pickup_longitude.clone(),
            distance_from_address_meters: entity.distance_from_address_meters.clone(),
            customer_notes: entity.customer_notes.clone(),
            agent_notes: entity.agent_notes.clone(),
            internal_notes: entity.internal_notes.clone(),
            failure_reason: entity.failure_reason.clone(),
            failure_code: entity.failure_code.clone(),
            reschedule_count: entity.reschedule_count.clone(),
            original_scheduled_date: entity.original_scheduled_date.clone(),
            reschedule_reason: entity.reschedule_reason.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateOrderPickupDto> for OrderPickup {
    fn from_create_dto(dto: CreateOrderPickupDto) -> backbone_core::ServiceResult<Self> {
        Ok(OrderPickup::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateOrderPickupDto> for OrderPickup {
    fn apply_update(mut self, dto: UpdateOrderPickupDto) -> backbone_core::ServiceResult<Self> {
        self.order_id = dto.order_id;
        self.pickup_type = dto.pickup_type;
        self.scheduled_date = dto.scheduled_date;
        self.scheduled_time_start = dto.scheduled_time_start;
        self.scheduled_time_end = dto.scheduled_time_end;
        self.time_slot = dto.time_slot;
        self.customer_requested_date = dto.customer_requested_date;
        self.customer_requested_time_start = dto.customer_requested_time_start;
        self.customer_requested_time_end = dto.customer_requested_time_end;
        self.address_id = dto.address_id;
        self.address_line = dto.address_line;
        self.address_detail = dto.address_detail;
        self.landmark = dto.landmark;
        self.latitude = dto.latitude;
        self.longitude = dto.longitude;
        self.contact_name = dto.contact_name;
        self.contact_phone = dto.contact_phone;
        self.contact_phone_alt = dto.contact_phone_alt;
        self.agent_id = dto.agent_id;
        self.agent_name = dto.agent_name;
        self.agent_phone = dto.agent_phone;
        self.assigned_at = dto.assigned_at;
        self.status = dto.status;
        self.en_route_at = dto.en_route_at;
        self.arrived_at = dto.arrived_at;
        self.started_at = dto.started_at;
        self.completed_at = dto.completed_at;
        self.estimated_weight_kg = dto.estimated_weight_kg;
        self.actual_weight_kg = dto.actual_weight_kg;
        self.estimated_items = dto.estimated_items;
        self.actual_items = dto.actual_items;
        self.bag_count = dto.bag_count;
        self.bag_numbers = dto.bag_numbers;
        self.photos = dto.photos;
        self.signature_url = dto.signature_url;
        self.signed_by = dto.signed_by;
        self.pickup_latitude = dto.pickup_latitude;
        self.pickup_longitude = dto.pickup_longitude;
        self.distance_from_address_meters = dto.distance_from_address_meters;
        self.customer_notes = dto.customer_notes;
        self.agent_notes = dto.agent_notes;
        self.internal_notes = dto.internal_notes;
        self.failure_reason = dto.failure_reason;
        self.failure_code = dto.failure_code;
        self.reschedule_count = dto.reschedule_count;
        self.original_scheduled_date = dto.original_scheduled_date;
        self.reschedule_reason = dto.reschedule_reason;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to OrderPickup here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

