//! Order DTOs (Data Transfer Objects)
//!
//! Auto-generated by backbone-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::Order;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::CancellationReason;
use crate::domain::entity::FulfillmentMethod;
use crate::domain::entity::OrderStatus;
use crate::domain::entity::OrderType;
use crate::domain::entity::PaymentStatus;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new Order
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateOrderDto {
    #[cfg_attr(feature = "validation", validate(length(max = 30)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub order_number: String,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub customer_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub provider_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub outlet_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub corporate_order_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub delivery_tier_id: Option<Uuid>,
    pub order_type: OrderType,
    pub status: OrderStatus,
    pub fulfillment_method: FulfillmentMethod,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub estimated_ready_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub actual_ready_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub currency: String,
    pub subtotal: Decimal,
    pub discount_amount: Decimal,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub promo_id: Option<Uuid>,
    pub delivery_fee: Decimal,
    pub pickup_fee: Decimal,
    pub tax_amount: Decimal,
    pub platform_fee: Decimal,
    pub grand_total: Decimal,
    pub payment_status: PaymentStatus,
    pub paid_amount: Decimal,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub paid_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "validation", validate(range(max = 1000)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub special_instructions: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 1000)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub provider_notes: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cancelled_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cancellation_reason: Option<CancellationReason>,
    #[cfg_attr(feature = "validation", validate(range(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cancellation_note: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cancelled_by: Option<Uuid>,
    pub data: serde_json::Value,
    #[cfg_attr(feature = "validation", validate(range(max = 50)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a Order
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateOrderDto {
    #[cfg_attr(feature = "validation", validate(length(max = 30)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub order_number: String,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub customer_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub provider_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub outlet_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub corporate_order_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub delivery_tier_id: Option<Uuid>,
    pub order_type: OrderType,
    pub status: OrderStatus,
    pub fulfillment_method: FulfillmentMethod,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub estimated_ready_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub actual_ready_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub currency: String,
    pub subtotal: Decimal,
    pub discount_amount: Decimal,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub promo_id: Option<Uuid>,
    pub delivery_fee: Decimal,
    pub pickup_fee: Decimal,
    pub tax_amount: Decimal,
    pub platform_fee: Decimal,
    pub grand_total: Decimal,
    pub payment_status: PaymentStatus,
    pub paid_amount: Decimal,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub paid_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "validation", validate(range(max = 1000)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub special_instructions: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 1000)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub provider_notes: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cancelled_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cancellation_reason: Option<CancellationReason>,
    #[cfg_attr(feature = "validation", validate(range(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cancellation_note: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cancelled_by: Option<Uuid>,
    pub data: serde_json::Value,
    #[cfg_attr(feature = "validation", validate(range(max = 50)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a Order
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchOrderDto {
    #[cfg_attr(feature = "validation", validate(nested))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub order_number: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub customer_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub provider_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub outlet_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub corporate_order_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub delivery_tier_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub order_type: Option<OrderType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<OrderStatus>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub fulfillment_method: Option<FulfillmentMethod>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub estimated_ready_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub actual_ready_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub currency: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub subtotal: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub discount_amount: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub promo_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub delivery_fee: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub pickup_fee: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tax_amount: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub platform_fee: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub grand_total: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub payment_status: Option<PaymentStatus>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub paid_amount: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub paid_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub special_instructions: Option<String>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub provider_notes: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cancelled_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cancellation_reason: Option<CancellationReason>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cancellation_note: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cancelled_by: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data: Option<serde_json::Value>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,
}

impl PatchOrderDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.order_number.is_some() || self.customer_id.is_some() || self.provider_id.is_some() || self.outlet_id.is_some() || self.corporate_order_id.is_some() || self.delivery_tier_id.is_some() || self.order_type.is_some() || self.status.is_some() || self.fulfillment_method.is_some() || self.estimated_ready_at.is_some() || self.actual_ready_at.is_some() || self.currency.is_some() || self.subtotal.is_some() || self.discount_amount.is_some() || self.promo_id.is_some() || self.delivery_fee.is_some() || self.pickup_fee.is_some() || self.tax_amount.is_some() || self.platform_fee.is_some() || self.grand_total.is_some() || self.payment_status.is_some() || self.paid_amount.is_some() || self.paid_at.is_some() || self.special_instructions.is_some() || self.provider_notes.is_some() || self.cancelled_at.is_some() || self.cancellation_reason.is_some() || self.cancellation_note.is_some() || self.cancelled_by.is_some() || self.data.is_some() || self.source.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for Order entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct OrderResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub order_number: String,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub customer_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub provider_id: Uuid,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub outlet_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub corporate_order_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub delivery_tier_id: Option<Uuid>,
    pub order_type: OrderType,
    pub status: OrderStatus,
    pub fulfillment_method: FulfillmentMethod,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub estimated_ready_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub actual_ready_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub currency: String,
    pub subtotal: Decimal,
    pub discount_amount: Decimal,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub promo_id: Option<Uuid>,
    pub delivery_fee: Decimal,
    pub pickup_fee: Decimal,
    pub tax_amount: Decimal,
    pub platform_fee: Decimal,
    pub grand_total: Decimal,
    pub payment_status: PaymentStatus,
    pub paid_amount: Decimal,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub paid_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub special_instructions: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub provider_notes: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cancelled_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cancellation_reason: Option<CancellationReason>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cancellation_note: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cancelled_by: Option<Uuid>,
    pub data: serde_json::Value,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for Order entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct OrderListResponseDto {
    /// List of items
    pub items: Vec<OrderResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl OrderListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<OrderResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct OrderSummaryDto {
    pub id: Uuid,
    pub order_number: String,
    pub customer_id: Uuid,
    pub provider_id: Uuid,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<Order> for OrderResponseDto {
    fn from(entity: Order) -> Self {
        Self {
            id: entity.id,
            order_number: entity.order_number,
            customer_id: entity.customer_id,
            provider_id: entity.provider_id,
            outlet_id: entity.outlet_id,
            corporate_order_id: entity.corporate_order_id,
            delivery_tier_id: entity.delivery_tier_id,
            order_type: entity.order_type,
            status: entity.status,
            fulfillment_method: entity.fulfillment_method,
            estimated_ready_at: entity.estimated_ready_at,
            actual_ready_at: entity.actual_ready_at,
            currency: entity.currency,
            subtotal: entity.subtotal,
            discount_amount: entity.discount_amount,
            promo_id: entity.promo_id,
            delivery_fee: entity.delivery_fee,
            pickup_fee: entity.pickup_fee,
            tax_amount: entity.tax_amount,
            platform_fee: entity.platform_fee,
            grand_total: entity.grand_total,
            payment_status: entity.payment_status,
            paid_amount: entity.paid_amount,
            paid_at: entity.paid_at,
            special_instructions: entity.special_instructions,
            provider_notes: entity.provider_notes,
            cancelled_at: entity.cancelled_at,
            cancellation_reason: entity.cancellation_reason,
            cancellation_note: entity.cancellation_note,
            cancelled_by: entity.cancelled_by,
            data: entity.data,
            source: entity.source,
            metadata: entity.metadata,
        }
    }
}

impl From<Order> for OrderSummaryDto {
    fn from(entity: Order) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            order_number: entity.order_number,
            customer_id: entity.customer_id,
            provider_id: entity.provider_id,
            created_at,
        }
    }
}

impl From<CreateOrderDto> for Order {
    fn from(dto: CreateOrderDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            order_number: dto.order_number,
            customer_id: dto.customer_id,
            provider_id: dto.provider_id,
            outlet_id: dto.outlet_id,
            corporate_order_id: dto.corporate_order_id,
            delivery_tier_id: dto.delivery_tier_id,
            order_type: dto.order_type,
            status: dto.status,
            fulfillment_method: dto.fulfillment_method,
            estimated_ready_at: dto.estimated_ready_at,
            actual_ready_at: dto.actual_ready_at,
            currency: dto.currency,
            subtotal: dto.subtotal,
            discount_amount: dto.discount_amount,
            promo_id: dto.promo_id,
            delivery_fee: dto.delivery_fee,
            pickup_fee: dto.pickup_fee,
            tax_amount: dto.tax_amount,
            platform_fee: dto.platform_fee,
            grand_total: dto.grand_total,
            payment_status: dto.payment_status,
            paid_amount: dto.paid_amount,
            paid_at: dto.paid_at,
            special_instructions: dto.special_instructions,
            provider_notes: dto.provider_notes,
            cancelled_at: dto.cancelled_at,
            cancellation_reason: dto.cancellation_reason,
            cancellation_note: dto.cancellation_note,
            cancelled_by: dto.cancelled_by,
            data: dto.data,
            source: dto.source,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&Order> for OrderResponseDto {
    fn from(entity: &Order) -> Self {
        Self {
            id: entity.id.clone(),
            order_number: entity.order_number.clone(),
            customer_id: entity.customer_id.clone(),
            provider_id: entity.provider_id.clone(),
            outlet_id: entity.outlet_id.clone(),
            corporate_order_id: entity.corporate_order_id.clone(),
            delivery_tier_id: entity.delivery_tier_id.clone(),
            order_type: entity.order_type.clone(),
            status: entity.status.clone(),
            fulfillment_method: entity.fulfillment_method.clone(),
            estimated_ready_at: entity.estimated_ready_at.clone(),
            actual_ready_at: entity.actual_ready_at.clone(),
            currency: entity.currency.clone(),
            subtotal: entity.subtotal.clone(),
            discount_amount: entity.discount_amount.clone(),
            promo_id: entity.promo_id.clone(),
            delivery_fee: entity.delivery_fee.clone(),
            pickup_fee: entity.pickup_fee.clone(),
            tax_amount: entity.tax_amount.clone(),
            platform_fee: entity.platform_fee.clone(),
            grand_total: entity.grand_total.clone(),
            payment_status: entity.payment_status.clone(),
            paid_amount: entity.paid_amount.clone(),
            paid_at: entity.paid_at.clone(),
            special_instructions: entity.special_instructions.clone(),
            provider_notes: entity.provider_notes.clone(),
            cancelled_at: entity.cancelled_at.clone(),
            cancellation_reason: entity.cancellation_reason.clone(),
            cancellation_note: entity.cancellation_note.clone(),
            cancelled_by: entity.cancelled_by.clone(),
            data: entity.data.clone(),
            source: entity.source.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateOrderDto> for Order {
    fn from_create_dto(dto: CreateOrderDto) -> backbone_core::ServiceResult<Self> {
        Ok(Order::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateOrderDto> for Order {
    fn apply_update(mut self, dto: UpdateOrderDto) -> backbone_core::ServiceResult<Self> {
        self.order_number = dto.order_number;
        self.customer_id = dto.customer_id;
        self.provider_id = dto.provider_id;
        self.outlet_id = dto.outlet_id;
        self.corporate_order_id = dto.corporate_order_id;
        self.delivery_tier_id = dto.delivery_tier_id;
        self.order_type = dto.order_type;
        self.status = dto.status;
        self.fulfillment_method = dto.fulfillment_method;
        self.estimated_ready_at = dto.estimated_ready_at;
        self.actual_ready_at = dto.actual_ready_at;
        self.currency = dto.currency;
        self.subtotal = dto.subtotal;
        self.discount_amount = dto.discount_amount;
        self.promo_id = dto.promo_id;
        self.delivery_fee = dto.delivery_fee;
        self.pickup_fee = dto.pickup_fee;
        self.tax_amount = dto.tax_amount;
        self.platform_fee = dto.platform_fee;
        self.grand_total = dto.grand_total;
        self.payment_status = dto.payment_status;
        self.paid_amount = dto.paid_amount;
        self.paid_at = dto.paid_at;
        self.special_instructions = dto.special_instructions;
        self.provider_notes = dto.provider_notes;
        self.cancelled_at = dto.cancelled_at;
        self.cancellation_reason = dto.cancellation_reason;
        self.cancellation_note = dto.cancellation_note;
        self.cancelled_by = dto.cancelled_by;
        self.data = dto.data;
        self.source = dto.source;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to Order here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

