//! OrderStatusTimeline DTOs (Data Transfer Objects)
//!
//! Auto-generated by backbone-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::OrderStatusTimeline;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::TimelineEntryType;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new OrderStatusTimeline
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateOrderStatusTimelineDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub order_id: Uuid,
    pub entry_type: TimelineEntryType,
    #[cfg_attr(feature = "validation", validate(range(max = 30)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub from_status: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 30)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub to_status: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    pub occurred_at: DateTime<Utc>,
    #[cfg_attr(feature = "validation", validate(range(max = 20)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub actor_type: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub actor_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(range(max = 100)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub actor_name: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 50)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub actor_role: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 100)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub title: String,
    #[cfg_attr(feature = "validation", validate(range(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub latitude: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub longitude: Option<f64>,
    #[cfg_attr(feature = "validation", validate(range(max = 255)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub location_name: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_customer_visible: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_provider_visible: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_agent_visible: bool,
    pub attachments: serde_json::Value,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub duration_minutes: Option<i32>,
    #[cfg_attr(feature = "validation", validate(range(max = 30)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub channel: Option<String>,
    pub device_info: serde_json::Value,
    #[cfg_attr(feature = "validation", validate(range(max = 45)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ip_address: Option<String>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a OrderStatusTimeline
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateOrderStatusTimelineDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub order_id: Uuid,
    pub entry_type: TimelineEntryType,
    #[cfg_attr(feature = "validation", validate(range(max = 30)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub from_status: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 30)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub to_status: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    pub occurred_at: DateTime<Utc>,
    #[cfg_attr(feature = "validation", validate(range(max = 20)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub actor_type: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub actor_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(range(max = 100)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub actor_name: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 50)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub actor_role: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 100)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub title: String,
    #[cfg_attr(feature = "validation", validate(range(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub latitude: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub longitude: Option<f64>,
    #[cfg_attr(feature = "validation", validate(range(max = 255)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub location_name: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_customer_visible: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_provider_visible: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_agent_visible: bool,
    pub attachments: serde_json::Value,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub duration_minutes: Option<i32>,
    #[cfg_attr(feature = "validation", validate(range(max = 30)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub channel: Option<String>,
    pub device_info: serde_json::Value,
    #[cfg_attr(feature = "validation", validate(range(max = 45)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ip_address: Option<String>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a OrderStatusTimeline
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchOrderStatusTimelineDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub order_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub entry_type: Option<TimelineEntryType>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub from_status: Option<String>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub to_status: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub occurred_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub actor_type: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub actor_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub actor_name: Option<String>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub actor_role: Option<String>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub latitude: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub longitude: Option<f64>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub location_name: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub is_customer_visible: Option<bool>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub is_provider_visible: Option<bool>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub is_agent_visible: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub attachments: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub duration_minutes: Option<i32>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub channel: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub device_info: Option<serde_json::Value>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ip_address: Option<String>,
}

impl PatchOrderStatusTimelineDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.order_id.is_some() || self.entry_type.is_some() || self.from_status.is_some() || self.to_status.is_some() || self.occurred_at.is_some() || self.actor_type.is_some() || self.actor_id.is_some() || self.actor_name.is_some() || self.actor_role.is_some() || self.title.is_some() || self.description.is_some() || self.latitude.is_some() || self.longitude.is_some() || self.location_name.is_some() || self.is_customer_visible.is_some() || self.is_provider_visible.is_some() || self.is_agent_visible.is_some() || self.attachments.is_some() || self.duration_minutes.is_some() || self.channel.is_some() || self.device_info.is_some() || self.ip_address.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for OrderStatusTimeline entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct OrderStatusTimelineResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub order_id: Uuid,
    pub entry_type: TimelineEntryType,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub from_status: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub to_status: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    pub occurred_at: DateTime<Utc>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub actor_type: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub actor_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub actor_name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub actor_role: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub title: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub latitude: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub longitude: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub location_name: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_customer_visible: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_provider_visible: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_agent_visible: bool,
    pub attachments: serde_json::Value,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub duration_minutes: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub channel: Option<String>,
    pub device_info: serde_json::Value,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ip_address: Option<String>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for OrderStatusTimeline entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct OrderStatusTimelineListResponseDto {
    /// List of items
    pub items: Vec<OrderStatusTimelineResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl OrderStatusTimelineListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<OrderStatusTimelineResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct OrderStatusTimelineSummaryDto {
    pub id: Uuid,
    pub order_id: Uuid,
    pub entry_type: TimelineEntryType,
    pub from_status: Option<String>,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<OrderStatusTimeline> for OrderStatusTimelineResponseDto {
    fn from(entity: OrderStatusTimeline) -> Self {
        Self {
            id: entity.id,
            order_id: entity.order_id,
            entry_type: entity.entry_type,
            from_status: entity.from_status,
            to_status: entity.to_status,
            occurred_at: entity.occurred_at,
            actor_type: entity.actor_type,
            actor_id: entity.actor_id,
            actor_name: entity.actor_name,
            actor_role: entity.actor_role,
            title: entity.title,
            description: entity.description,
            latitude: entity.latitude,
            longitude: entity.longitude,
            location_name: entity.location_name,
            is_customer_visible: entity.is_customer_visible,
            is_provider_visible: entity.is_provider_visible,
            is_agent_visible: entity.is_agent_visible,
            attachments: entity.attachments,
            duration_minutes: entity.duration_minutes,
            channel: entity.channel,
            device_info: entity.device_info,
            ip_address: entity.ip_address,
            metadata: entity.metadata,
        }
    }
}

impl From<OrderStatusTimeline> for OrderStatusTimelineSummaryDto {
    fn from(entity: OrderStatusTimeline) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            order_id: entity.order_id,
            entry_type: entity.entry_type,
            from_status: entity.from_status,
            created_at,
        }
    }
}

impl From<CreateOrderStatusTimelineDto> for OrderStatusTimeline {
    fn from(dto: CreateOrderStatusTimelineDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            order_id: dto.order_id,
            entry_type: dto.entry_type,
            from_status: dto.from_status,
            to_status: dto.to_status,
            occurred_at: dto.occurred_at,
            actor_type: dto.actor_type,
            actor_id: dto.actor_id,
            actor_name: dto.actor_name,
            actor_role: dto.actor_role,
            title: dto.title,
            description: dto.description,
            latitude: dto.latitude,
            longitude: dto.longitude,
            location_name: dto.location_name,
            is_customer_visible: dto.is_customer_visible,
            is_provider_visible: dto.is_provider_visible,
            is_agent_visible: dto.is_agent_visible,
            attachments: dto.attachments,
            duration_minutes: dto.duration_minutes,
            channel: dto.channel,
            device_info: dto.device_info,
            ip_address: dto.ip_address,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&OrderStatusTimeline> for OrderStatusTimelineResponseDto {
    fn from(entity: &OrderStatusTimeline) -> Self {
        Self {
            id: entity.id.clone(),
            order_id: entity.order_id.clone(),
            entry_type: entity.entry_type.clone(),
            from_status: entity.from_status.clone(),
            to_status: entity.to_status.clone(),
            occurred_at: entity.occurred_at.clone(),
            actor_type: entity.actor_type.clone(),
            actor_id: entity.actor_id.clone(),
            actor_name: entity.actor_name.clone(),
            actor_role: entity.actor_role.clone(),
            title: entity.title.clone(),
            description: entity.description.clone(),
            latitude: entity.latitude.clone(),
            longitude: entity.longitude.clone(),
            location_name: entity.location_name.clone(),
            is_customer_visible: entity.is_customer_visible.clone(),
            is_provider_visible: entity.is_provider_visible.clone(),
            is_agent_visible: entity.is_agent_visible.clone(),
            attachments: entity.attachments.clone(),
            duration_minutes: entity.duration_minutes.clone(),
            channel: entity.channel.clone(),
            device_info: entity.device_info.clone(),
            ip_address: entity.ip_address.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateOrderStatusTimelineDto> for OrderStatusTimeline {
    fn from_create_dto(dto: CreateOrderStatusTimelineDto) -> backbone_core::ServiceResult<Self> {
        Ok(OrderStatusTimeline::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateOrderStatusTimelineDto> for OrderStatusTimeline {
    fn apply_update(mut self, dto: UpdateOrderStatusTimelineDto) -> backbone_core::ServiceResult<Self> {
        self.order_id = dto.order_id;
        self.entry_type = dto.entry_type;
        self.from_status = dto.from_status;
        self.to_status = dto.to_status;
        self.occurred_at = dto.occurred_at;
        self.actor_type = dto.actor_type;
        self.actor_id = dto.actor_id;
        self.actor_name = dto.actor_name;
        self.actor_role = dto.actor_role;
        self.title = dto.title;
        self.description = dto.description;
        self.latitude = dto.latitude;
        self.longitude = dto.longitude;
        self.location_name = dto.location_name;
        self.is_customer_visible = dto.is_customer_visible;
        self.is_provider_visible = dto.is_provider_visible;
        self.is_agent_visible = dto.is_agent_visible;
        self.attachments = dto.attachments;
        self.duration_minutes = dto.duration_minutes;
        self.channel = dto.channel;
        self.device_info = dto.device_info;
        self.ip_address = dto.ip_address;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to OrderStatusTimeline here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

