//! OrderDelivery DTOs (Data Transfer Objects)
//!
//! Auto-generated by backbone-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc, NaiveDate};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::OrderDelivery;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::DeliveryStatus;
use crate::domain::entity::DeliveryType;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new OrderDelivery
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateOrderDeliveryDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub order_id: Uuid,
    pub delivery_type: DeliveryType,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    pub scheduled_date: NaiveDate,
    #[cfg_attr(feature = "validation", validate(range(max = 5)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub scheduled_time_start: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 5)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub scheduled_time_end: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 30)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub time_slot: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub customer_requested_date: Option<NaiveDate>,
    #[cfg_attr(feature = "validation", validate(range(max = 5)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub customer_requested_time_start: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 5)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub customer_requested_time_end: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub address_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 255)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub address_line: String,
    #[cfg_attr(feature = "validation", validate(range(max = 255)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub address_detail: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 100)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub landmark: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub latitude: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub longitude: Option<f64>,
    #[cfg_attr(feature = "validation", validate(length(max = 100)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub contact_name: String,
    #[cfg_attr(feature = "validation", validate(length(max = 20)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub contact_phone: String,
    #[cfg_attr(feature = "validation", validate(range(max = 20)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub contact_phone_alt: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub agent_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(range(max = 100)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub agent_name: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 20)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub agent_phone: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub assigned_at: Option<DateTime<Utc>>,
    pub status: DeliveryStatus,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub dispatched_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub en_route_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arrived_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub delivered_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub item_count: i32,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub bag_count: i32,
    pub bag_numbers: serde_json::Value,
    #[cfg_attr(feature = "validation", validate(range(max = 30)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub verification_method: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 10)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub verification_code: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub verified_at: Option<DateTime<Utc>>,
    pub photos: serde_json::Value,
    #[cfg_attr(feature = "validation", validate(range(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub proof_photo_url: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub signature_url: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 100)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub signed_by: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 50)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub relation_to_customer: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub delivery_latitude: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub delivery_longitude: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub distance_from_address_meters: Option<i32>,
    pub delivery_fee: Decimal,
    pub express_fee: Decimal,
    pub total_fee: Decimal,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub currency: String,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_cod: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cod_amount: Option<Decimal>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub cod_collected: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cod_collected_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "validation", validate(range(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub customer_notes: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub agent_notes: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub internal_notes: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 255)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub failure_reason: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 30)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub failure_code: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub attempt_count: i32,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub reschedule_count: i32,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub original_scheduled_date: Option<NaiveDate>,
    #[cfg_attr(feature = "validation", validate(range(max = 255)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reschedule_reason: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub delivery_rating: Option<i32>,
    #[cfg_attr(feature = "validation", validate(range(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub rating_comment: Option<String>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a OrderDelivery
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateOrderDeliveryDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub order_id: Uuid,
    pub delivery_type: DeliveryType,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    pub scheduled_date: NaiveDate,
    #[cfg_attr(feature = "validation", validate(range(max = 5)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub scheduled_time_start: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 5)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub scheduled_time_end: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 30)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub time_slot: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub customer_requested_date: Option<NaiveDate>,
    #[cfg_attr(feature = "validation", validate(range(max = 5)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub customer_requested_time_start: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 5)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub customer_requested_time_end: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub address_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 255)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub address_line: String,
    #[cfg_attr(feature = "validation", validate(range(max = 255)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub address_detail: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 100)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub landmark: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub latitude: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub longitude: Option<f64>,
    #[cfg_attr(feature = "validation", validate(length(max = 100)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub contact_name: String,
    #[cfg_attr(feature = "validation", validate(length(max = 20)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub contact_phone: String,
    #[cfg_attr(feature = "validation", validate(range(max = 20)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub contact_phone_alt: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub agent_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(range(max = 100)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub agent_name: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 20)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub agent_phone: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub assigned_at: Option<DateTime<Utc>>,
    pub status: DeliveryStatus,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub dispatched_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub en_route_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arrived_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub delivered_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub item_count: i32,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub bag_count: i32,
    pub bag_numbers: serde_json::Value,
    #[cfg_attr(feature = "validation", validate(range(max = 30)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub verification_method: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 10)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub verification_code: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub verified_at: Option<DateTime<Utc>>,
    pub photos: serde_json::Value,
    #[cfg_attr(feature = "validation", validate(range(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub proof_photo_url: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub signature_url: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 100)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub signed_by: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 50)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub relation_to_customer: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub delivery_latitude: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub delivery_longitude: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub distance_from_address_meters: Option<i32>,
    pub delivery_fee: Decimal,
    pub express_fee: Decimal,
    pub total_fee: Decimal,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub currency: String,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_cod: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cod_amount: Option<Decimal>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub cod_collected: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cod_collected_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "validation", validate(range(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub customer_notes: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub agent_notes: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub internal_notes: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 255)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub failure_reason: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 30)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub failure_code: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub attempt_count: i32,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub reschedule_count: i32,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub original_scheduled_date: Option<NaiveDate>,
    #[cfg_attr(feature = "validation", validate(range(max = 255)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reschedule_reason: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub delivery_rating: Option<i32>,
    #[cfg_attr(feature = "validation", validate(range(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub rating_comment: Option<String>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a OrderDelivery
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchOrderDeliveryDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub order_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub delivery_type: Option<DeliveryType>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub scheduled_date: Option<NaiveDate>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub scheduled_time_start: Option<String>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub scheduled_time_end: Option<String>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub time_slot: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub customer_requested_date: Option<NaiveDate>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub customer_requested_time_start: Option<String>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub customer_requested_time_end: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub address_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub address_line: Option<String>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub address_detail: Option<String>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub landmark: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub latitude: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub longitude: Option<f64>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub contact_name: Option<String>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub contact_phone: Option<String>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub contact_phone_alt: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub agent_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub agent_name: Option<String>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub agent_phone: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub assigned_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<DeliveryStatus>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub dispatched_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub en_route_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub arrived_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub delivered_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub item_count: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bag_count: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bag_numbers: Option<serde_json::Value>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub verification_method: Option<String>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub verification_code: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub verified_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub photos: Option<serde_json::Value>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub proof_photo_url: Option<String>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub signature_url: Option<String>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub signed_by: Option<String>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub relation_to_customer: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub delivery_latitude: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub delivery_longitude: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub distance_from_address_meters: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub delivery_fee: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub express_fee: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub total_fee: Option<Decimal>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub currency: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub is_cod: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cod_amount: Option<Decimal>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cod_collected: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cod_collected_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub customer_notes: Option<String>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub agent_notes: Option<String>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub internal_notes: Option<String>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub failure_reason: Option<String>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub failure_code: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub attempt_count: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reschedule_count: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub original_scheduled_date: Option<NaiveDate>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reschedule_reason: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub delivery_rating: Option<i32>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub rating_comment: Option<String>,
}

impl PatchOrderDeliveryDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.order_id.is_some() || self.delivery_type.is_some() || self.scheduled_date.is_some() || self.scheduled_time_start.is_some() || self.scheduled_time_end.is_some() || self.time_slot.is_some() || self.customer_requested_date.is_some() || self.customer_requested_time_start.is_some() || self.customer_requested_time_end.is_some() || self.address_id.is_some() || self.address_line.is_some() || self.address_detail.is_some() || self.landmark.is_some() || self.latitude.is_some() || self.longitude.is_some() || self.contact_name.is_some() || self.contact_phone.is_some() || self.contact_phone_alt.is_some() || self.agent_id.is_some() || self.agent_name.is_some() || self.agent_phone.is_some() || self.assigned_at.is_some() || self.status.is_some() || self.dispatched_at.is_some() || self.en_route_at.is_some() || self.arrived_at.is_some() || self.delivered_at.is_some() || self.item_count.is_some() || self.bag_count.is_some() || self.bag_numbers.is_some() || self.verification_method.is_some() || self.verification_code.is_some() || self.verified_at.is_some() || self.photos.is_some() || self.proof_photo_url.is_some() || self.signature_url.is_some() || self.signed_by.is_some() || self.relation_to_customer.is_some() || self.delivery_latitude.is_some() || self.delivery_longitude.is_some() || self.distance_from_address_meters.is_some() || self.delivery_fee.is_some() || self.express_fee.is_some() || self.total_fee.is_some() || self.currency.is_some() || self.is_cod.is_some() || self.cod_amount.is_some() || self.cod_collected.is_some() || self.cod_collected_at.is_some() || self.customer_notes.is_some() || self.agent_notes.is_some() || self.internal_notes.is_some() || self.failure_reason.is_some() || self.failure_code.is_some() || self.attempt_count.is_some() || self.reschedule_count.is_some() || self.original_scheduled_date.is_some() || self.reschedule_reason.is_some() || self.delivery_rating.is_some() || self.rating_comment.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for OrderDelivery entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct OrderDeliveryResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub order_id: Uuid,
    pub delivery_type: DeliveryType,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    pub scheduled_date: NaiveDate,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub scheduled_time_start: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub scheduled_time_end: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub time_slot: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub customer_requested_date: Option<NaiveDate>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub customer_requested_time_start: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub customer_requested_time_end: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub address_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub address_line: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub address_detail: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub landmark: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub latitude: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub longitude: Option<f64>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub contact_name: String,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub contact_phone: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub contact_phone_alt: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub agent_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub agent_name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub agent_phone: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub assigned_at: Option<DateTime<Utc>>,
    pub status: DeliveryStatus,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub dispatched_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub en_route_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub arrived_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub delivered_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub item_count: i32,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub bag_count: i32,
    pub bag_numbers: serde_json::Value,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub verification_method: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub verification_code: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub verified_at: Option<DateTime<Utc>>,
    pub photos: serde_json::Value,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub proof_photo_url: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub signature_url: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub signed_by: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub relation_to_customer: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub delivery_latitude: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub delivery_longitude: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub distance_from_address_meters: Option<i32>,
    pub delivery_fee: Decimal,
    pub express_fee: Decimal,
    pub total_fee: Decimal,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub currency: String,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_cod: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cod_amount: Option<Decimal>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub cod_collected: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cod_collected_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub customer_notes: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub agent_notes: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub internal_notes: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub failure_reason: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub failure_code: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub attempt_count: i32,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub reschedule_count: i32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub original_scheduled_date: Option<NaiveDate>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reschedule_reason: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub delivery_rating: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub rating_comment: Option<String>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for OrderDelivery entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct OrderDeliveryListResponseDto {
    /// List of items
    pub items: Vec<OrderDeliveryResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl OrderDeliveryListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<OrderDeliveryResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct OrderDeliverySummaryDto {
    pub id: Uuid,
    pub order_id: Uuid,
    pub delivery_type: DeliveryType,
    pub scheduled_date: NaiveDate,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<OrderDelivery> for OrderDeliveryResponseDto {
    fn from(entity: OrderDelivery) -> Self {
        Self {
            id: entity.id,
            order_id: entity.order_id,
            delivery_type: entity.delivery_type,
            scheduled_date: entity.scheduled_date,
            scheduled_time_start: entity.scheduled_time_start,
            scheduled_time_end: entity.scheduled_time_end,
            time_slot: entity.time_slot,
            customer_requested_date: entity.customer_requested_date,
            customer_requested_time_start: entity.customer_requested_time_start,
            customer_requested_time_end: entity.customer_requested_time_end,
            address_id: entity.address_id,
            address_line: entity.address_line,
            address_detail: entity.address_detail,
            landmark: entity.landmark,
            latitude: entity.latitude,
            longitude: entity.longitude,
            contact_name: entity.contact_name,
            contact_phone: entity.contact_phone,
            contact_phone_alt: entity.contact_phone_alt,
            agent_id: entity.agent_id,
            agent_name: entity.agent_name,
            agent_phone: entity.agent_phone,
            assigned_at: entity.assigned_at,
            status: entity.status,
            dispatched_at: entity.dispatched_at,
            en_route_at: entity.en_route_at,
            arrived_at: entity.arrived_at,
            delivered_at: entity.delivered_at,
            item_count: entity.item_count,
            bag_count: entity.bag_count,
            bag_numbers: entity.bag_numbers,
            verification_method: entity.verification_method,
            verification_code: entity.verification_code,
            verified_at: entity.verified_at,
            photos: entity.photos,
            proof_photo_url: entity.proof_photo_url,
            signature_url: entity.signature_url,
            signed_by: entity.signed_by,
            relation_to_customer: entity.relation_to_customer,
            delivery_latitude: entity.delivery_latitude,
            delivery_longitude: entity.delivery_longitude,
            distance_from_address_meters: entity.distance_from_address_meters,
            delivery_fee: entity.delivery_fee,
            express_fee: entity.express_fee,
            total_fee: entity.total_fee,
            currency: entity.currency,
            is_cod: entity.is_cod,
            cod_amount: entity.cod_amount,
            cod_collected: entity.cod_collected,
            cod_collected_at: entity.cod_collected_at,
            customer_notes: entity.customer_notes,
            agent_notes: entity.agent_notes,
            internal_notes: entity.internal_notes,
            failure_reason: entity.failure_reason,
            failure_code: entity.failure_code,
            attempt_count: entity.attempt_count,
            reschedule_count: entity.reschedule_count,
            original_scheduled_date: entity.original_scheduled_date,
            reschedule_reason: entity.reschedule_reason,
            delivery_rating: entity.delivery_rating,
            rating_comment: entity.rating_comment,
            metadata: entity.metadata,
        }
    }
}

impl From<OrderDelivery> for OrderDeliverySummaryDto {
    fn from(entity: OrderDelivery) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            order_id: entity.order_id,
            delivery_type: entity.delivery_type,
            scheduled_date: entity.scheduled_date,
            created_at,
        }
    }
}

impl From<CreateOrderDeliveryDto> for OrderDelivery {
    fn from(dto: CreateOrderDeliveryDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            order_id: dto.order_id,
            delivery_type: dto.delivery_type,
            scheduled_date: dto.scheduled_date,
            scheduled_time_start: dto.scheduled_time_start,
            scheduled_time_end: dto.scheduled_time_end,
            time_slot: dto.time_slot,
            customer_requested_date: dto.customer_requested_date,
            customer_requested_time_start: dto.customer_requested_time_start,
            customer_requested_time_end: dto.customer_requested_time_end,
            address_id: dto.address_id,
            address_line: dto.address_line,
            address_detail: dto.address_detail,
            landmark: dto.landmark,
            latitude: dto.latitude,
            longitude: dto.longitude,
            contact_name: dto.contact_name,
            contact_phone: dto.contact_phone,
            contact_phone_alt: dto.contact_phone_alt,
            agent_id: dto.agent_id,
            agent_name: dto.agent_name,
            agent_phone: dto.agent_phone,
            assigned_at: dto.assigned_at,
            status: dto.status,
            dispatched_at: dto.dispatched_at,
            en_route_at: dto.en_route_at,
            arrived_at: dto.arrived_at,
            delivered_at: dto.delivered_at,
            item_count: dto.item_count,
            bag_count: dto.bag_count,
            bag_numbers: dto.bag_numbers,
            verification_method: dto.verification_method,
            verification_code: dto.verification_code,
            verified_at: dto.verified_at,
            photos: dto.photos,
            proof_photo_url: dto.proof_photo_url,
            signature_url: dto.signature_url,
            signed_by: dto.signed_by,
            relation_to_customer: dto.relation_to_customer,
            delivery_latitude: dto.delivery_latitude,
            delivery_longitude: dto.delivery_longitude,
            distance_from_address_meters: dto.distance_from_address_meters,
            delivery_fee: dto.delivery_fee,
            express_fee: dto.express_fee,
            total_fee: dto.total_fee,
            currency: dto.currency,
            is_cod: dto.is_cod,
            cod_amount: dto.cod_amount,
            cod_collected: dto.cod_collected,
            cod_collected_at: dto.cod_collected_at,
            customer_notes: dto.customer_notes,
            agent_notes: dto.agent_notes,
            internal_notes: dto.internal_notes,
            failure_reason: dto.failure_reason,
            failure_code: dto.failure_code,
            attempt_count: dto.attempt_count,
            reschedule_count: dto.reschedule_count,
            original_scheduled_date: dto.original_scheduled_date,
            reschedule_reason: dto.reschedule_reason,
            delivery_rating: dto.delivery_rating,
            rating_comment: dto.rating_comment,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&OrderDelivery> for OrderDeliveryResponseDto {
    fn from(entity: &OrderDelivery) -> Self {
        Self {
            id: entity.id.clone(),
            order_id: entity.order_id.clone(),
            delivery_type: entity.delivery_type.clone(),
            scheduled_date: entity.scheduled_date.clone(),
            scheduled_time_start: entity.scheduled_time_start.clone(),
            scheduled_time_end: entity.scheduled_time_end.clone(),
            time_slot: entity.time_slot.clone(),
            customer_requested_date: entity.customer_requested_date.clone(),
            customer_requested_time_start: entity.customer_requested_time_start.clone(),
            customer_requested_time_end: entity.customer_requested_time_end.clone(),
            address_id: entity.address_id.clone(),
            address_line: entity.address_line.clone(),
            address_detail: entity.address_detail.clone(),
            landmark: entity.landmark.clone(),
            latitude: entity.latitude.clone(),
            longitude: entity.longitude.clone(),
            contact_name: entity.contact_name.clone(),
            contact_phone: entity.contact_phone.clone(),
            contact_phone_alt: entity.contact_phone_alt.clone(),
            agent_id: entity.agent_id.clone(),
            agent_name: entity.agent_name.clone(),
            agent_phone: entity.agent_phone.clone(),
            assigned_at: entity.assigned_at.clone(),
            status: entity.status.clone(),
            dispatched_at: entity.dispatched_at.clone(),
            en_route_at: entity.en_route_at.clone(),
            arrived_at: entity.arrived_at.clone(),
            delivered_at: entity.delivered_at.clone(),
            item_count: entity.item_count.clone(),
            bag_count: entity.bag_count.clone(),
            bag_numbers: entity.bag_numbers.clone(),
            verification_method: entity.verification_method.clone(),
            verification_code: entity.verification_code.clone(),
            verified_at: entity.verified_at.clone(),
            photos: entity.photos.clone(),
            proof_photo_url: entity.proof_photo_url.clone(),
            signature_url: entity.signature_url.clone(),
            signed_by: entity.signed_by.clone(),
            relation_to_customer: entity.relation_to_customer.clone(),
            delivery_latitude: entity.delivery_latitude.clone(),
            delivery_longitude: entity.delivery_longitude.clone(),
            distance_from_address_meters: entity.distance_from_address_meters.clone(),
            delivery_fee: entity.delivery_fee.clone(),
            express_fee: entity.express_fee.clone(),
            total_fee: entity.total_fee.clone(),
            currency: entity.currency.clone(),
            is_cod: entity.is_cod.clone(),
            cod_amount: entity.cod_amount.clone(),
            cod_collected: entity.cod_collected.clone(),
            cod_collected_at: entity.cod_collected_at.clone(),
            customer_notes: entity.customer_notes.clone(),
            agent_notes: entity.agent_notes.clone(),
            internal_notes: entity.internal_notes.clone(),
            failure_reason: entity.failure_reason.clone(),
            failure_code: entity.failure_code.clone(),
            attempt_count: entity.attempt_count.clone(),
            reschedule_count: entity.reschedule_count.clone(),
            original_scheduled_date: entity.original_scheduled_date.clone(),
            reschedule_reason: entity.reschedule_reason.clone(),
            delivery_rating: entity.delivery_rating.clone(),
            rating_comment: entity.rating_comment.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateOrderDeliveryDto> for OrderDelivery {
    fn from_create_dto(dto: CreateOrderDeliveryDto) -> backbone_core::ServiceResult<Self> {
        Ok(OrderDelivery::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateOrderDeliveryDto> for OrderDelivery {
    fn apply_update(mut self, dto: UpdateOrderDeliveryDto) -> backbone_core::ServiceResult<Self> {
        self.order_id = dto.order_id;
        self.delivery_type = dto.delivery_type;
        self.scheduled_date = dto.scheduled_date;
        self.scheduled_time_start = dto.scheduled_time_start;
        self.scheduled_time_end = dto.scheduled_time_end;
        self.time_slot = dto.time_slot;
        self.customer_requested_date = dto.customer_requested_date;
        self.customer_requested_time_start = dto.customer_requested_time_start;
        self.customer_requested_time_end = dto.customer_requested_time_end;
        self.address_id = dto.address_id;
        self.address_line = dto.address_line;
        self.address_detail = dto.address_detail;
        self.landmark = dto.landmark;
        self.latitude = dto.latitude;
        self.longitude = dto.longitude;
        self.contact_name = dto.contact_name;
        self.contact_phone = dto.contact_phone;
        self.contact_phone_alt = dto.contact_phone_alt;
        self.agent_id = dto.agent_id;
        self.agent_name = dto.agent_name;
        self.agent_phone = dto.agent_phone;
        self.assigned_at = dto.assigned_at;
        self.status = dto.status;
        self.dispatched_at = dto.dispatched_at;
        self.en_route_at = dto.en_route_at;
        self.arrived_at = dto.arrived_at;
        self.delivered_at = dto.delivered_at;
        self.item_count = dto.item_count;
        self.bag_count = dto.bag_count;
        self.bag_numbers = dto.bag_numbers;
        self.verification_method = dto.verification_method;
        self.verification_code = dto.verification_code;
        self.verified_at = dto.verified_at;
        self.photos = dto.photos;
        self.proof_photo_url = dto.proof_photo_url;
        self.signature_url = dto.signature_url;
        self.signed_by = dto.signed_by;
        self.relation_to_customer = dto.relation_to_customer;
        self.delivery_latitude = dto.delivery_latitude;
        self.delivery_longitude = dto.delivery_longitude;
        self.distance_from_address_meters = dto.distance_from_address_meters;
        self.delivery_fee = dto.delivery_fee;
        self.express_fee = dto.express_fee;
        self.total_fee = dto.total_fee;
        self.currency = dto.currency;
        self.is_cod = dto.is_cod;
        self.cod_amount = dto.cod_amount;
        self.cod_collected = dto.cod_collected;
        self.cod_collected_at = dto.cod_collected_at;
        self.customer_notes = dto.customer_notes;
        self.agent_notes = dto.agent_notes;
        self.internal_notes = dto.internal_notes;
        self.failure_reason = dto.failure_reason;
        self.failure_code = dto.failure_code;
        self.attempt_count = dto.attempt_count;
        self.reschedule_count = dto.reschedule_count;
        self.original_scheduled_date = dto.original_scheduled_date;
        self.reschedule_reason = dto.reschedule_reason;
        self.delivery_rating = dto.delivery_rating;
        self.rating_comment = dto.rating_comment;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to OrderDelivery here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

