//! GraphQL schema composition for Orders module
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Provides both standalone `build_schema()` and composable `inject_services()`
//! methods. Use `inject_services()` to compose module GraphQL services into
//! a shared app-level schema.

use std::sync::Arc;
use async_graphql::*;

use super::{DeliveryTierQuery, DeliveryTierMutation};
use super::{OrderQuery, OrderMutation};
use super::{OrderDeliveryQuery, OrderDeliveryMutation};
use super::{OrderItemQuery, OrderItemMutation};
use super::{OrderPickupQuery, OrderPickupMutation};
use super::{OrderStatusTimelineQuery, OrderStatusTimelineMutation};

use crate::application::service::DeliveryTierService;
use crate::application::service::OrderService;
use crate::application::service::OrderDeliveryService;
use crate::application::service::OrderItemService;
use crate::application::service::OrderPickupService;
use crate::application::service::OrderStatusTimelineService;

/// Merged Query root for Orders module
#[derive(MergedObject, Default)]
pub struct OrdersQuery(DeliveryTierQuery, OrderQuery, OrderDeliveryQuery, OrderItemQuery, OrderPickupQuery, 
    OrderStatusTimelineQuery);

/// Merged Mutation root for Orders module
#[derive(MergedObject, Default)]
pub struct OrdersMutation(DeliveryTierMutation, OrderMutation, OrderDeliveryMutation, OrderItemMutation, OrderPickupMutation, 
    OrderStatusTimelineMutation);

/// Inject all Orders services into a schema builder
pub fn inject_services<Q: ObjectType + 'static, M: ObjectType + 'static, S: SubscriptionType + 'static>(
    builder: SchemaBuilder<Q, M, S>,
    module: &crate::OrdersModule,
) -> SchemaBuilder<Q, M, S> {
    builder
        .data(module.delivery_tier_service.clone())
        .data(module.order_service.clone())
        .data(module.order_delivery_service.clone())
        .data(module.order_item_service.clone())
        .data(module.order_pickup_service.clone())
        .data(module.order_status_timeline_service.clone())
}

/// Build the GraphQL schema for Orders module (standalone)
pub fn build_schema(module: &crate::OrdersModule) -> Schema<OrdersQuery, OrdersMutation, EmptySubscription> {
    let builder = Schema::build(OrdersQuery::default(), OrdersMutation::default(), EmptySubscription);
    inject_services(builder, module).finish()
}
