//! gRPC service registration
//!
//! Generated by backbone-schema. Do not edit manually.

use tonic::transport::Server;

use super::grpc::delivery_tier_grpc_service::DeliveryTierGrpcService;
use super::grpc::order_grpc_service::OrderGrpcService;
use super::grpc::order_delivery_grpc_service::OrderDeliveryGrpcService;
use super::grpc::order_item_grpc_service::OrderItemGrpcService;
use super::grpc::order_pickup_grpc_service::OrderPickupGrpcService;
use super::grpc::order_status_timeline_grpc_service::OrderStatusTimelineGrpcService;

/// gRPC server for Orders module
pub struct OrdersGrpcServer {
    delivery_tier_service: DeliveryTierGrpcService,
    order_service: OrderGrpcService,
    order_delivery_service: OrderDeliveryGrpcService,
    order_item_service: OrderItemGrpcService,
    order_pickup_service: OrderPickupGrpcService,
    order_status_timeline_service: OrderStatusTimelineGrpcService,
}

impl OrdersGrpcServer {
    /// Create a new gRPC server from module
    pub fn new(module: &super::OrdersModule) -> Self {
        Self {
            delivery_tier_service: DeliveryTierGrpcService::new(module.delivery_tier_service.clone()),
            order_service: OrderGrpcService::new(module.order_service.clone()),
            order_delivery_service: OrderDeliveryGrpcService::new(module.order_delivery_service.clone()),
            order_item_service: OrderItemGrpcService::new(module.order_item_service.clone()),
            order_pickup_service: OrderPickupGrpcService::new(module.order_pickup_service.clone()),
            order_status_timeline_service: OrderStatusTimelineGrpcService::new(module.order_status_timeline_service.clone()),
        }
    }

    /// Start the gRPC server
    pub async fn serve(self, addr: std::net::SocketAddr) -> Result<(), tonic::transport::Error> {
        Server::builder()
            .add_service(self.delivery_tier_service.into_service())
            .add_service(self.order_service.into_service())
            .add_service(self.order_delivery_service.into_service())
            .add_service(self.order_item_service.into_service())
            .add_service(self.order_pickup_service.into_service())
            .add_service(self.order_status_timeline_service.into_service())
            .serve(addr)
            .await
    }
}
