//! Domain specifications
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Combinators (AND/OR/NOT) come from `backbone_core::Specification`.

pub use backbone_core::{Specification, AndSpecification, OrSpecification, NotSpecification};

pub mod delivery_tier_specification;
pub mod order_specification;
pub mod order_delivery_specification;
pub mod order_item_specification;
pub mod order_pickup_specification;
pub mod order_status_timeline_specification;

// <<< CUSTOM
// END CUSTOM
