//! Domain policy for OrderStatusTimeline aggregate
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! `DomainPolicy` enforces pure business invariants (state-based rules).
//! Identity-based rules live in `backbone_auth::ResourcePolicy`.

use backbone_core::PermitAllPolicy;
use crate::domain::entity::OrderStatusTimeline;

/// Domain policy for OrderStatusTimeline — permits all operations (no business invariants).
///
/// To add domain rules, replace this alias with a struct implementing
/// `backbone_core::DomainPolicy<OrderStatusTimeline>` in the `// <<< CUSTOM` zone.
pub type OrderStatusTimelineDomainPolicy = PermitAllPolicy<OrderStatusTimeline>;

// <<< CUSTOM
// END CUSTOM
