//! Domain policy for OrderPickup aggregate
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! `DomainPolicy` enforces pure business invariants (state-based rules).
//! Identity-based rules live in `backbone_auth::ResourcePolicy`.

use backbone_core::PermitAllPolicy;
use crate::domain::entity::OrderPickup;

/// Domain policy for OrderPickup — permits all operations (no business invariants).
///
/// To add domain rules, replace this alias with a struct implementing
/// `backbone_core::DomainPolicy<OrderPickup>` in the `// <<< CUSTOM` zone.
pub type OrderPickupDomainPolicy = PermitAllPolicy<OrderPickup>;

// <<< CUSTOM
// END CUSTOM
