//! Domain policy for OrderDelivery aggregate
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! `DomainPolicy` enforces pure business invariants (state-based rules).
//! Identity-based rules live in `backbone_auth::ResourcePolicy`.

use backbone_core::PermitAllPolicy;
use crate::domain::entity::OrderDelivery;

/// Domain policy for OrderDelivery — permits all operations (no business invariants).
///
/// To add domain rules, replace this alias with a struct implementing
/// `backbone_core::DomainPolicy<OrderDelivery>` in the `// <<< CUSTOM` zone.
pub type OrderDeliveryDomainPolicy = PermitAllPolicy<OrderDelivery>;

// <<< CUSTOM
// END CUSTOM
