//! Application service for DeliveryTier entities
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `delivery_tier_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateDeliveryTierDto, UpdateDeliveryTierDto};
use crate::domain::entity::DeliveryTier;
use crate::infrastructure::persistence::DeliveryTierRepository;

/// Application service for DeliveryTier entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `delivery_tier_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct DeliveryTierServiceCustom {
///     inner: Arc<DeliveryTierService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type DeliveryTierService = GenericCrudService<
    DeliveryTier,
    CreateDeliveryTierDto,
    UpdateDeliveryTierDto,
    DeliveryTierRepository,
>;

// <<< CUSTOM
// END CUSTOM
