//! Application services
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Each entity service is a type alias over `GenericCrudService`.

pub mod error;
pub use error::{ServiceError, ServiceResult};

mod delivery_tier_service;
mod order_service;
mod order_delivery_service;
mod order_item_service;
mod order_pickup_service;
mod order_status_timeline_service;

// <<< CUSTOM
// END CUSTOM

pub use delivery_tier_service::DeliveryTierService;
pub use order_service::OrderService;
pub use order_delivery_service::OrderDeliveryService;
pub use order_item_service::OrderItemService;
pub use order_pickup_service::OrderPickupService;
pub use order_status_timeline_service::OrderStatusTimelineService;
// <<< CUSTOM
// END CUSTOM
