//! Application service for OrderStatusTimeline entities
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `order_status_timeline_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateOrderStatusTimelineDto, UpdateOrderStatusTimelineDto};
use crate::domain::entity::OrderStatusTimeline;
use crate::infrastructure::persistence::OrderStatusTimelineRepository;

/// Application service for OrderStatusTimeline entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `order_status_timeline_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct OrderStatusTimelineServiceCustom {
///     inner: Arc<OrderStatusTimelineService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type OrderStatusTimelineService = GenericCrudService<
    OrderStatusTimeline,
    CreateOrderStatusTimelineDto,
    UpdateOrderStatusTimelineDto,
    OrderStatusTimelineRepository,
>;

// <<< CUSTOM
// END CUSTOM
