//! Application service for OrderDelivery entities
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `order_delivery_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateOrderDeliveryDto, UpdateOrderDeliveryDto};
use crate::domain::entity::OrderDelivery;
use crate::infrastructure::persistence::OrderDeliveryRepository;

/// Application service for OrderDelivery entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `order_delivery_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct OrderDeliveryServiceCustom {
///     inner: Arc<OrderDeliveryService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type OrderDeliveryService = GenericCrudService<
    OrderDelivery,
    CreateOrderDeliveryDto,
    UpdateOrderDeliveryDto,
    OrderDeliveryRepository,
>;

// <<< CUSTOM
// END CUSTOM
