//! Application service for Order entities
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `order_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateOrderDto, UpdateOrderDto};
use crate::domain::entity::Order;
use crate::infrastructure::persistence::OrderRepository;

/// Application service for Order entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `order_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct OrderServiceCustom {
///     inner: Arc<OrderService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type OrderService = GenericCrudService<
    Order,
    CreateOrderDto,
    UpdateOrderDto,
    OrderRepository,
>;

// <<< CUSTOM
// END CUSTOM
