//! Application service for OrderItem entities
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `order_item_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateOrderItemDto, UpdateOrderItemDto};
use crate::domain::entity::OrderItem;
use crate::infrastructure::persistence::OrderItemRepository;

/// Application service for OrderItem entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `order_item_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct OrderItemServiceCustom {
///     inner: Arc<OrderItemService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type OrderItemService = GenericCrudService<
    OrderItem,
    CreateOrderItemDto,
    UpdateOrderItemDto,
    OrderItemRepository,
>;

// <<< CUSTOM
// END CUSTOM
