-- DeliveryTier Seed Data
-- Generated by backbone-schema
--
-- This file contains initial seed data for the delivery_tiers table.
-- Customize this file to add your initial data.

-- INSERT INTO delivery_tiers (
--     id,
--     code,
--     name,
--     name_en,
--     description,
--     duration_hours,
--     duration_label,
--     color,
--     icon,
--     is_urgent,
--     sort_order,
--     is_active,
--     is_default,
--     provider_id,
--     outlet_id,
--     source_id,
--     is_cloned,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert reference data
-- Uncomment and modify the following:

-- INSERT INTO delivery_tiers (id, code, name, is_active, created_at, updated_at) VALUES
--     (gen_random_uuid(), 'SAMPLE1', 'Sample 1', true, NOW(), NOW()),
--     (gen_random_uuid(), 'SAMPLE2', 'Sample 2', true, NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

