-- OrderStatusTimeline Seed Data
-- Generated by backbone-schema
--
-- This file contains initial seed data for the order_status_timelines table.
-- Customize this file to add your initial data.

-- INSERT INTO order_status_timelines (
--     id,
--     order_id,
--     entry_type,
--     from_status,
--     to_status,
--     occurred_at,
--     actor_type,
--     actor_id,
--     actor_name,
--     actor_role,
--     title,
--     description,
--     latitude,
--     longitude,
--     location_name,
--     is_customer_visible,
--     is_provider_visible,
--     is_agent_visible,
--     attachments,
--     duration_minutes,
--     channel,
--     device_info,
--     ip_address,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO order_status_timelines (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

