-- OrderItem Seed Data
-- Generated by backbone-schema
--
-- This file contains initial seed data for the order_items table.
-- Customize this file to add your initial data.

-- INSERT INTO order_items (
--     id,
--     order_id,
--     service_id,
--     item_name,
--     quantity,
--     unit_type,
--     unit_price,
--     subtotal,
--     discount,
--     addon_total,
--     total,
--     currency,
--     addons,
--     condition_on_receipt,
--     condition_notes,
--     processing_status,
--     special_instructions,
--     processing_notes,
--     delivery_tier_id,
--     started_at,
--     completed_at,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO order_items (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

