-- Enum types for orders module
-- Generated by backbone-schema

-- Create order_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'order_status') THEN
        CREATE TYPE order_status AS ENUM ('pending', 'confirmed', 'pickup_scheduled', 'pickup_in_progress', 'picked_up', 'received', 'queue_washing', 'washing', 'drying', 'queue_ironing', 'ironing', 'quality_check', 'packing', 'ready', 'delivery_scheduled', 'delivery_in_progress', 'delivered', 'completed', 'cancelled');
    END IF;
END
$$;

-- Create order_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'order_type') THEN
        CREATE TYPE order_type AS ENUM ('kiloan', 'satuan', 'dry_clean', 'express', 'same_day', 'specialty');
    END IF;
END
$$;

-- Create fulfillment_method enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'fulfillment_method') THEN
        CREATE TYPE fulfillment_method AS ENUM ('pickup_delivery', 'pickup_only', 'delivery_only', 'drop_off');
    END IF;
END
$$;

-- Create payment_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'payment_status') THEN
        CREATE TYPE payment_status AS ENUM ('pending', 'awaiting_payment', 'paid', 'partially_paid', 'refunded', 'failed');
    END IF;
END
$$;

-- Create cancellation_reason enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'cancellation_reason') THEN
        CREATE TYPE cancellation_reason AS ENUM ('customer_request', 'provider_unavailable', 'no_pickup_response', 'no_delivery_response', 'payment_failed', 'item_issue', 'force_majeure', 'other');
    END IF;
END
$$;

-- Create delivery_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'delivery_status') THEN
        CREATE TYPE delivery_status AS ENUM ('pending', 'scheduled', 'assigned', 'preparing', 'dispatched', 'en_route', 'arrived', 'delivering', 'delivered', 'failed', 'returned', 'rescheduled', 'cancelled');
    END IF;
END
$$;

-- Create delivery_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'delivery_type') THEN
        CREATE TYPE delivery_type AS ENUM ('scheduled', 'express', 'same_day', 'self_pickup');
    END IF;
END
$$;

-- Create item_condition enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'item_condition') THEN
        CREATE TYPE item_condition AS ENUM ('good', 'stained', 'damaged', 'worn');
    END IF;
END
$$;

-- Create item_processing_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'item_processing_status') THEN
        CREATE TYPE item_processing_status AS ENUM ('pending', 'washing', 'drying', 'ironing', 'folding', 'quality_check', 'ready', 'delivered', 'problem');
    END IF;
END
$$;

-- Create unit_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'unit_type') THEN
        CREATE TYPE unit_type AS ENUM ('per_kg', 'per_item', 'per_piece', 'flat_rate', 'tiered', 'per_set', 'per_pair', 'per_sqm', 'other');
    END IF;
END
$$;

-- Create pickup_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'pickup_status') THEN
        CREATE TYPE pickup_status AS ENUM ('scheduled', 'assigned', 'en_route', 'arrived', 'in_progress', 'completed', 'failed', 'rescheduled', 'cancelled');
    END IF;
END
$$;

-- Create pickup_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'pickup_type') THEN
        CREATE TYPE pickup_type AS ENUM ('scheduled', 'on_demand', 'drop_off');
    END IF;
END
$$;

-- Create timeline_entry_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'timeline_entry_type') THEN
        CREATE TYPE timeline_entry_type AS ENUM ('status_change', 'note', 'assignment', 'location', 'communication', 'action', 'system');
    END IF;
END
$$;

