-- Migration: Create delivery_tiers table
-- Generated by backbone-schema

CREATE TABLE IF NOT EXISTS delivery_tiers (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    name_en TEXT,
    description TEXT,
    duration_hours INTEGER NOT NULL,
    duration_label TEXT NOT NULL,
    color TEXT,
    icon TEXT,
    is_urgent BOOLEAN NOT NULL DEFAULT FALSE,
    sort_order INTEGER NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    provider_id UUID,
    outlet_id UUID,
    source_id UUID,
    is_cloned BOOLEAN NOT NULL DEFAULT FALSE,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_delivery_tiers_code ON delivery_tiers (code) WHERE (metadata->>'deleted_at') IS NULL AND provider_id IS NULL AND outlet_id IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_delivery_tiers_provider_id_outlet_id_code ON delivery_tiers (provider_id, outlet_id, code);

CREATE INDEX IF NOT EXISTS idx_delivery_tiers_provider_id_outlet_id_is_active ON delivery_tiers (provider_id, outlet_id, is_active);

CREATE INDEX IF NOT EXISTS idx_delivery_tiers_outlet_id_is_active_sort_order ON delivery_tiers (outlet_id, is_active, sort_order);

CREATE INDEX IF NOT EXISTS idx_delivery_tiers_source_id_is_cloned ON delivery_tiers (source_id, is_cloned);

CREATE INDEX IF NOT EXISTS idx_delivery_tiers_is_active_sort_order ON delivery_tiers (is_active, sort_order);

CREATE INDEX IF NOT EXISTS idx_delivery_tiers_provider_id_is_active_sort_order ON delivery_tiers (provider_id, is_active, sort_order);

CREATE INDEX IF NOT EXISTS idx_delivery_tiers_is_default ON delivery_tiers (is_default);

CREATE INDEX IF NOT EXISTS idx_delivery_tiers_duration_hours ON delivery_tiers (duration_hours);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_delivery_tiers_metadata_gin ON delivery_tiers USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_delivery_tiers_metadata_deleted_at ON delivery_tiers ((metadata->>'deleted_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION delivery_tiers_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS delivery_tiers_insert_audit ON delivery_tiers;
CREATE TRIGGER delivery_tiers_insert_audit BEFORE INSERT ON delivery_tiers
    FOR EACH ROW EXECUTE FUNCTION delivery_tiers_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS delivery_tiers_update_audit ON delivery_tiers;
CREATE TRIGGER delivery_tiers_update_audit BEFORE UPDATE ON delivery_tiers
    FOR EACH ROW EXECUTE FUNCTION delivery_tiers_audit_timestamp();

