-- Migration: Create orders table
-- Generated by backbone-schema

CREATE TABLE IF NOT EXISTS orders (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    order_number TEXT NOT NULL,
    customer_id UUID NOT NULL,
    provider_id UUID NOT NULL,
    outlet_id UUID,
    corporate_order_id UUID,
    delivery_tier_id UUID,
    order_type order_type NOT NULL DEFAULT 'kiloan',
    status order_status NOT NULL DEFAULT 'pending',
    fulfillment_method fulfillment_method NOT NULL DEFAULT 'pickup_delivery',
    estimated_ready_at TIMESTAMPTZ,
    actual_ready_at TIMESTAMPTZ,
    currency TEXT NOT NULL DEFAULT 'IDR',
    subtotal NUMERIC NOT NULL,
    discount_amount NUMERIC NOT NULL DEFAULT 0,
    promo_id UUID,
    delivery_fee NUMERIC NOT NULL DEFAULT 0,
    pickup_fee NUMERIC NOT NULL DEFAULT 0,
    tax_amount NUMERIC NOT NULL DEFAULT 0,
    platform_fee NUMERIC NOT NULL DEFAULT 0,
    grand_total NUMERIC NOT NULL,
    payment_status payment_status NOT NULL DEFAULT 'pending',
    paid_amount NUMERIC NOT NULL DEFAULT 0,
    paid_at TIMESTAMPTZ,
    special_instructions TEXT,
    provider_notes TEXT,
    cancelled_at TIMESTAMPTZ,
    cancellation_reason cancellation_reason,
    cancellation_note TEXT,
    cancelled_by UUID,
    data JSONB NOT NULL DEFAULT '{"total_items":0,"total_weight_kg":null,"actual_weight_kg":null,"is_recurring":false,"is_overflow":false,"points_earned":0,"points_redeemed":0,"points_discount":0}'::jsonb,
    source TEXT,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_orders_order_number ON orders (order_number) WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_orders_customer_id_status ON orders (customer_id, status);

CREATE INDEX IF NOT EXISTS idx_orders_provider_id_status ON orders (provider_id, status);

CREATE INDEX IF NOT EXISTS idx_orders_provider_id_outlet_id_status ON orders (provider_id, outlet_id, status);

CREATE INDEX IF NOT EXISTS idx_orders_status_created_at ON orders (status, ((metadata->>'created_at')));

CREATE INDEX IF NOT EXISTS idx_orders_payment_status ON orders (payment_status);

CREATE INDEX IF NOT EXISTS idx_orders_delivery_tier_id ON orders (delivery_tier_id);

CREATE INDEX IF NOT EXISTS idx_orders_corporate_order_id ON orders (corporate_order_id) WHERE corporate_order_id IS NOT NULL;

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_orders_metadata_gin ON orders USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_orders_metadata_deleted_at ON orders ((metadata->>'deleted_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION orders_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS orders_insert_audit ON orders;
CREATE TRIGGER orders_insert_audit BEFORE INSERT ON orders
    FOR EACH ROW EXECUTE FUNCTION orders_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS orders_update_audit ON orders;
CREATE TRIGGER orders_update_audit BEFORE UPDATE ON orders
    FOR EACH ROW EXECUTE FUNCTION orders_audit_timestamp();

