-- Migration: Create order_deliveries table
-- Generated by backbone-schema

CREATE TABLE IF NOT EXISTS order_deliveries (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    order_id UUID NOT NULL,
    delivery_type delivery_type NOT NULL DEFAULT 'scheduled',
    scheduled_date DATE NOT NULL,
    scheduled_time_start TEXT,
    scheduled_time_end TEXT,
    time_slot TEXT,
    customer_requested_date DATE,
    customer_requested_time_start TEXT,
    customer_requested_time_end TEXT,
    address_id UUID,
    address_line TEXT NOT NULL,
    address_detail TEXT,
    landmark TEXT,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    contact_name TEXT NOT NULL,
    contact_phone TEXT NOT NULL,
    contact_phone_alt TEXT,
    agent_id UUID,
    agent_name TEXT,
    agent_phone TEXT,
    assigned_at TIMESTAMPTZ,
    status delivery_status NOT NULL DEFAULT 'pending',
    dispatched_at TIMESTAMPTZ,
    en_route_at TIMESTAMPTZ,
    arrived_at TIMESTAMPTZ,
    delivered_at TIMESTAMPTZ,
    item_count INTEGER NOT NULL DEFAULT 0,
    bag_count INTEGER NOT NULL DEFAULT 0,
    bag_numbers JSONB NOT NULL DEFAULT '[]'::jsonb,
    verification_method TEXT,
    verification_code TEXT,
    verified_at TIMESTAMPTZ,
    photos JSONB NOT NULL DEFAULT '[]'::jsonb,
    proof_photo_url TEXT,
    signature_url TEXT,
    signed_by TEXT,
    relation_to_customer TEXT,
    delivery_latitude DOUBLE PRECISION,
    delivery_longitude DOUBLE PRECISION,
    distance_from_address_meters INTEGER,
    delivery_fee NUMERIC NOT NULL DEFAULT 0,
    express_fee NUMERIC NOT NULL DEFAULT 0,
    total_fee NUMERIC NOT NULL DEFAULT 0,
    currency TEXT NOT NULL DEFAULT 'IDR',
    is_cod BOOLEAN NOT NULL DEFAULT FALSE,
    cod_amount NUMERIC,
    cod_collected BOOLEAN NOT NULL DEFAULT FALSE,
    cod_collected_at TIMESTAMPTZ,
    customer_notes TEXT,
    agent_notes TEXT,
    internal_notes TEXT,
    failure_reason TEXT,
    failure_code TEXT,
    attempt_count INTEGER NOT NULL DEFAULT 1,
    reschedule_count INTEGER NOT NULL DEFAULT 0,
    original_scheduled_date DATE,
    reschedule_reason TEXT,
    delivery_rating INTEGER,
    rating_comment TEXT,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_order_deliveries_order_id ON order_deliveries (order_id) WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_order_deliveries_agent_id_scheduled_date_status ON order_deliveries (agent_id, scheduled_date, status);

CREATE INDEX IF NOT EXISTS idx_order_deliveries_status_scheduled_date ON order_deliveries (status, scheduled_date);

CREATE INDEX IF NOT EXISTS idx_order_deliveries_scheduled_date_status ON order_deliveries (scheduled_date, status);

CREATE INDEX IF NOT EXISTS idx_order_deliveries_is_cod_cod_collected ON order_deliveries (is_cod, cod_collected);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_order_deliveries_metadata_gin ON order_deliveries USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_order_deliveries_metadata_deleted_at ON order_deliveries ((metadata->>'deleted_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION order_deliveries_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS order_deliveries_insert_audit ON order_deliveries;
CREATE TRIGGER order_deliveries_insert_audit BEFORE INSERT ON order_deliveries
    FOR EACH ROW EXECUTE FUNCTION order_deliveries_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS order_deliveries_update_audit ON order_deliveries;
CREATE TRIGGER order_deliveries_update_audit BEFORE UPDATE ON order_deliveries
    FOR EACH ROW EXECUTE FUNCTION order_deliveries_audit_timestamp();

