-- Migration: Create order_items table
-- Generated by backbone-schema

CREATE TABLE IF NOT EXISTS order_items (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    order_id UUID NOT NULL,
    service_id UUID,
    item_name TEXT,
    quantity INTEGER NOT NULL DEFAULT 1,
    unit_type unit_type NOT NULL DEFAULT 'per_kg',
    unit_price NUMERIC NOT NULL,
    subtotal NUMERIC NOT NULL,
    discount NUMERIC NOT NULL DEFAULT 0,
    addon_total NUMERIC NOT NULL DEFAULT 0,
    total NUMERIC NOT NULL,
    currency TEXT NOT NULL DEFAULT 'IDR',
    addons JSONB NOT NULL DEFAULT '[]'::jsonb,
    condition_on_receipt item_condition NOT NULL DEFAULT 'good',
    condition_notes TEXT,
    processing_status item_processing_status NOT NULL DEFAULT 'pending',
    special_instructions TEXT,
    processing_notes TEXT,
    delivery_tier_id UUID,
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_order_items_order_id_processing_status ON order_items (order_id, processing_status);

CREATE INDEX IF NOT EXISTS idx_order_items_order_id_service_id ON order_items (order_id, service_id);

CREATE INDEX IF NOT EXISTS idx_order_items_delivery_tier_id ON order_items (delivery_tier_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_order_items_metadata_gin ON order_items USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_order_items_metadata_deleted_at ON order_items ((metadata->>'deleted_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION order_items_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS order_items_insert_audit ON order_items;
CREATE TRIGGER order_items_insert_audit BEFORE INSERT ON order_items
    FOR EACH ROW EXECUTE FUNCTION order_items_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS order_items_update_audit ON order_items;
CREATE TRIGGER order_items_update_audit BEFORE UPDATE ON order_items
    FOR EACH ROW EXECUTE FUNCTION order_items_audit_timestamp();

