-- Migration: Create order_pickups table
-- Generated by backbone-schema

CREATE TABLE IF NOT EXISTS order_pickups (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    order_id UUID NOT NULL,
    pickup_type pickup_type NOT NULL DEFAULT 'scheduled',
    scheduled_date DATE NOT NULL,
    scheduled_time_start TEXT,
    scheduled_time_end TEXT,
    time_slot TEXT,
    customer_requested_date DATE,
    customer_requested_time_start TEXT,
    customer_requested_time_end TEXT,
    address_id UUID,
    address_line TEXT NOT NULL,
    address_detail TEXT,
    landmark TEXT,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    contact_name TEXT NOT NULL,
    contact_phone TEXT NOT NULL,
    contact_phone_alt TEXT,
    agent_id UUID,
    agent_name TEXT,
    agent_phone TEXT,
    assigned_at TIMESTAMPTZ,
    status pickup_status NOT NULL DEFAULT 'scheduled',
    en_route_at TIMESTAMPTZ,
    arrived_at TIMESTAMPTZ,
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    estimated_weight_kg NUMERIC,
    actual_weight_kg NUMERIC,
    estimated_items INTEGER,
    actual_items INTEGER,
    bag_count INTEGER NOT NULL DEFAULT 0,
    bag_numbers JSONB NOT NULL DEFAULT '[]'::jsonb,
    photos JSONB NOT NULL DEFAULT '[]'::jsonb,
    signature_url TEXT,
    signed_by TEXT,
    pickup_latitude DOUBLE PRECISION,
    pickup_longitude DOUBLE PRECISION,
    distance_from_address_meters INTEGER,
    customer_notes TEXT,
    agent_notes TEXT,
    internal_notes TEXT,
    failure_reason TEXT,
    failure_code TEXT,
    reschedule_count INTEGER NOT NULL DEFAULT 0,
    original_scheduled_date DATE,
    reschedule_reason TEXT,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_order_pickups_order_id ON order_pickups (order_id) WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_order_pickups_agent_id_scheduled_date_status ON order_pickups (agent_id, scheduled_date, status);

CREATE INDEX IF NOT EXISTS idx_order_pickups_status_scheduled_date ON order_pickups (status, scheduled_date);

CREATE INDEX IF NOT EXISTS idx_order_pickups_scheduled_date_status ON order_pickups (scheduled_date, status);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_order_pickups_metadata_gin ON order_pickups USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_order_pickups_metadata_deleted_at ON order_pickups ((metadata->>'deleted_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION order_pickups_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS order_pickups_insert_audit ON order_pickups;
CREATE TRIGGER order_pickups_insert_audit BEFORE INSERT ON order_pickups
    FOR EACH ROW EXECUTE FUNCTION order_pickups_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS order_pickups_update_audit ON order_pickups;
CREATE TRIGGER order_pickups_update_audit BEFORE UPDATE ON order_pickups
    FOR EACH ROW EXECUTE FUNCTION order_pickups_audit_timestamp();

