-- Migration: Create order_status_timelines table
-- Generated by backbone-schema

CREATE TABLE IF NOT EXISTS order_status_timelines (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    order_id UUID NOT NULL,
    entry_type timeline_entry_type NOT NULL DEFAULT 'status_change',
    from_status TEXT,
    to_status TEXT,
    occurred_at TIMESTAMPTZ NOT NULL,
    actor_type TEXT,
    actor_id UUID,
    actor_name TEXT,
    actor_role TEXT,
    title TEXT NOT NULL,
    description TEXT,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    location_name TEXT,
    is_customer_visible BOOLEAN NOT NULL DEFAULT TRUE,
    is_provider_visible BOOLEAN NOT NULL DEFAULT TRUE,
    is_agent_visible BOOLEAN NOT NULL DEFAULT TRUE,
    attachments JSONB NOT NULL DEFAULT '[]'::jsonb,
    duration_minutes INTEGER,
    channel TEXT,
    device_info JSONB NOT NULL DEFAULT '{}'::jsonb,
    ip_address TEXT,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_order_status_timelines_order_id_occurred_at ON order_status_timelines (order_id, occurred_at);

CREATE INDEX IF NOT EXISTS idx_order_status_timelines_order_id_entry_type ON order_status_timelines (order_id, entry_type);

CREATE INDEX IF NOT EXISTS idx_order_status_timelines_order_id_to_status ON order_status_timelines (order_id, to_status);

CREATE INDEX IF NOT EXISTS idx_order_status_timelines_actor_id_occurred_at ON order_status_timelines (actor_id, occurred_at);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_order_status_timelines_metadata_gin ON order_status_timelines USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_order_status_timelines_metadata_deleted_at ON order_status_timelines ((metadata->>'deleted_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION order_status_timelines_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS order_status_timelines_insert_audit ON order_status_timelines;
CREATE TRIGGER order_status_timelines_insert_audit BEFORE INSERT ON order_status_timelines
    FOR EACH ROW EXECUTE FUNCTION order_status_timelines_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS order_status_timelines_update_audit ON order_status_timelines;
CREATE TRIGGER order_status_timelines_update_audit BEFORE UPDATE ON order_status_timelines
    FOR EACH ROW EXECUTE FUNCTION order_status_timelines_audit_timestamp();

