-- Foreign key constraints for orders module
-- Generated by backbone-schema

ALTER TABLE orders ADD CONSTRAINT fk_orders_delivery_tier_id FOREIGN KEY (delivery_tier_id) REFERENCES delivery_tiers (id) ON DELETE SET NULL;

ALTER TABLE order_deliveries ADD CONSTRAINT fk_order_deliveries_order_id FOREIGN KEY (order_id) REFERENCES orders (id);

ALTER TABLE order_items ADD CONSTRAINT fk_order_items_order_id FOREIGN KEY (order_id) REFERENCES orders (id);
ALTER TABLE order_items ADD CONSTRAINT fk_order_items_delivery_tier_id FOREIGN KEY (delivery_tier_id) REFERENCES delivery_tiers (id);

ALTER TABLE order_pickups ADD CONSTRAINT fk_order_pickups_order_id FOREIGN KEY (order_id) REFERENCES orders (id);

ALTER TABLE order_status_timelines ADD CONSTRAINT fk_order_status_timelines_order_id FOREIGN KEY (order_id) REFERENCES orders (id);
ALTER TABLE order_status_timelines ADD CONSTRAINT fk_order_status_timelines_actor_id FOREIGN KEY (actor_id) REFERENCES sapiens.users (id);

