-- Audit Triggers Migration for orders module
-- Generated by backbone-schema
--
-- This migration adds automatic timestamp management triggers
-- to all tables with audit metadata fields.
--
-- Triggers automatically set:
--   - metadata->'created_at' on INSERT
--   - metadata->'updated_at' on INSERT and UPDATE

-- ==============================================================================
-- Table: DeliveryTier (delivery_tiers)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION delivery_tiers_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS delivery_tiers_insert_audit ON delivery_tiers;
CREATE TRIGGER delivery_tiers_insert_audit BEFORE INSERT ON delivery_tiers
    FOR EACH ROW EXECUTE FUNCTION delivery_tiers_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS delivery_tiers_update_audit ON delivery_tiers;
CREATE TRIGGER delivery_tiers_update_audit BEFORE UPDATE ON delivery_tiers
    FOR EACH ROW EXECUTE FUNCTION delivery_tiers_audit_timestamp();

-- ==============================================================================
-- Table: Order (orders)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION orders_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS orders_insert_audit ON orders;
CREATE TRIGGER orders_insert_audit BEFORE INSERT ON orders
    FOR EACH ROW EXECUTE FUNCTION orders_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS orders_update_audit ON orders;
CREATE TRIGGER orders_update_audit BEFORE UPDATE ON orders
    FOR EACH ROW EXECUTE FUNCTION orders_audit_timestamp();

-- ==============================================================================
-- Table: OrderDelivery (order_deliveries)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION order_deliveries_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS order_deliveries_insert_audit ON order_deliveries;
CREATE TRIGGER order_deliveries_insert_audit BEFORE INSERT ON order_deliveries
    FOR EACH ROW EXECUTE FUNCTION order_deliveries_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS order_deliveries_update_audit ON order_deliveries;
CREATE TRIGGER order_deliveries_update_audit BEFORE UPDATE ON order_deliveries
    FOR EACH ROW EXECUTE FUNCTION order_deliveries_audit_timestamp();

-- ==============================================================================
-- Table: OrderItem (order_items)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION order_items_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS order_items_insert_audit ON order_items;
CREATE TRIGGER order_items_insert_audit BEFORE INSERT ON order_items
    FOR EACH ROW EXECUTE FUNCTION order_items_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS order_items_update_audit ON order_items;
CREATE TRIGGER order_items_update_audit BEFORE UPDATE ON order_items
    FOR EACH ROW EXECUTE FUNCTION order_items_audit_timestamp();

-- ==============================================================================
-- Table: OrderPickup (order_pickups)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION order_pickups_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS order_pickups_insert_audit ON order_pickups;
CREATE TRIGGER order_pickups_insert_audit BEFORE INSERT ON order_pickups
    FOR EACH ROW EXECUTE FUNCTION order_pickups_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS order_pickups_update_audit ON order_pickups;
CREATE TRIGGER order_pickups_update_audit BEFORE UPDATE ON order_pickups
    FOR EACH ROW EXECUTE FUNCTION order_pickups_audit_timestamp();

-- ==============================================================================
-- Table: OrderStatusTimeline (order_status_timelines)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION order_status_timelines_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS order_status_timelines_insert_audit ON order_status_timelines;
CREATE TRIGGER order_status_timelines_insert_audit BEFORE INSERT ON order_status_timelines
    FOR EACH ROW EXECUTE FUNCTION order_status_timelines_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS order_status_timelines_update_audit ON order_status_timelines;
CREATE TRIGGER order_status_timelines_update_audit BEFORE UPDATE ON order_status_timelines
    FOR EACH ROW EXECUTE FUNCTION order_status_timelines_audit_timestamp();

