-- Down migration for orders module
-- Generated by backbone-schema


DROP TABLE IF EXISTS order_status_timelines CASCADE;
DROP TABLE IF EXISTS order_pickups CASCADE;
DROP TABLE IF EXISTS order_items CASCADE;
DROP TABLE IF EXISTS order_deliveries CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS delivery_tiers CASCADE;

DROP TYPE IF EXISTS order_status CASCADE;
DROP TYPE IF EXISTS order_type CASCADE;
DROP TYPE IF EXISTS fulfillment_method CASCADE;
DROP TYPE IF EXISTS payment_status CASCADE;
DROP TYPE IF EXISTS cancellation_reason CASCADE;
DROP TYPE IF EXISTS delivery_status CASCADE;
DROP TYPE IF EXISTS delivery_type CASCADE;
DROP TYPE IF EXISTS item_condition CASCADE;
DROP TYPE IF EXISTS item_processing_status CASCADE;
DROP TYPE IF EXISTS unit_type CASCADE;
DROP TYPE IF EXISTS pickup_status CASCADE;
DROP TYPE IF EXISTS pickup_type CASCADE;
DROP TYPE IF EXISTS timeline_entry_type CASCADE;
