//! Event handler trait for DeliveryTier events
//!
//! Generated by backbone-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::DeliveryTierEvent;

/// Event handler for DeliveryTier events.
/// Implement this trait to react to DeliveryTier lifecycle events.
pub trait DeliveryTierEventHandler: EventHandler<DeliveryTierEvent> {}
