//! Domain events for DeliveryTier entity
//!
//! Generated by backbone-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::DeliveryTier;

/// Domain events for DeliveryTier — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<DeliveryTier>)` variant.
pub type DeliveryTierEvent = CrudEvent<DeliveryTier>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for DeliveryTier events.
pub type DeliveryTierEventPublisher = Arc<dyn CrudEventPublisher<DeliveryTier> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopDeliveryTierEventPublisher = NoOpCrudEventPublisher<DeliveryTier>;
