//! Domain events for OrderPickup entity
//!
//! Generated by backbone-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::OrderPickup;

/// Domain events for OrderPickup — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<OrderPickup>)` variant.
pub type OrderPickupEvent = CrudEvent<OrderPickup>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for OrderPickup events.
pub type OrderPickupEventPublisher = Arc<dyn CrudEventPublisher<OrderPickup> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopOrderPickupEventPublisher = NoOpCrudEventPublisher<OrderPickup>;
