//! Event handler trait for OrderStatusTimeline events
//!
//! Generated by backbone-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::OrderStatusTimelineEvent;

/// Event handler for OrderStatusTimeline events.
/// Implement this trait to react to OrderStatusTimeline lifecycle events.
pub trait OrderStatusTimelineEventHandler: EventHandler<OrderStatusTimelineEvent> {}
