//! Event handler trait for OrderDelivery events
//!
//! Generated by backbone-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::OrderDeliveryEvent;

/// Event handler for OrderDelivery events.
/// Implement this trait to react to OrderDelivery lifecycle events.
pub trait OrderDeliveryEventHandler: EventHandler<OrderDeliveryEvent> {}
