//! Domain events for Order entity
//!
//! Generated by backbone-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::Order;

/// Domain events for Order — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<Order>)` variant.
pub type OrderEvent = CrudEvent<Order>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for Order events.
pub type OrderEventPublisher = Arc<dyn CrudEventPublisher<Order> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopOrderEventPublisher = NoOpCrudEventPublisher<Order>;
