//! Domain events for OrderStatusTimeline entity
//!
//! Generated by backbone-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::OrderStatusTimeline;

/// Domain events for OrderStatusTimeline — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<OrderStatusTimeline>)` variant.
pub type OrderStatusTimelineEvent = CrudEvent<OrderStatusTimeline>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for OrderStatusTimeline events.
pub type OrderStatusTimelineEventPublisher = Arc<dyn CrudEventPublisher<OrderStatusTimeline> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopOrderStatusTimelineEventPublisher = NoOpCrudEventPublisher<OrderStatusTimeline>;
