//! Event handler trait for OrderPickup events
//!
//! Generated by backbone-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::OrderPickupEvent;

/// Event handler for OrderPickup events.
/// Implement this trait to react to OrderPickup lifecycle events.
pub trait OrderPickupEventHandler: EventHandler<OrderPickupEvent> {}
