//! Event handler trait for Order events
//!
//! Generated by backbone-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::OrderEvent;

/// Event handler for Order events.
/// Implement this trait to react to Order lifecycle events.
pub trait OrderEventHandler: EventHandler<OrderEvent> {}
