//! Domain events for OrderDelivery entity
//!
//! Generated by backbone-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::OrderDelivery;

/// Domain events for OrderDelivery — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<OrderDelivery>)` variant.
pub type OrderDeliveryEvent = CrudEvent<OrderDelivery>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for OrderDelivery events.
pub type OrderDeliveryEventPublisher = Arc<dyn CrudEventPublisher<OrderDelivery> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopOrderDeliveryEventPublisher = NoOpCrudEventPublisher<OrderDelivery>;
