//! Event handler trait for OrderItem events
//!
//! Generated by backbone-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::OrderItemEvent;

/// Event handler for OrderItem events.
/// Implement this trait to react to OrderItem lifecycle events.
pub trait OrderItemEventHandler: EventHandler<OrderItemEvent> {}
