//! Domain events for OrderItem entity
//!
//! Generated by backbone-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::OrderItem;

/// Domain events for OrderItem — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<OrderItem>)` variant.
pub type OrderItemEvent = CrudEvent<OrderItem>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for OrderItem events.
pub type OrderItemEventPublisher = Arc<dyn CrudEventPublisher<OrderItem> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopOrderItemEventPublisher = NoOpCrudEventPublisher<OrderItem>;
