//! Event subscriber type aliases for Orders module
//!
//! Generated by backbone-schema. Do not edit manually.

use backbone_messaging::GenericEventSubscriber;

use crate::domain::event::DeliveryTierEvent;
use crate::domain::event::OrderEvent;
use crate::domain::event::OrderDeliveryEvent;
use crate::domain::event::OrderItemEvent;
use crate::domain::event::OrderPickupEvent;
use crate::domain::event::OrderStatusTimelineEvent;

/// Subscriber for DeliveryTier events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type DeliveryTierEventSubscriber = GenericEventSubscriber<DeliveryTierEvent>;

/// Subscriber for Order events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type OrderEventSubscriber = GenericEventSubscriber<OrderEvent>;

/// Subscriber for OrderDelivery events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type OrderDeliveryEventSubscriber = GenericEventSubscriber<OrderDeliveryEvent>;

/// Subscriber for OrderItem events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type OrderItemEventSubscriber = GenericEventSubscriber<OrderItemEvent>;

/// Subscriber for OrderPickup events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type OrderPickupEventSubscriber = GenericEventSubscriber<OrderPickupEvent>;

/// Subscriber for OrderStatusTimeline events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type OrderStatusTimelineEventSubscriber = GenericEventSubscriber<OrderStatusTimelineEvent>;

// <<< CUSTOM
// END CUSTOM
