//! Subscription registry for Orders module
//!
//! Generated by backbone-schema. Do not edit manually.

use backbone_messaging::SubscriberRegistry;

/// Registry of all event subscriptions for the Orders module.
///
/// Register your subscribers with the event bus on startup:
///
/// ```rust,ignore
/// let registry = SubscriptionRegistry::default();
/// registry.register_all(&event_bus).await?;
/// ```
pub type SubscriptionRegistry = SubscriberRegistry;

// <<< CUSTOM
// END CUSTOM
