//! DeliveryTier seeder
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Seeds initial DeliveryTier data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// DELIVERYTIER SEEDER
// ============================================================================

/// Seeder for delivery_tier
pub struct SeedDeliveryTierSeeder;

impl SeedDeliveryTierSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedDeliveryTierSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedDeliveryTierSeeder {
    fn name(&self) -> &'static str {
        "SeedDeliveryTierSeeder"
    }

    fn order(&self) -> i32 {
        1
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if delivery_tiers table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM delivery_tiers")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/delivery_tier_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM delivery_tiers")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

