//! Database seeders for the orders module
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! This module provides seed data for initial database setup.
//! Seeders can be run via the seeder binary or CLI.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

mod delivery_tier_seeder;
mod order_seeder;
mod order_delivery_seeder;
mod order_item_seeder;
mod order_pickup_seeder;
mod order_status_timeline_seeder;

pub use delivery_tier_seeder::SeedDeliveryTierSeeder;
pub use order_seeder::SeedOrderSeeder;
pub use order_delivery_seeder::SeedOrderDeliverySeeder;
pub use order_item_seeder::SeedOrderItemSeeder;
pub use order_pickup_seeder::SeedOrderPickupSeeder;
pub use order_status_timeline_seeder::SeedOrderStatusTimelineSeeder;

// ============================================================================
// SEEDER TRAIT
// ============================================================================

/// Trait for database seeders
#[async_trait]
pub trait Seeder {
    /// Get the name of this seeder
    fn name(&self) -> &'static str;

    /// Get the order in which this seeder should run
    fn order(&self) -> i32;

    /// Check if this seeder should run (e.g., check if data already exists)
    async fn should_run(&self, pool: &PgPool) -> Result<bool>;

    /// Run the seeder
    async fn run(&self, pool: &PgPool) -> Result<()>;

    /// Rollback the seeder (optional)
    async fn rollback(&self, _pool: &PgPool) -> Result<()> {
        Ok(())
    }
}

// ============================================================================
// SEEDER TYPE
// ============================================================================

/// Type of seeder
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SeederType {
    /// Reference data (required for application to function)
    Reference,
    /// Initial production data
    Production,
    /// Development/testing data
    Development,
    /// Test data (for automated tests)
    Test,
}

// ============================================================================
// CUSTOM SEEDERS
// ============================================================================

// <<< CUSTOM SEEDERS START >>>
// Add custom seeders here
// <<< CUSTOM SEEDERS END >>>

