//! OrderStatusTimeline seeder
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Seeds initial OrderStatusTimeline data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// ORDERSTATUSTIMELINE SEEDER
// ============================================================================

/// Seeder for order_status_timeline
pub struct SeedOrderStatusTimelineSeeder;

impl SeedOrderStatusTimelineSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedOrderStatusTimelineSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedOrderStatusTimelineSeeder {
    fn name(&self) -> &'static str {
        "SeedOrderStatusTimelineSeeder"
    }

    fn order(&self) -> i32 {
        6
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if order_status_timelines table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM order_status_timelines")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/order_status_timeline_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM order_status_timelines")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

