//! OrderItem seeder
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Seeds initial OrderItem data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// ORDERITEM SEEDER
// ============================================================================

/// Seeder for order_item
pub struct SeedOrderItemSeeder;

impl SeedOrderItemSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedOrderItemSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedOrderItemSeeder {
    fn name(&self) -> &'static str {
        "SeedOrderItemSeeder"
    }

    fn order(&self) -> i32 {
        4
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if order_items table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM order_items")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/order_item_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM order_items")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

