//! Repository trait for DeliveryTier aggregate
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the DeliveryTier aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::DeliveryTier;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct DeliveryTierPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl DeliveryTierPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct DeliveryTierPaginatedResult {
    pub data: Vec<DeliveryTier>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct DeliveryTierFilter {
    pub code: Option<String>,
    pub name: Option<String>,
    pub name_en: Option<String>,
    pub description: Option<String>,
    pub duration_label: Option<String>,
    pub color: Option<String>,
    pub icon: Option<String>,
    pub is_urgent: Option<bool>,
    pub is_active: Option<bool>,
    pub is_default: Option<bool>,
    pub provider_id: Option<Uuid>,
    pub outlet_id: Option<Uuid>,
    pub source_id: Option<Uuid>,
    pub is_cloned: Option<bool>,
}

impl DeliveryTierFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.code.is_some() || self.name.is_some() || self.name_en.is_some() || self.description.is_some() || self.duration_label.is_some() || self.color.is_some() || self.icon.is_some() || self.is_urgent.is_some() || self.is_active.is_some() || self.is_default.is_some() || self.provider_id.is_some() || self.outlet_id.is_some() || self.source_id.is_some() || self.is_cloned.is_some()
    }
}

/// Repository trait for DeliveryTier aggregate
///
/// This trait defines the persistence contract for DeliveryTier entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait DeliveryTierRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new delivery_tier entity
    async fn save(&self, entity: &DeliveryTier) -> Result<DeliveryTier>;

    /// Find delivery_tier by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<DeliveryTier>>;

    /// Find all delivery_tier entities
    async fn find_all(&self) -> Result<Vec<DeliveryTier>>;

    /// Update delivery_tier by ID
    async fn update(&self, id: &str, entity: &DeliveryTier) -> Result<Option<DeliveryTier>>;

    /// Delete delivery_tier by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List delivery_tier with pagination
    async fn list(&self, params: DeliveryTierPaginationParams) -> Result<DeliveryTierPaginatedResult>;

    /// List delivery_tier with pagination and filters
    async fn list_with_filters(&self, params: DeliveryTierPaginationParams, filters: DeliveryTierFilter) -> Result<DeliveryTierPaginatedResult>;

    /// Count all delivery_tier entities
    async fn count(&self) -> Result<u64>;

    /// Count delivery_tier entities matching filters
    async fn count_with_filters(&self, filters: DeliveryTierFilter) -> Result<u64>;

    /// Check if delivery_tier exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete delivery_tier by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted delivery_tier by ID
    async fn restore(&self, id: &str) -> Result<Option<DeliveryTier>>;

    /// List soft-deleted delivery_tier entities
    async fn list_deleted(&self, params: DeliveryTierPaginationParams) -> Result<DeliveryTierPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Query by Unique Fields
    // =========================================================================

    /// Find delivery_tier by code
    async fn find_by_code(&self, code: &str) -> Result<Option<DeliveryTier>>;

    // =========================================================================
    // Existence Checks by Unique Fields
    // =========================================================================

    /// Check if delivery_tier exists by code
    async fn exists_by_code(&self, code: &str) -> Result<bool>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save delivery_tier entities
    async fn bulk_save(&self, entities: &[DeliveryTier]) -> Result<Vec<DeliveryTier>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
