//! Repository trait for Order aggregate
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the Order aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{Order, CancellationReason, FulfillmentMethod, OrderStatus, OrderType, PaymentStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct OrderPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl OrderPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct OrderPaginatedResult {
    pub data: Vec<Order>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct OrderFilter {
    pub order_number: Option<String>,
    pub customer_id: Option<Uuid>,
    pub provider_id: Option<Uuid>,
    pub outlet_id: Option<Uuid>,
    pub corporate_order_id: Option<Uuid>,
    pub delivery_tier_id: Option<Uuid>,
    pub order_type: Option<OrderType>,
    pub status: Option<OrderStatus>,
    pub fulfillment_method: Option<FulfillmentMethod>,
    pub currency: Option<String>,
    pub promo_id: Option<Uuid>,
    pub payment_status: Option<PaymentStatus>,
    pub special_instructions: Option<String>,
    pub provider_notes: Option<String>,
    pub cancellation_reason: Option<CancellationReason>,
    pub cancellation_note: Option<String>,
    pub cancelled_by: Option<Uuid>,
    pub source: Option<String>,
}

impl OrderFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.order_number.is_some() || self.customer_id.is_some() || self.provider_id.is_some() || self.outlet_id.is_some() || self.corporate_order_id.is_some() || self.delivery_tier_id.is_some() || self.order_type.is_some() || self.status.is_some() || self.fulfillment_method.is_some() || self.currency.is_some() || self.promo_id.is_some() || self.payment_status.is_some() || self.special_instructions.is_some() || self.provider_notes.is_some() || self.cancellation_reason.is_some() || self.cancellation_note.is_some() || self.cancelled_by.is_some() || self.source.is_some()
    }
}

/// Repository trait for Order aggregate
///
/// This trait defines the persistence contract for Order entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait OrderRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new order entity
    async fn save(&self, entity: &Order) -> Result<Order>;

    /// Find order by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<Order>>;

    /// Find all order entities
    async fn find_all(&self) -> Result<Vec<Order>>;

    /// Update order by ID
    async fn update(&self, id: &str, entity: &Order) -> Result<Option<Order>>;

    /// Delete order by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List order with pagination
    async fn list(&self, params: OrderPaginationParams) -> Result<OrderPaginatedResult>;

    /// List order with pagination and filters
    async fn list_with_filters(&self, params: OrderPaginationParams, filters: OrderFilter) -> Result<OrderPaginatedResult>;

    /// Count all order entities
    async fn count(&self) -> Result<u64>;

    /// Count order entities matching filters
    async fn count_with_filters(&self, filters: OrderFilter) -> Result<u64>;

    /// Check if order exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete order by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted order by ID
    async fn restore(&self, id: &str) -> Result<Option<Order>>;

    /// List soft-deleted order entities
    async fn list_deleted(&self, params: OrderPaginationParams) -> Result<OrderPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Query by Unique Fields
    // =========================================================================

    /// Find order by order_number
    async fn find_by_order_number(&self, order_number: &str) -> Result<Option<Order>>;

    // =========================================================================
    // Existence Checks by Unique Fields
    // =========================================================================

    /// Check if order exists by order_number
    async fn exists_by_order_number(&self, order_number: &str) -> Result<bool>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save order entities
    async fn bulk_save(&self, entities: &[Order]) -> Result<Vec<Order>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
