//! Repository trait for OrderPickup aggregate
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the OrderPickup aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{OrderPickup, PickupStatus, PickupType};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct OrderPickupPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl OrderPickupPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct OrderPickupPaginatedResult {
    pub data: Vec<OrderPickup>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct OrderPickupFilter {
    pub order_id: Option<Uuid>,
    pub pickup_type: Option<PickupType>,
    pub scheduled_time_start: Option<String>,
    pub scheduled_time_end: Option<String>,
    pub time_slot: Option<String>,
    pub customer_requested_time_start: Option<String>,
    pub customer_requested_time_end: Option<String>,
    pub address_id: Option<Uuid>,
    pub address_line: Option<String>,
    pub address_detail: Option<String>,
    pub landmark: Option<String>,
    pub contact_name: Option<String>,
    pub contact_phone: Option<String>,
    pub contact_phone_alt: Option<String>,
    pub agent_id: Option<Uuid>,
    pub agent_name: Option<String>,
    pub agent_phone: Option<String>,
    pub status: Option<PickupStatus>,
    pub signature_url: Option<String>,
    pub signed_by: Option<String>,
    pub customer_notes: Option<String>,
    pub agent_notes: Option<String>,
    pub internal_notes: Option<String>,
    pub failure_reason: Option<String>,
    pub failure_code: Option<String>,
    pub reschedule_reason: Option<String>,
}

impl OrderPickupFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.order_id.is_some() || self.pickup_type.is_some() || self.scheduled_time_start.is_some() || self.scheduled_time_end.is_some() || self.time_slot.is_some() || self.customer_requested_time_start.is_some() || self.customer_requested_time_end.is_some() || self.address_id.is_some() || self.address_line.is_some() || self.address_detail.is_some() || self.landmark.is_some() || self.contact_name.is_some() || self.contact_phone.is_some() || self.contact_phone_alt.is_some() || self.agent_id.is_some() || self.agent_name.is_some() || self.agent_phone.is_some() || self.status.is_some() || self.signature_url.is_some() || self.signed_by.is_some() || self.customer_notes.is_some() || self.agent_notes.is_some() || self.internal_notes.is_some() || self.failure_reason.is_some() || self.failure_code.is_some() || self.reschedule_reason.is_some()
    }
}

/// Repository trait for OrderPickup aggregate
///
/// This trait defines the persistence contract for OrderPickup entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait OrderPickupRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new order_pickup entity
    async fn save(&self, entity: &OrderPickup) -> Result<OrderPickup>;

    /// Find order_pickup by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<OrderPickup>>;

    /// Find all order_pickup entities
    async fn find_all(&self) -> Result<Vec<OrderPickup>>;

    /// Update order_pickup by ID
    async fn update(&self, id: &str, entity: &OrderPickup) -> Result<Option<OrderPickup>>;

    /// Delete order_pickup by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List order_pickup with pagination
    async fn list(&self, params: OrderPickupPaginationParams) -> Result<OrderPickupPaginatedResult>;

    /// List order_pickup with pagination and filters
    async fn list_with_filters(&self, params: OrderPickupPaginationParams, filters: OrderPickupFilter) -> Result<OrderPickupPaginatedResult>;

    /// Count all order_pickup entities
    async fn count(&self) -> Result<u64>;

    /// Count order_pickup entities matching filters
    async fn count_with_filters(&self, filters: OrderPickupFilter) -> Result<u64>;

    /// Check if order_pickup exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete order_pickup by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted order_pickup by ID
    async fn restore(&self, id: &str) -> Result<Option<OrderPickup>>;

    /// List soft-deleted order_pickup entities
    async fn list_deleted(&self, params: OrderPickupPaginationParams) -> Result<OrderPickupPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save order_pickup entities
    async fn bulk_save(&self, entities: &[OrderPickup]) -> Result<Vec<OrderPickup>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
