//! Repository trait for OrderDelivery aggregate
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the OrderDelivery aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{OrderDelivery, DeliveryStatus, DeliveryType};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct OrderDeliveryPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl OrderDeliveryPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct OrderDeliveryPaginatedResult {
    pub data: Vec<OrderDelivery>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct OrderDeliveryFilter {
    pub order_id: Option<Uuid>,
    pub delivery_type: Option<DeliveryType>,
    pub scheduled_time_start: Option<String>,
    pub scheduled_time_end: Option<String>,
    pub time_slot: Option<String>,
    pub customer_requested_time_start: Option<String>,
    pub customer_requested_time_end: Option<String>,
    pub address_id: Option<Uuid>,
    pub address_line: Option<String>,
    pub address_detail: Option<String>,
    pub landmark: Option<String>,
    pub contact_name: Option<String>,
    pub contact_phone: Option<String>,
    pub contact_phone_alt: Option<String>,
    pub agent_id: Option<Uuid>,
    pub agent_name: Option<String>,
    pub agent_phone: Option<String>,
    pub status: Option<DeliveryStatus>,
    pub verification_method: Option<String>,
    pub verification_code: Option<String>,
    pub proof_photo_url: Option<String>,
    pub signature_url: Option<String>,
    pub signed_by: Option<String>,
    pub relation_to_customer: Option<String>,
    pub currency: Option<String>,
    pub is_cod: Option<bool>,
    pub cod_collected: Option<bool>,
    pub customer_notes: Option<String>,
    pub agent_notes: Option<String>,
    pub internal_notes: Option<String>,
    pub failure_reason: Option<String>,
    pub failure_code: Option<String>,
    pub reschedule_reason: Option<String>,
    pub rating_comment: Option<String>,
}

impl OrderDeliveryFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.order_id.is_some() || self.delivery_type.is_some() || self.scheduled_time_start.is_some() || self.scheduled_time_end.is_some() || self.time_slot.is_some() || self.customer_requested_time_start.is_some() || self.customer_requested_time_end.is_some() || self.address_id.is_some() || self.address_line.is_some() || self.address_detail.is_some() || self.landmark.is_some() || self.contact_name.is_some() || self.contact_phone.is_some() || self.contact_phone_alt.is_some() || self.agent_id.is_some() || self.agent_name.is_some() || self.agent_phone.is_some() || self.status.is_some() || self.verification_method.is_some() || self.verification_code.is_some() || self.proof_photo_url.is_some() || self.signature_url.is_some() || self.signed_by.is_some() || self.relation_to_customer.is_some() || self.currency.is_some() || self.is_cod.is_some() || self.cod_collected.is_some() || self.customer_notes.is_some() || self.agent_notes.is_some() || self.internal_notes.is_some() || self.failure_reason.is_some() || self.failure_code.is_some() || self.reschedule_reason.is_some() || self.rating_comment.is_some()
    }
}

/// Repository trait for OrderDelivery aggregate
///
/// This trait defines the persistence contract for OrderDelivery entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait OrderDeliveryRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new order_delivery entity
    async fn save(&self, entity: &OrderDelivery) -> Result<OrderDelivery>;

    /// Find order_delivery by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<OrderDelivery>>;

    /// Find all order_delivery entities
    async fn find_all(&self) -> Result<Vec<OrderDelivery>>;

    /// Update order_delivery by ID
    async fn update(&self, id: &str, entity: &OrderDelivery) -> Result<Option<OrderDelivery>>;

    /// Delete order_delivery by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List order_delivery with pagination
    async fn list(&self, params: OrderDeliveryPaginationParams) -> Result<OrderDeliveryPaginatedResult>;

    /// List order_delivery with pagination and filters
    async fn list_with_filters(&self, params: OrderDeliveryPaginationParams, filters: OrderDeliveryFilter) -> Result<OrderDeliveryPaginatedResult>;

    /// Count all order_delivery entities
    async fn count(&self) -> Result<u64>;

    /// Count order_delivery entities matching filters
    async fn count_with_filters(&self, filters: OrderDeliveryFilter) -> Result<u64>;

    /// Check if order_delivery exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete order_delivery by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted order_delivery by ID
    async fn restore(&self, id: &str) -> Result<Option<OrderDelivery>>;

    /// List soft-deleted order_delivery entities
    async fn list_deleted(&self, params: OrderDeliveryPaginationParams) -> Result<OrderDeliveryPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save order_delivery entities
    async fn bulk_save(&self, entities: &[OrderDelivery]) -> Result<Vec<OrderDelivery>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
