//! Repository trait for OrderStatusTimeline aggregate
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the OrderStatusTimeline aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{OrderStatusTimeline, TimelineEntryType};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct OrderStatusTimelinePaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl OrderStatusTimelinePaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct OrderStatusTimelinePaginatedResult {
    pub data: Vec<OrderStatusTimeline>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct OrderStatusTimelineFilter {
    pub order_id: Option<Uuid>,
    pub entry_type: Option<TimelineEntryType>,
    pub from_status: Option<String>,
    pub to_status: Option<String>,
    pub actor_type: Option<String>,
    pub actor_id: Option<Uuid>,
    pub actor_name: Option<String>,
    pub actor_role: Option<String>,
    pub title: Option<String>,
    pub description: Option<String>,
    pub location_name: Option<String>,
    pub is_customer_visible: Option<bool>,
    pub is_provider_visible: Option<bool>,
    pub is_agent_visible: Option<bool>,
    pub channel: Option<String>,
    pub ip_address: Option<String>,
}

impl OrderStatusTimelineFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.order_id.is_some() || self.entry_type.is_some() || self.from_status.is_some() || self.to_status.is_some() || self.actor_type.is_some() || self.actor_id.is_some() || self.actor_name.is_some() || self.actor_role.is_some() || self.title.is_some() || self.description.is_some() || self.location_name.is_some() || self.is_customer_visible.is_some() || self.is_provider_visible.is_some() || self.is_agent_visible.is_some() || self.channel.is_some() || self.ip_address.is_some()
    }
}

/// Repository trait for OrderStatusTimeline aggregate
///
/// This trait defines the persistence contract for OrderStatusTimeline entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait OrderStatusTimelineRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new order_status_timeline entity
    async fn save(&self, entity: &OrderStatusTimeline) -> Result<OrderStatusTimeline>;

    /// Find order_status_timeline by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<OrderStatusTimeline>>;

    /// Find all order_status_timeline entities
    async fn find_all(&self) -> Result<Vec<OrderStatusTimeline>>;

    /// Update order_status_timeline by ID
    async fn update(&self, id: &str, entity: &OrderStatusTimeline) -> Result<Option<OrderStatusTimeline>>;

    /// Delete order_status_timeline by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List order_status_timeline with pagination
    async fn list(&self, params: OrderStatusTimelinePaginationParams) -> Result<OrderStatusTimelinePaginatedResult>;

    /// List order_status_timeline with pagination and filters
    async fn list_with_filters(&self, params: OrderStatusTimelinePaginationParams, filters: OrderStatusTimelineFilter) -> Result<OrderStatusTimelinePaginatedResult>;

    /// Count all order_status_timeline entities
    async fn count(&self) -> Result<u64>;

    /// Count order_status_timeline entities matching filters
    async fn count_with_filters(&self, filters: OrderStatusTimelineFilter) -> Result<u64>;

    /// Check if order_status_timeline exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete order_status_timeline by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted order_status_timeline by ID
    async fn restore(&self, id: &str) -> Result<Option<OrderStatusTimeline>>;

    /// List soft-deleted order_status_timeline entities
    async fn list_deleted(&self, params: OrderStatusTimelinePaginationParams) -> Result<OrderStatusTimelinePaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save order_status_timeline entities
    async fn bulk_save(&self, entities: &[OrderStatusTimeline]) -> Result<Vec<OrderStatusTimeline>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
