//! Repository trait for OrderItem aggregate
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the OrderItem aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{OrderItem, ItemCondition, ItemProcessingStatus, UnitType};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct OrderItemPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl OrderItemPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct OrderItemPaginatedResult {
    pub data: Vec<OrderItem>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct OrderItemFilter {
    pub order_id: Option<Uuid>,
    pub service_id: Option<Uuid>,
    pub item_name: Option<String>,
    pub unit_type: Option<UnitType>,
    pub currency: Option<String>,
    pub condition_on_receipt: Option<ItemCondition>,
    pub condition_notes: Option<String>,
    pub processing_status: Option<ItemProcessingStatus>,
    pub special_instructions: Option<String>,
    pub processing_notes: Option<String>,
    pub delivery_tier_id: Option<Uuid>,
}

impl OrderItemFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.order_id.is_some() || self.service_id.is_some() || self.item_name.is_some() || self.unit_type.is_some() || self.currency.is_some() || self.condition_on_receipt.is_some() || self.condition_notes.is_some() || self.processing_status.is_some() || self.special_instructions.is_some() || self.processing_notes.is_some() || self.delivery_tier_id.is_some()
    }
}

/// Repository trait for OrderItem aggregate
///
/// This trait defines the persistence contract for OrderItem entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait OrderItemRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new order_item entity
    async fn save(&self, entity: &OrderItem) -> Result<OrderItem>;

    /// Find order_item by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<OrderItem>>;

    /// Find all order_item entities
    async fn find_all(&self) -> Result<Vec<OrderItem>>;

    /// Update order_item by ID
    async fn update(&self, id: &str, entity: &OrderItem) -> Result<Option<OrderItem>>;

    /// Delete order_item by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List order_item with pagination
    async fn list(&self, params: OrderItemPaginationParams) -> Result<OrderItemPaginatedResult>;

    /// List order_item with pagination and filters
    async fn list_with_filters(&self, params: OrderItemPaginationParams, filters: OrderItemFilter) -> Result<OrderItemPaginatedResult>;

    /// Count all order_item entities
    async fn count(&self) -> Result<u64>;

    /// Count order_item entities matching filters
    async fn count_with_filters(&self, filters: OrderItemFilter) -> Result<u64>;

    /// Check if order_item exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete order_item by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted order_item by ID
    async fn restore(&self, id: &str) -> Result<Option<OrderItem>>;

    /// List soft-deleted order_item entities
    async fn list_deleted(&self, params: OrderItemPaginationParams) -> Result<OrderItemPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save order_item entities
    async fn bulk_save(&self, entities: &[OrderItem]) -> Result<Vec<OrderItem>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
