//! Repository for DeliveryTier entities
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<DeliveryTier, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::DeliveryTier;

/// Table name for DeliveryTier entities
pub const TABLE_NAME: &str = "delivery_tiers";

/// Repository for DeliveryTier entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct DeliveryTierRepository(
    backbone_orm::GenericCrudRepository<DeliveryTier, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for DeliveryTierRepository {
    type Target = backbone_orm::GenericCrudRepository<DeliveryTier, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl DeliveryTierRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

impl DeliveryTierRepository {
    /// Find delivery_tier by code (excludes soft-deleted)
    pub async fn find_by_code(&self, code: &str) -> Result<Option<DeliveryTier>> {
        self.find_by_text_field("code", code).await
    }

    /// Check if delivery_tier exists by code (excludes soft-deleted)
    pub async fn exists_by_code(&self, code: &str) -> Result<bool> {
        self.exists_by_text_field("code", code).await
    }

}

backbone_core::impl_crud_repository!(DeliveryTierRepository, DeliveryTier, soft_delete);
