//! Repository for OrderStatusTimeline entities
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<OrderStatusTimeline, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::OrderStatusTimeline;

/// Table name for OrderStatusTimeline entities
pub const TABLE_NAME: &str = "order_status_timelines";

/// Repository for OrderStatusTimeline entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct OrderStatusTimelineRepository(
    backbone_orm::GenericCrudRepository<OrderStatusTimeline, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for OrderStatusTimelineRepository {
    type Target = backbone_orm::GenericCrudRepository<OrderStatusTimeline, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl OrderStatusTimelineRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(OrderStatusTimelineRepository, OrderStatusTimeline, soft_delete);
