//! Repository for OrderItem entities
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<OrderItem, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::OrderItem;

/// Table name for OrderItem entities
pub const TABLE_NAME: &str = "order_items";

/// Repository for OrderItem entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct OrderItemRepository(
    backbone_orm::GenericCrudRepository<OrderItem, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for OrderItemRepository {
    type Target = backbone_orm::GenericCrudRepository<OrderItem, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl OrderItemRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(OrderItemRepository, OrderItem, soft_delete);
