//! Repository for Order entities
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<Order, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::Order;

/// Table name for Order entities
pub const TABLE_NAME: &str = "orders";

/// Repository for Order entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct OrderRepository(
    backbone_orm::GenericCrudRepository<Order, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for OrderRepository {
    type Target = backbone_orm::GenericCrudRepository<Order, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl OrderRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

impl OrderRepository {
    /// Find order by order_number (excludes soft-deleted)
    pub async fn find_by_order_number(&self, order_number: &str) -> Result<Option<Order>> {
        self.find_by_text_field("order_number", order_number).await
    }

    /// Check if order exists by order_number (excludes soft-deleted)
    pub async fn exists_by_order_number(&self, order_number: &str) -> Result<bool> {
        self.exists_by_text_field("order_number", order_number).await
    }

}

backbone_core::impl_crud_repository!(OrderRepository, Order, soft_delete);
