//! Validator for OrderStatusTimeline entity
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<OrderStatusTimeline>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative, OptionalNotBlank, RequiredString, RequiredUuid};
use crate::domain::entity::OrderStatusTimeline;

/// Validator type alias for OrderStatusTimeline entities.
pub type OrderStatusTimelineValidator = EntityValidator<OrderStatusTimeline>;

/// Build a validator for OrderStatusTimeline with all schema-defined field rules.
pub fn order_status_timeline_validator() -> OrderStatusTimelineValidator {
    EntityValidator::new()
        .rule(RequiredUuid::new("order_id", |e: &OrderStatusTimeline| &e.order_id))
        .rule(OptionalNotBlank::new("from_status", |e: &OrderStatusTimeline| e.from_status.as_deref()))
        .rule(OptionalNotBlank::new("to_status", |e: &OrderStatusTimeline| e.to_status.as_deref()))
        .rule(OptionalNotBlank::new("actor_type", |e: &OrderStatusTimeline| e.actor_type.as_deref()))
        .rule(OptionalNotBlank::new("actor_name", |e: &OrderStatusTimeline| e.actor_name.as_deref()))
        .rule(OptionalNotBlank::new("actor_role", |e: &OrderStatusTimeline| e.actor_role.as_deref()))
        .rule(RequiredString::new("title", |e: &OrderStatusTimeline| &e.title))
        .rule(OptionalNotBlank::new("description", |e: &OrderStatusTimeline| e.description.as_deref()))
        .rule(OptionalNotBlank::new("location_name", |e: &OrderStatusTimeline| e.location_name.as_deref()))
        .rule(NonNegative::new("duration_minutes", |e: &OrderStatusTimeline| e.duration_minutes))
        .rule(OptionalNotBlank::new("channel", |e: &OrderStatusTimeline| e.channel.as_deref()))
        .rule(OptionalNotBlank::new("ip_address", |e: &OrderStatusTimeline| e.ip_address.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
