//! Validator for Order entity
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<Order>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative, OptionalNotBlank, RequiredString, RequiredUuid};
use crate::domain::entity::Order;

/// Validator type alias for Order entities.
pub type OrderValidator = EntityValidator<Order>;

/// Build a validator for Order with all schema-defined field rules.
pub fn order_validator() -> OrderValidator {
    EntityValidator::new()
        .rule(RequiredString::new("order_number", |e: &Order| &e.order_number))
        .rule(RequiredUuid::new("customer_id", |e: &Order| &e.customer_id))
        .rule(RequiredUuid::new("provider_id", |e: &Order| &e.provider_id))
        .rule(RequiredString::new("currency", |e: &Order| &e.currency))
        .rule(NonNegative::new("subtotal", |e: &Order| e.subtotal))
        .rule(NonNegative::new("discount_amount", |e: &Order| e.discount_amount))
        .rule(NonNegative::new("delivery_fee", |e: &Order| e.delivery_fee))
        .rule(NonNegative::new("pickup_fee", |e: &Order| e.pickup_fee))
        .rule(NonNegative::new("tax_amount", |e: &Order| e.tax_amount))
        .rule(NonNegative::new("platform_fee", |e: &Order| e.platform_fee))
        .rule(NonNegative::new("grand_total", |e: &Order| e.grand_total))
        .rule(NonNegative::new("paid_amount", |e: &Order| e.paid_amount))
        .rule(OptionalNotBlank::new("special_instructions", |e: &Order| e.special_instructions.as_deref()))
        .rule(OptionalNotBlank::new("provider_notes", |e: &Order| e.provider_notes.as_deref()))
        .rule(OptionalNotBlank::new("cancellation_note", |e: &Order| e.cancellation_note.as_deref()))
        .rule(OptionalNotBlank::new("source", |e: &Order| e.source.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
