//! Validator for OrderDelivery entity
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<OrderDelivery>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative, OptionalNotBlank, RequiredString, RequiredUuid};
use crate::domain::entity::OrderDelivery;

/// Validator type alias for OrderDelivery entities.
pub type OrderDeliveryValidator = EntityValidator<OrderDelivery>;

/// Build a validator for OrderDelivery with all schema-defined field rules.
pub fn order_delivery_validator() -> OrderDeliveryValidator {
    EntityValidator::new()
        .rule(RequiredUuid::new("order_id", |e: &OrderDelivery| &e.order_id))
        .rule(OptionalNotBlank::new("scheduled_time_start", |e: &OrderDelivery| e.scheduled_time_start.as_deref()))
        .rule(OptionalNotBlank::new("scheduled_time_end", |e: &OrderDelivery| e.scheduled_time_end.as_deref()))
        .rule(OptionalNotBlank::new("time_slot", |e: &OrderDelivery| e.time_slot.as_deref()))
        .rule(OptionalNotBlank::new("customer_requested_time_start", |e: &OrderDelivery| e.customer_requested_time_start.as_deref()))
        .rule(OptionalNotBlank::new("customer_requested_time_end", |e: &OrderDelivery| e.customer_requested_time_end.as_deref()))
        .rule(RequiredString::new("address_line", |e: &OrderDelivery| &e.address_line))
        .rule(OptionalNotBlank::new("address_detail", |e: &OrderDelivery| e.address_detail.as_deref()))
        .rule(OptionalNotBlank::new("landmark", |e: &OrderDelivery| e.landmark.as_deref()))
        .rule(RequiredString::new("contact_name", |e: &OrderDelivery| &e.contact_name))
        .rule(RequiredString::new("contact_phone", |e: &OrderDelivery| &e.contact_phone))
        .rule(OptionalNotBlank::new("contact_phone_alt", |e: &OrderDelivery| e.contact_phone_alt.as_deref()))
        .rule(OptionalNotBlank::new("agent_name", |e: &OrderDelivery| e.agent_name.as_deref()))
        .rule(OptionalNotBlank::new("agent_phone", |e: &OrderDelivery| e.agent_phone.as_deref()))
        .rule(NonNegative::new("item_count", |e: &OrderDelivery| e.item_count))
        .rule(NonNegative::new("bag_count", |e: &OrderDelivery| e.bag_count))
        .rule(OptionalNotBlank::new("verification_method", |e: &OrderDelivery| e.verification_method.as_deref()))
        .rule(OptionalNotBlank::new("verification_code", |e: &OrderDelivery| e.verification_code.as_deref()))
        .rule(OptionalNotBlank::new("proof_photo_url", |e: &OrderDelivery| e.proof_photo_url.as_deref()))
        .rule(OptionalNotBlank::new("signature_url", |e: &OrderDelivery| e.signature_url.as_deref()))
        .rule(OptionalNotBlank::new("signed_by", |e: &OrderDelivery| e.signed_by.as_deref()))
        .rule(OptionalNotBlank::new("relation_to_customer", |e: &OrderDelivery| e.relation_to_customer.as_deref()))
        .rule(NonNegative::new("distance_from_address_meters", |e: &OrderDelivery| e.distance_from_address_meters))
        .rule(NonNegative::new("delivery_fee", |e: &OrderDelivery| e.delivery_fee))
        .rule(NonNegative::new("express_fee", |e: &OrderDelivery| e.express_fee))
        .rule(NonNegative::new("total_fee", |e: &OrderDelivery| e.total_fee))
        .rule(RequiredString::new("currency", |e: &OrderDelivery| &e.currency))
        .rule(NonNegative::new("cod_amount", |e: &OrderDelivery| e.cod_amount))
        .rule(OptionalNotBlank::new("customer_notes", |e: &OrderDelivery| e.customer_notes.as_deref()))
        .rule(OptionalNotBlank::new("agent_notes", |e: &OrderDelivery| e.agent_notes.as_deref()))
        .rule(OptionalNotBlank::new("internal_notes", |e: &OrderDelivery| e.internal_notes.as_deref()))
        .rule(OptionalNotBlank::new("failure_reason", |e: &OrderDelivery| e.failure_reason.as_deref()))
        .rule(OptionalNotBlank::new("failure_code", |e: &OrderDelivery| e.failure_code.as_deref()))
        .rule(NonNegative::new("reschedule_count", |e: &OrderDelivery| e.reschedule_count))
        .rule(OptionalNotBlank::new("reschedule_reason", |e: &OrderDelivery| e.reschedule_reason.as_deref()))
        .rule(OptionalNotBlank::new("rating_comment", |e: &OrderDelivery| e.rating_comment.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
