//! Validator for OrderItem entity
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<OrderItem>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative, OptionalNotBlank, RequiredString, RequiredUuid};
use crate::domain::entity::OrderItem;

/// Validator type alias for OrderItem entities.
pub type OrderItemValidator = EntityValidator<OrderItem>;

/// Build a validator for OrderItem with all schema-defined field rules.
pub fn order_item_validator() -> OrderItemValidator {
    EntityValidator::new()
        .rule(RequiredUuid::new("order_id", |e: &OrderItem| &e.order_id))
        .rule(OptionalNotBlank::new("item_name", |e: &OrderItem| e.item_name.as_deref()))
        .rule(NonNegative::new("unit_price", |e: &OrderItem| e.unit_price))
        .rule(NonNegative::new("subtotal", |e: &OrderItem| e.subtotal))
        .rule(NonNegative::new("discount", |e: &OrderItem| e.discount))
        .rule(NonNegative::new("addon_total", |e: &OrderItem| e.addon_total))
        .rule(NonNegative::new("total", |e: &OrderItem| e.total))
        .rule(RequiredString::new("currency", |e: &OrderItem| &e.currency))
        .rule(OptionalNotBlank::new("condition_notes", |e: &OrderItem| e.condition_notes.as_deref()))
        .rule(OptionalNotBlank::new("special_instructions", |e: &OrderItem| e.special_instructions.as_deref()))
        .rule(OptionalNotBlank::new("processing_notes", |e: &OrderItem| e.processing_notes.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
