//! Validator for OrderPickup entity
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<OrderPickup>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative, OptionalNotBlank, RequiredString, RequiredUuid};
use crate::domain::entity::OrderPickup;

/// Validator type alias for OrderPickup entities.
pub type OrderPickupValidator = EntityValidator<OrderPickup>;

/// Build a validator for OrderPickup with all schema-defined field rules.
pub fn order_pickup_validator() -> OrderPickupValidator {
    EntityValidator::new()
        .rule(RequiredUuid::new("order_id", |e: &OrderPickup| &e.order_id))
        .rule(OptionalNotBlank::new("scheduled_time_start", |e: &OrderPickup| e.scheduled_time_start.as_deref()))
        .rule(OptionalNotBlank::new("scheduled_time_end", |e: &OrderPickup| e.scheduled_time_end.as_deref()))
        .rule(OptionalNotBlank::new("time_slot", |e: &OrderPickup| e.time_slot.as_deref()))
        .rule(OptionalNotBlank::new("customer_requested_time_start", |e: &OrderPickup| e.customer_requested_time_start.as_deref()))
        .rule(OptionalNotBlank::new("customer_requested_time_end", |e: &OrderPickup| e.customer_requested_time_end.as_deref()))
        .rule(RequiredString::new("address_line", |e: &OrderPickup| &e.address_line))
        .rule(OptionalNotBlank::new("address_detail", |e: &OrderPickup| e.address_detail.as_deref()))
        .rule(OptionalNotBlank::new("landmark", |e: &OrderPickup| e.landmark.as_deref()))
        .rule(RequiredString::new("contact_name", |e: &OrderPickup| &e.contact_name))
        .rule(RequiredString::new("contact_phone", |e: &OrderPickup| &e.contact_phone))
        .rule(OptionalNotBlank::new("contact_phone_alt", |e: &OrderPickup| e.contact_phone_alt.as_deref()))
        .rule(OptionalNotBlank::new("agent_name", |e: &OrderPickup| e.agent_name.as_deref()))
        .rule(OptionalNotBlank::new("agent_phone", |e: &OrderPickup| e.agent_phone.as_deref()))
        .rule(NonNegative::new("estimated_weight_kg", |e: &OrderPickup| e.estimated_weight_kg))
        .rule(NonNegative::new("actual_weight_kg", |e: &OrderPickup| e.actual_weight_kg))
        .rule(NonNegative::new("estimated_items", |e: &OrderPickup| e.estimated_items))
        .rule(NonNegative::new("actual_items", |e: &OrderPickup| e.actual_items))
        .rule(NonNegative::new("bag_count", |e: &OrderPickup| e.bag_count))
        .rule(OptionalNotBlank::new("signature_url", |e: &OrderPickup| e.signature_url.as_deref()))
        .rule(OptionalNotBlank::new("signed_by", |e: &OrderPickup| e.signed_by.as_deref()))
        .rule(NonNegative::new("distance_from_address_meters", |e: &OrderPickup| e.distance_from_address_meters))
        .rule(OptionalNotBlank::new("customer_notes", |e: &OrderPickup| e.customer_notes.as_deref()))
        .rule(OptionalNotBlank::new("agent_notes", |e: &OrderPickup| e.agent_notes.as_deref()))
        .rule(OptionalNotBlank::new("internal_notes", |e: &OrderPickup| e.internal_notes.as_deref()))
        .rule(OptionalNotBlank::new("failure_reason", |e: &OrderPickup| e.failure_reason.as_deref()))
        .rule(OptionalNotBlank::new("failure_code", |e: &OrderPickup| e.failure_code.as_deref()))
        .rule(NonNegative::new("reschedule_count", |e: &OrderPickup| e.reschedule_count))
        .rule(OptionalNotBlank::new("reschedule_reason", |e: &OrderPickup| e.reschedule_reason.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
