//! Domain Entities
//!
//! Generated by backbone-schema. Do not edit manually.

pub mod delivery_tier;
pub mod order;
pub mod order_delivery;
pub mod order_item;
pub mod order_pickup;
pub mod order_status_timeline;
pub mod order_status;
pub mod order_type;
pub mod fulfillment_method;
pub mod payment_status;
pub mod cancellation_reason;
pub mod delivery_status;
pub mod delivery_type;
pub mod item_condition;
pub mod item_processing_status;
pub mod unit_type;
pub mod pickup_status;
pub mod pickup_type;
pub mod timeline_entry_type;

// Re-exports
pub use delivery_tier::DeliveryTier;
pub use delivery_tier::DeliveryTierBuilder;
pub use delivery_tier::DeliveryTierId;
pub use order::Order;
pub use order::OrderBuilder;
pub use order::OrderId;
pub use order_delivery::OrderDelivery;
pub use order_delivery::OrderDeliveryBuilder;
pub use order_delivery::OrderDeliveryId;
pub use order_item::OrderItem;
pub use order_item::OrderItemBuilder;
pub use order_item::OrderItemId;
pub use order_pickup::OrderPickup;
pub use order_pickup::OrderPickupBuilder;
pub use order_pickup::OrderPickupId;
pub use order_status_timeline::OrderStatusTimeline;
pub use order_status_timeline::OrderStatusTimelineBuilder;
pub use order_status_timeline::OrderStatusTimelineId;
pub use order_status::OrderStatus;
pub use order_type::OrderType;
pub use fulfillment_method::FulfillmentMethod;
pub use payment_status::PaymentStatus;
pub use cancellation_reason::CancellationReason;
pub use delivery_status::DeliveryStatus;
pub use delivery_type::DeliveryType;
pub use item_condition::ItemCondition;
pub use item_processing_status::ItemProcessingStatus;
pub use unit_type::UnitType;
pub use pickup_status::PickupStatus;
pub use pickup_type::PickupType;
pub use timeline_entry_type::TimelineEntryType;

// ==========================================================================
// Entity Trait
// ==========================================================================

use std::fmt::Debug;

/// Trait for domain entities
///
/// All generated entities implement this trait, providing
/// a common interface for working with domain objects.
pub trait Entity: Debug + Clone {
    /// The type of the entity's unique identifier
    type Id: Debug + Clone + PartialEq;

    /// Get the entity's unique identifier
    fn entity_id(&self) -> &Self::Id;

    /// Get the entity type name
    fn entity_type() -> &'static str;
}

// ==========================================================================
// Audit Metadata
// ==========================================================================

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// Audit metadata stored as JSONB in the database
///
/// This struct consolidates audit fields (timestamps and actors) into a single
/// JSONB column for efficient storage and flexible querying.
#[derive(Debug, Clone, Default, Serialize, Deserialize, PartialEq)]
pub struct AuditMetadata {
    /// Timestamp when the record was created
    #[serde(skip_serializing_if = "Option::is_none")]
    pub created_at: Option<DateTime<Utc>>,

    /// Timestamp when the record was last updated
    #[serde(skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<DateTime<Utc>>,

    /// Timestamp when the record was soft-deleted
    #[serde(skip_serializing_if = "Option::is_none")]
    pub deleted_at: Option<DateTime<Utc>>,

    /// User ID who created the record
    #[serde(skip_serializing_if = "Option::is_none")]
    pub created_by: Option<Uuid>,

    /// User ID who last updated the record
    #[serde(skip_serializing_if = "Option::is_none")]
    pub updated_by: Option<Uuid>,

    /// User ID who deleted the record
    #[serde(skip_serializing_if = "Option::is_none")]
    pub deleted_by: Option<Uuid>,
}

impl AuditMetadata {
    /// Create new audit metadata with created_at set to now
    pub fn new() -> Self {
        Self {
            created_at: Some(Utc::now()),
            ..Default::default()
        }
    }

    /// Create with creator ID
    pub fn with_creator(creator_id: Uuid) -> Self {
        Self {
            created_at: Some(Utc::now()),
            created_by: Some(creator_id),
            ..Default::default()
        }
    }

    /// Touch the record (update updated_at)
    pub fn touch(&mut self) {
        self.updated_at = Some(Utc::now());
    }

    /// Touch with updater ID
    pub fn touch_by(&mut self, updater_id: Uuid) {
        self.updated_at = Some(Utc::now());
        self.updated_by = Some(updater_id);
    }

    /// Soft delete the record
    pub fn soft_delete(&mut self) {
        self.deleted_at = Some(Utc::now());
    }

    /// Soft delete with deleter ID
    pub fn soft_delete_by(&mut self, deleter_id: Uuid) {
        self.deleted_at = Some(Utc::now());
        self.deleted_by = Some(deleter_id);
    }

    /// Restore a soft-deleted record
    pub fn restore(&mut self) {
        self.deleted_at = None;
        self.deleted_by = None;
    }

    /// Check if record is deleted
    pub fn is_deleted(&self) -> bool {
        self.deleted_at.is_some()
    }

    /// Check if record is active (not deleted)
    pub fn is_active(&self) -> bool {
        self.deleted_at.is_none()
    }
}
