//! Auth configuration for DeliveryTier handlers
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<DeliveryTier>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::DeliveryTierService;
use crate::domain::entity::DeliveryTier;

/// Permission string constants for DeliveryTier operations.
pub mod permissions {
    pub const LIST:        &str = "delivery_tier:list";
    pub const READ:        &str = "delivery_tier:read";
    pub const CREATE:      &str = "delivery_tier:create";
    pub const UPDATE:      &str = "delivery_tier:update";
    pub const DELETE:      &str = "delivery_tier:delete";
    pub const RESTORE:     &str = "delivery_tier:restore";
    pub const TRASH:       &str = "delivery_tier:trash";
    pub const EMPTY_TRASH: &str = "delivery_tier:empty_trash";
    pub const BULK_CREATE: &str = "delivery_tier:bulk_create";
    pub const UPSERT:      &str = "delivery_tier:upsert";
}

/// Resource policy for DeliveryTier — maps CRUD actions to permission strings.
pub struct DeliveryTierPolicy;

#[async_trait]
impl ResourcePolicy<DeliveryTier> for DeliveryTierPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &DeliveryTier,
        ctx: &backbone_auth::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read   => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update => permissions::UPDATE,
            ResourceAction::Delete => permissions::DELETE,
        };
        ctx.has_permission(required)
    }
}

/// Permission guard for DeliveryTier handlers.
///
/// Wraps `DeliveryTierService` and checks `DeliveryTierPolicy` before delegating.
pub type DeliveryTierGuard = PermissionGuard<DeliveryTier, DeliveryTierService, DeliveryTierPolicy>;

/// Service-integrated permission guard for DeliveryTier (for use in generated handlers).
pub type DeliveryTierServiceGuard = ServicePermissionGuard<DeliveryTier, DeliveryTierService, DeliveryTierPolicy>;

// <<< CUSTOM
// END CUSTOM
