//! Auth configuration for OrderPickup handlers
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<OrderPickup>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::OrderPickupService;
use crate::domain::entity::OrderPickup;

/// Permission string constants for OrderPickup operations.
pub mod permissions {
    pub const LIST:        &str = "order_pickup:list";
    pub const READ:        &str = "order_pickup:read";
    pub const CREATE:      &str = "order_pickup:create";
    pub const UPDATE:      &str = "order_pickup:update";
    pub const DELETE:      &str = "order_pickup:delete";
    pub const RESTORE:     &str = "order_pickup:restore";
    pub const TRASH:       &str = "order_pickup:trash";
    pub const EMPTY_TRASH: &str = "order_pickup:empty_trash";
    pub const BULK_CREATE: &str = "order_pickup:bulk_create";
    pub const UPSERT:      &str = "order_pickup:upsert";
}

/// Resource policy for OrderPickup — maps CRUD actions to permission strings.
pub struct OrderPickupPolicy;

#[async_trait]
impl ResourcePolicy<OrderPickup> for OrderPickupPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &OrderPickup,
        ctx: &backbone_auth::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read   => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update => permissions::UPDATE,
            ResourceAction::Delete => permissions::DELETE,
        };
        ctx.has_permission(required)
    }
}

/// Permission guard for OrderPickup handlers.
///
/// Wraps `OrderPickupService` and checks `OrderPickupPolicy` before delegating.
pub type OrderPickupGuard = PermissionGuard<OrderPickup, OrderPickupService, OrderPickupPolicy>;

/// Service-integrated permission guard for OrderPickup (for use in generated handlers).
pub type OrderPickupServiceGuard = ServicePermissionGuard<OrderPickup, OrderPickupService, OrderPickupPolicy>;

// <<< CUSTOM
// END CUSTOM
