//! Auth configuration for Order handlers
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<Order>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::OrderService;
use crate::domain::entity::Order;

/// Permission string constants for Order operations.
pub mod permissions {
    pub const LIST:        &str = "order:list";
    pub const READ:        &str = "order:read";
    pub const CREATE:      &str = "order:create";
    pub const UPDATE:      &str = "order:update";
    pub const DELETE:      &str = "order:delete";
    pub const RESTORE:     &str = "order:restore";
    pub const TRASH:       &str = "order:trash";
    pub const EMPTY_TRASH: &str = "order:empty_trash";
    pub const BULK_CREATE: &str = "order:bulk_create";
    pub const UPSERT:      &str = "order:upsert";
}

/// Resource policy for Order — maps CRUD actions to permission strings.
pub struct OrderPolicy;

#[async_trait]
impl ResourcePolicy<Order> for OrderPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &Order,
        ctx: &backbone_auth::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read   => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update => permissions::UPDATE,
            ResourceAction::Delete => permissions::DELETE,
        };
        ctx.has_permission(required)
    }
}

/// Permission guard for Order handlers.
///
/// Wraps `OrderService` and checks `OrderPolicy` before delegating.
pub type OrderGuard = PermissionGuard<Order, OrderService, OrderPolicy>;

/// Service-integrated permission guard for Order (for use in generated handlers).
pub type OrderServiceGuard = ServicePermissionGuard<Order, OrderService, OrderPolicy>;

// <<< CUSTOM
// END CUSTOM
