//! Auth configuration for OrderStatusTimeline handlers
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<OrderStatusTimeline>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::OrderStatusTimelineService;
use crate::domain::entity::OrderStatusTimeline;

/// Permission string constants for OrderStatusTimeline operations.
pub mod permissions {
    pub const LIST:        &str = "order_status_timeline:list";
    pub const READ:        &str = "order_status_timeline:read";
    pub const CREATE:      &str = "order_status_timeline:create";
    pub const UPDATE:      &str = "order_status_timeline:update";
    pub const DELETE:      &str = "order_status_timeline:delete";
    pub const RESTORE:     &str = "order_status_timeline:restore";
    pub const TRASH:       &str = "order_status_timeline:trash";
    pub const EMPTY_TRASH: &str = "order_status_timeline:empty_trash";
    pub const BULK_CREATE: &str = "order_status_timeline:bulk_create";
    pub const UPSERT:      &str = "order_status_timeline:upsert";
}

/// Resource policy for OrderStatusTimeline — maps CRUD actions to permission strings.
pub struct OrderStatusTimelinePolicy;

#[async_trait]
impl ResourcePolicy<OrderStatusTimeline> for OrderStatusTimelinePolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &OrderStatusTimeline,
        ctx: &backbone_auth::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read   => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update => permissions::UPDATE,
            ResourceAction::Delete => permissions::DELETE,
        };
        ctx.has_permission(required)
    }
}

/// Permission guard for OrderStatusTimeline handlers.
///
/// Wraps `OrderStatusTimelineService` and checks `OrderStatusTimelinePolicy` before delegating.
pub type OrderStatusTimelineGuard = PermissionGuard<OrderStatusTimeline, OrderStatusTimelineService, OrderStatusTimelinePolicy>;

/// Service-integrated permission guard for OrderStatusTimeline (for use in generated handlers).
pub type OrderStatusTimelineServiceGuard = ServicePermissionGuard<OrderStatusTimeline, OrderStatusTimelineService, OrderStatusTimelinePolicy>;

// <<< CUSTOM
// END CUSTOM
