//! Auth configuration for OrderItem handlers
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<OrderItem>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::OrderItemService;
use crate::domain::entity::OrderItem;

/// Permission string constants for OrderItem operations.
pub mod permissions {
    pub const LIST:        &str = "order_item:list";
    pub const READ:        &str = "order_item:read";
    pub const CREATE:      &str = "order_item:create";
    pub const UPDATE:      &str = "order_item:update";
    pub const DELETE:      &str = "order_item:delete";
    pub const RESTORE:     &str = "order_item:restore";
    pub const TRASH:       &str = "order_item:trash";
    pub const EMPTY_TRASH: &str = "order_item:empty_trash";
    pub const BULK_CREATE: &str = "order_item:bulk_create";
    pub const UPSERT:      &str = "order_item:upsert";
}

/// Resource policy for OrderItem — maps CRUD actions to permission strings.
pub struct OrderItemPolicy;

#[async_trait]
impl ResourcePolicy<OrderItem> for OrderItemPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &OrderItem,
        ctx: &backbone_auth::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read   => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update => permissions::UPDATE,
            ResourceAction::Delete => permissions::DELETE,
        };
        ctx.has_permission(required)
    }
}

/// Permission guard for OrderItem handlers.
///
/// Wraps `OrderItemService` and checks `OrderItemPolicy` before delegating.
pub type OrderItemGuard = PermissionGuard<OrderItem, OrderItemService, OrderItemPolicy>;

/// Service-integrated permission guard for OrderItem (for use in generated handlers).
pub type OrderItemServiceGuard = ServicePermissionGuard<OrderItem, OrderItemService, OrderItemPolicy>;

// <<< CUSTOM
// END CUSTOM
