//! Auth configuration for OrderDelivery handlers
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<OrderDelivery>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::OrderDeliveryService;
use crate::domain::entity::OrderDelivery;

/// Permission string constants for OrderDelivery operations.
pub mod permissions {
    pub const LIST:        &str = "order_delivery:list";
    pub const READ:        &str = "order_delivery:read";
    pub const CREATE:      &str = "order_delivery:create";
    pub const UPDATE:      &str = "order_delivery:update";
    pub const DELETE:      &str = "order_delivery:delete";
    pub const RESTORE:     &str = "order_delivery:restore";
    pub const TRASH:       &str = "order_delivery:trash";
    pub const EMPTY_TRASH: &str = "order_delivery:empty_trash";
    pub const BULK_CREATE: &str = "order_delivery:bulk_create";
    pub const UPSERT:      &str = "order_delivery:upsert";
}

/// Resource policy for OrderDelivery — maps CRUD actions to permission strings.
pub struct OrderDeliveryPolicy;

#[async_trait]
impl ResourcePolicy<OrderDelivery> for OrderDeliveryPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &OrderDelivery,
        ctx: &backbone_auth::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read   => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update => permissions::UPDATE,
            ResourceAction::Delete => permissions::DELETE,
        };
        ctx.has_permission(required)
    }
}

/// Permission guard for OrderDelivery handlers.
///
/// Wraps `OrderDeliveryService` and checks `OrderDeliveryPolicy` before delegating.
pub type OrderDeliveryGuard = PermissionGuard<OrderDelivery, OrderDeliveryService, OrderDeliveryPolicy>;

/// Service-integrated permission guard for OrderDelivery (for use in generated handlers).
pub type OrderDeliveryServiceGuard = ServicePermissionGuard<OrderDelivery, OrderDeliveryService, OrderDeliveryPolicy>;

// <<< CUSTOM
// END CUSTOM
