//! OrderDelivery API Integration Tests
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Tests the OrderDelivery CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::helpers::CommonUtils;

// ============================================================================
// ORDERDELIVERY TEST DATA GENERATOR
// ============================================================================

/// Test data generator for OrderDelivery
pub struct OrderDeliveryTestData;

impl TestDataGenerator for OrderDeliveryTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "order_id": null,
            "delivery_type": null,
            "scheduled_date": null,
            "scheduled_time_start": null,
            "scheduled_time_end": null,
            "time_slot": null,
            "customer_requested_date": null,
            "customer_requested_time_start": null,
            "customer_requested_time_end": null,
            "address_id": null,
            "address_line": null,
            "address_detail": null,
            "landmark": null,
            "latitude": null,
            "longitude": null,
            "contact_name": null,
            "contact_phone": null,
            "contact_phone_alt": null,
            "agent_id": null,
            "agent_name": null,
            "agent_phone": null,
            "assigned_at": now,
            "status": null,
            "dispatched_at": now,
            "en_route_at": now,
            "arrived_at": now,
            "delivered_at": now,
            "item_count": null,
            "bag_count": null,
            "bag_numbers": null,
            "verification_method": null,
            "verification_code": null,
            "verified_at": now,
            "photos": null,
            "proof_photo_url": null,
            "signature_url": null,
            "signed_by": null,
            "relation_to_customer": null,
            "delivery_latitude": null,
            "delivery_longitude": null,
            "distance_from_address_meters": null,
            "delivery_fee": null,
            "express_fee": null,
            "total_fee": null,
            "currency": null,
            "is_cod": false,
            "cod_amount": null,
            "cod_collected": null,
            "cod_collected_at": now,
            "customer_notes": null,
            "agent_notes": null,
            "internal_notes": null,
            "failure_reason": null,
            "failure_code": null,
            "attempt_count": null,
            "reschedule_count": null,
            "original_scheduled_date": null,
            "reschedule_reason": null,
            "delivery_rating": null,
            "rating_comment": null,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "order_id": null,
            "delivery_type": null,
            "scheduled_date": null,
            "scheduled_time_start": null,
            "scheduled_time_end": null,
            "time_slot": null,
            "customer_requested_date": null,
            "customer_requested_time_start": null,
            "customer_requested_time_end": null,
            "address_id": null,
            "address_line": null,
            "address_detail": null,
            "landmark": null,
            "latitude": null,
            "longitude": null,
            "contact_name": null,
            "contact_phone": null,
            "contact_phone_alt": null,
            "agent_id": null,
            "agent_name": null,
            "agent_phone": null,
            "assigned_at": now,
            "status": null,
            "dispatched_at": now,
            "en_route_at": now,
            "arrived_at": now,
            "delivered_at": now,
            "item_count": null,
            "bag_count": null,
            "bag_numbers": null,
            "verification_method": null,
            "verification_code": null,
            "verified_at": now,
            "photos": null,
            "proof_photo_url": null,
            "signature_url": null,
            "signed_by": null,
            "relation_to_customer": null,
            "delivery_latitude": null,
            "delivery_longitude": null,
            "distance_from_address_meters": null,
            "delivery_fee": null,
            "express_fee": null,
            "total_fee": null,
            "currency": null,
            "is_cod": false,
            "cod_amount": null,
            "cod_collected": null,
            "cod_collected_at": now,
            "customer_notes": null,
            "agent_notes": null,
            "internal_notes": null,
            "failure_reason": null,
            "failure_code": null,
            "attempt_count": null,
            "reschedule_count": null,
            "original_scheduled_date": null,
            "reschedule_reason": null,
            "delivery_rating": null,
            "rating_comment": null,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// ORDERDELIVERY API TEST
// ============================================================================

/// OrderDelivery API test suite
pub struct OrderDeliveryApiTest {
    inner: GenericCrudTest<OrderDeliveryTestData>,
}

impl OrderDeliveryApiTest {
    pub fn new() -> Self {
        let config = CrudTestConfig::new("/api/v1/order_deliveries", "OrderDelivery");
        Self {
            inner: GenericCrudTest::new(config, OrderDeliveryTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for OrderDeliveryApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_order_delivery_crud() {
        let mut test = OrderDeliveryApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add OrderDelivery specific tests here
// <<< CUSTOM TESTS END >>>
