//! Order API Integration Tests
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Tests the Order CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::helpers::CommonUtils;

// ============================================================================
// ORDER TEST DATA GENERATOR
// ============================================================================

/// Test data generator for Order
pub struct OrderTestData;

impl TestDataGenerator for OrderTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "order_number": null,
            "customer_id": null,
            "provider_id": null,
            "outlet_id": null,
            "corporate_order_id": null,
            "delivery_tier_id": null,
            "order_type": null,
            "status": null,
            "fulfillment_method": null,
            "estimated_ready_at": now,
            "actual_ready_at": now,
            "currency": null,
            "subtotal": null,
            "discount_amount": null,
            "promo_id": null,
            "delivery_fee": null,
            "pickup_fee": null,
            "tax_amount": null,
            "platform_fee": null,
            "grand_total": null,
            "payment_status": null,
            "paid_amount": null,
            "paid_at": now,
            "special_instructions": null,
            "provider_notes": null,
            "cancelled_at": now,
            "cancellation_reason": null,
            "cancellation_note": null,
            "cancelled_by": null,
            "data": null,
            "source": null,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "order_number": null,
            "customer_id": null,
            "provider_id": null,
            "outlet_id": null,
            "corporate_order_id": null,
            "delivery_tier_id": null,
            "order_type": null,
            "status": null,
            "fulfillment_method": null,
            "estimated_ready_at": now,
            "actual_ready_at": now,
            "currency": null,
            "subtotal": null,
            "discount_amount": null,
            "promo_id": null,
            "delivery_fee": null,
            "pickup_fee": null,
            "tax_amount": null,
            "platform_fee": null,
            "grand_total": null,
            "payment_status": null,
            "paid_amount": null,
            "paid_at": now,
            "special_instructions": null,
            "provider_notes": null,
            "cancelled_at": now,
            "cancellation_reason": null,
            "cancellation_note": null,
            "cancelled_by": null,
            "data": null,
            "source": null,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// ORDER API TEST
// ============================================================================

/// Order API test suite
pub struct OrderApiTest {
    inner: GenericCrudTest<OrderTestData>,
}

impl OrderApiTest {
    pub fn new() -> Self {
        let config = CrudTestConfig::new("/api/v1/orders", "Order");
        Self {
            inner: GenericCrudTest::new(config, OrderTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for OrderApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_order_crud() {
        let mut test = OrderApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add Order specific tests here
// <<< CUSTOM TESTS END >>>
