//! OrderItem API Integration Tests
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Tests the OrderItem CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::helpers::CommonUtils;

// ============================================================================
// ORDERITEM TEST DATA GENERATOR
// ============================================================================

/// Test data generator for OrderItem
pub struct OrderItemTestData;

impl TestDataGenerator for OrderItemTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "order_id": null,
            "service_id": null,
            "item_name": null,
            "quantity": null,
            "unit_type": null,
            "unit_price": null,
            "subtotal": null,
            "discount": null,
            "addon_total": null,
            "total": null,
            "currency": null,
            "addons": null,
            "condition_on_receipt": null,
            "condition_notes": null,
            "processing_status": null,
            "special_instructions": null,
            "processing_notes": null,
            "delivery_tier_id": null,
            "started_at": now,
            "completed_at": now,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "order_id": null,
            "service_id": null,
            "item_name": null,
            "quantity": null,
            "unit_type": null,
            "unit_price": null,
            "subtotal": null,
            "discount": null,
            "addon_total": null,
            "total": null,
            "currency": null,
            "addons": null,
            "condition_on_receipt": null,
            "condition_notes": null,
            "processing_status": null,
            "special_instructions": null,
            "processing_notes": null,
            "delivery_tier_id": null,
            "started_at": now,
            "completed_at": now,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// ORDERITEM API TEST
// ============================================================================

/// OrderItem API test suite
pub struct OrderItemApiTest {
    inner: GenericCrudTest<OrderItemTestData>,
}

impl OrderItemApiTest {
    pub fn new() -> Self {
        let config = CrudTestConfig::new("/api/v1/order_items", "OrderItem");
        Self {
            inner: GenericCrudTest::new(config, OrderItemTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for OrderItemApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_order_item_crud() {
        let mut test = OrderItemApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add OrderItem specific tests here
// <<< CUSTOM TESTS END >>>
