//! Projections (CQRS read models) for Orders module
//!
//! Projections are optimized read models built from domain events.
//! They provide query-specific views of the data.
//!
//! Generated by backbone-schema. Custom code sections are preserved.

// Projections will be generated here by backbone-schema
// Use: backbone schema generate orders --target projection
