//! Public events for Orders module
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! These events are published by this module for other modules to subscribe to.
//! Events are the primary mechanism for cross-module communication.

use serde::{Deserialize, Serialize};
use chrono::{DateTime, Utc};

use super::types::*;

// ============================================================================
// DELIVERYTIER EVENTS
// ============================================================================

/// Event published when a DeliveryTier is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DeliveryTierCreatedEvent {
    pub id: DeliveryTierId,
    pub data: DeliveryTierDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a DeliveryTier is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DeliveryTierUpdatedEvent {
    pub id: DeliveryTierId,
    pub data: DeliveryTierDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a DeliveryTier is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DeliveryTierDeletedEvent {
    pub id: DeliveryTierId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// ORDER EVENTS
// ============================================================================

/// Event published when a Order is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrderCreatedEvent {
    pub id: OrderId,
    pub data: OrderDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Order is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrderUpdatedEvent {
    pub id: OrderId,
    pub data: OrderDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Order is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrderDeletedEvent {
    pub id: OrderId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// ORDERDELIVERY EVENTS
// ============================================================================

/// Event published when a OrderDelivery is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrderDeliveryCreatedEvent {
    pub id: OrderDeliveryId,
    pub data: OrderDeliveryDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a OrderDelivery is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrderDeliveryUpdatedEvent {
    pub id: OrderDeliveryId,
    pub data: OrderDeliveryDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a OrderDelivery is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrderDeliveryDeletedEvent {
    pub id: OrderDeliveryId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// ORDERITEM EVENTS
// ============================================================================

/// Event published when a OrderItem is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrderItemCreatedEvent {
    pub id: OrderItemId,
    pub data: OrderItemDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a OrderItem is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrderItemUpdatedEvent {
    pub id: OrderItemId,
    pub data: OrderItemDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a OrderItem is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrderItemDeletedEvent {
    pub id: OrderItemId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// ORDERPICKUP EVENTS
// ============================================================================

/// Event published when a OrderPickup is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrderPickupCreatedEvent {
    pub id: OrderPickupId,
    pub data: OrderPickupDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a OrderPickup is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrderPickupUpdatedEvent {
    pub id: OrderPickupId,
    pub data: OrderPickupDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a OrderPickup is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrderPickupDeletedEvent {
    pub id: OrderPickupId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// ORDERSTATUSTIMELINE EVENTS
// ============================================================================

/// Event published when a OrderStatusTimeline is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrderStatusTimelineCreatedEvent {
    pub id: OrderStatusTimelineId,
    pub data: OrderStatusTimelineDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a OrderStatusTimeline is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrderStatusTimelineUpdatedEvent {
    pub id: OrderStatusTimelineId,
    pub data: OrderStatusTimelineDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a OrderStatusTimeline is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrderStatusTimelineDeletedEvent {
    pub id: OrderStatusTimelineId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// MODULE EVENT ENUM
// ============================================================================

/// All events published by Orders module
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum OrdersEvent {
    DeliveryTierCreated(DeliveryTierCreatedEvent),
    DeliveryTierUpdated(DeliveryTierUpdatedEvent),
    DeliveryTierDeleted(DeliveryTierDeletedEvent),
    OrderCreated(OrderCreatedEvent),
    OrderUpdated(OrderUpdatedEvent),
    OrderDeleted(OrderDeletedEvent),
    OrderDeliveryCreated(OrderDeliveryCreatedEvent),
    OrderDeliveryUpdated(OrderDeliveryUpdatedEvent),
    OrderDeliveryDeleted(OrderDeliveryDeletedEvent),
    OrderItemCreated(OrderItemCreatedEvent),
    OrderItemUpdated(OrderItemUpdatedEvent),
    OrderItemDeleted(OrderItemDeletedEvent),
    OrderPickupCreated(OrderPickupCreatedEvent),
    OrderPickupUpdated(OrderPickupUpdatedEvent),
    OrderPickupDeleted(OrderPickupDeletedEvent),
    OrderStatusTimelineCreated(OrderStatusTimelineCreatedEvent),
    OrderStatusTimelineUpdated(OrderStatusTimelineUpdatedEvent),
    OrderStatusTimelineDeleted(OrderStatusTimelineDeletedEvent),
}

/// Metadata for module events
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrdersEventMetadata {
    pub module: &'static str,
    pub version: &'static str,
}

impl Default for OrdersEventMetadata {
    fn default() -> Self {
        Self {
            module: "orders",
            version: "1.0",
        }
    }
}

// ============================================================================
// CUSTOM EVENTS
// ============================================================================

// <<< CUSTOM EVENTS START >>>
// Add custom public events here
// <<< CUSTOM EVENTS END >>>
