//! Orders Module Exports
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! This module defines the public API that Orders exposes to other modules.
//! Other modules should ONLY depend on types defined here, not internal types.
//!
//! ## Usage from other modules
//!
//! ```text
//! use orders::exports::{DeliveryTierDto, OrdersQueryService};
//! ```

mod types;
mod services;
mod events;

// Re-export all public types
pub use types::*;
pub use services::*;
pub use events::*;

// ============================================================================
// EXPORT SUMMARY
// ============================================================================

/// Summary of what this module exports
///
/// ## Public Types
/// - `DeliveryTierDto` - Data transfer object for DeliveryTier
/// - `DeliveryTierSummary` - Summary view of DeliveryTier
/// - `DeliveryTierId` - Type-safe ID wrapper
/// - `OrderDto` - Data transfer object for Order
/// - `OrderSummary` - Summary view of Order
/// - `OrderId` - Type-safe ID wrapper
/// - `OrderDeliveryDto` - Data transfer object for OrderDelivery
/// - `OrderDeliverySummary` - Summary view of OrderDelivery
/// - `OrderDeliveryId` - Type-safe ID wrapper
/// - `OrderItemDto` - Data transfer object for OrderItem
/// - `OrderItemSummary` - Summary view of OrderItem
/// - `OrderItemId` - Type-safe ID wrapper
/// - `OrderPickupDto` - Data transfer object for OrderPickup
/// - `OrderPickupSummary` - Summary view of OrderPickup
/// - `OrderPickupId` - Type-safe ID wrapper
/// - `OrderStatusTimelineDto` - Data transfer object for OrderStatusTimeline
/// - `OrderStatusTimelineSummary` - Summary view of OrderStatusTimeline
/// - `OrderStatusTimelineId` - Type-safe ID wrapper
///
/// ## Public Services
/// - `OrdersQueryService` - Read-only queries
///
/// ## Public Events
/// - `DeliveryTierCreatedEvent` - Published when DeliveryTier is created
/// - `DeliveryTierUpdatedEvent` - Published when DeliveryTier is updated
/// - `DeliveryTierDeletedEvent` - Published when DeliveryTier is deleted
/// - `OrderCreatedEvent` - Published when Order is created
/// - `OrderUpdatedEvent` - Published when Order is updated
/// - `OrderDeletedEvent` - Published when Order is deleted
/// - `OrderDeliveryCreatedEvent` - Published when OrderDelivery is created
/// - `OrderDeliveryUpdatedEvent` - Published when OrderDelivery is updated
/// - `OrderDeliveryDeletedEvent` - Published when OrderDelivery is deleted
/// - `OrderItemCreatedEvent` - Published when OrderItem is created
/// - `OrderItemUpdatedEvent` - Published when OrderItem is updated
/// - `OrderItemDeletedEvent` - Published when OrderItem is deleted
/// - `OrderPickupCreatedEvent` - Published when OrderPickup is created
/// - `OrderPickupUpdatedEvent` - Published when OrderPickup is updated
/// - `OrderPickupDeletedEvent` - Published when OrderPickup is deleted
/// - `OrderStatusTimelineCreatedEvent` - Published when OrderStatusTimeline is created
/// - `OrderStatusTimelineUpdatedEvent` - Published when OrderStatusTimeline is updated
/// - `OrderStatusTimelineDeletedEvent` - Published when OrderStatusTimeline is deleted
pub struct ExportSummary;
