//! Public services for Orders module
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! These services provide the public API for other modules.
//! They only expose read operations - writes go through events.

use std::sync::Arc;

use anyhow::Result;
use async_trait::async_trait;
use uuid::Uuid;

use super::types::*;

// ============================================================================
// QUERY SERVICE TRAIT
// ============================================================================

/// Public query service for Orders module
///
/// This trait defines read-only operations that other modules can use.
/// Implementations should NOT expose internal domain logic.
#[async_trait]
pub trait OrdersQueryService: Send + Sync {
    /// Get DeliveryTier by ID
    async fn get_delivery_tier(&self, id: DeliveryTierId) -> Result<Option<DeliveryTierDto>>;

    /// Get DeliveryTier summary by ID
    async fn get_delivery_tier_summary(&self, id: DeliveryTierId) -> Result<Option<DeliveryTierSummary>>;

    /// Check if DeliveryTier exists
    async fn delivery_tier_exists(&self, id: DeliveryTierId) -> Result<bool>;

    /// Get Order by ID
    async fn get_order(&self, id: OrderId) -> Result<Option<OrderDto>>;

    /// Get Order summary by ID
    async fn get_order_summary(&self, id: OrderId) -> Result<Option<OrderSummary>>;

    /// Check if Order exists
    async fn order_exists(&self, id: OrderId) -> Result<bool>;

    /// Get OrderDelivery by ID
    async fn get_order_delivery(&self, id: OrderDeliveryId) -> Result<Option<OrderDeliveryDto>>;

    /// Get OrderDelivery summary by ID
    async fn get_order_delivery_summary(&self, id: OrderDeliveryId) -> Result<Option<OrderDeliverySummary>>;

    /// Check if OrderDelivery exists
    async fn order_delivery_exists(&self, id: OrderDeliveryId) -> Result<bool>;

    /// Get OrderItem by ID
    async fn get_order_item(&self, id: OrderItemId) -> Result<Option<OrderItemDto>>;

    /// Get OrderItem summary by ID
    async fn get_order_item_summary(&self, id: OrderItemId) -> Result<Option<OrderItemSummary>>;

    /// Check if OrderItem exists
    async fn order_item_exists(&self, id: OrderItemId) -> Result<bool>;

    /// Get OrderPickup by ID
    async fn get_order_pickup(&self, id: OrderPickupId) -> Result<Option<OrderPickupDto>>;

    /// Get OrderPickup summary by ID
    async fn get_order_pickup_summary(&self, id: OrderPickupId) -> Result<Option<OrderPickupSummary>>;

    /// Check if OrderPickup exists
    async fn order_pickup_exists(&self, id: OrderPickupId) -> Result<bool>;

    /// Get OrderStatusTimeline by ID
    async fn get_order_status_timeline(&self, id: OrderStatusTimelineId) -> Result<Option<OrderStatusTimelineDto>>;

    /// Get OrderStatusTimeline summary by ID
    async fn get_order_status_timeline_summary(&self, id: OrderStatusTimelineId) -> Result<Option<OrderStatusTimelineSummary>>;

    /// Check if OrderStatusTimeline exists
    async fn order_status_timeline_exists(&self, id: OrderStatusTimelineId) -> Result<bool>;

}

// ============================================================================
// QUERY SERVICE IMPLEMENTATION
// ============================================================================

/// Default implementation of OrdersQueryService
pub struct OrdersQueryServiceImpl<R> {
    repository: Arc<R>,
}

impl<R> OrdersQueryServiceImpl<R> {
    pub fn new(repository: Arc<R>) -> Self {
        Self { repository }
    }
}

// ============================================================================
// CUSTOM SERVICES
// ============================================================================

// <<< CUSTOM SERVICES START >>>
// Add custom public services here
// <<< CUSTOM SERVICES END >>>
