//! Public types for Orders module
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! These DTOs are the ONLY types other modules should use.
//! They are decoupled from internal domain entities.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

// ============================================================================
// DELIVERYTIER TYPES
// ============================================================================

/// Type-safe ID for DeliveryTier
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct DeliveryTierId(pub Uuid);

impl DeliveryTierId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for DeliveryTierId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<DeliveryTierId> for Uuid {
    fn from(id: DeliveryTierId) -> Self {
        id.0
    }
}

/// Data transfer object for DeliveryTier
///
/// This is the public representation of DeliveryTier for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DeliveryTierDto {
    pub id: DeliveryTierId,
    pub code: String,
    pub name: String,
    pub name_en: Option<String>,
    pub description: Option<String>,
    pub duration_hours: i32,
    pub duration_label: String,
    pub color: Option<String>,
    pub icon: Option<String>,
    pub is_urgent: bool,
    pub sort_order: i32,
    pub is_active: bool,
    pub is_default: bool,
    pub provider_id: Option<Uuid>,
    pub outlet_id: Option<Uuid>,
    pub source_id: Option<Uuid>,
    pub is_cloned: bool,
    pub metadata: serde_json::Value,
}

/// Summary view of DeliveryTier for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DeliveryTierSummary {
    pub id: DeliveryTierId,
    pub name: String,
}

/// Reference to DeliveryTier for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DeliveryTierRef {
    pub id: DeliveryTierId,
}

// ============================================================================
// ORDER TYPES
// ============================================================================

/// Type-safe ID for Order
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct OrderId(pub Uuid);

impl OrderId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for OrderId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<OrderId> for Uuid {
    fn from(id: OrderId) -> Self {
        id.0
    }
}

/// Data transfer object for Order
///
/// This is the public representation of Order for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrderDto {
    pub id: OrderId,
    pub order_number: String,
    pub customer_id: Uuid,
    pub provider_id: Uuid,
    pub outlet_id: Option<Uuid>,
    pub corporate_order_id: Option<Uuid>,
    pub delivery_tier_id: Option<Uuid>,
    pub order_type: OrderType,
    pub status: OrderStatus,
    pub fulfillment_method: FulfillmentMethod,
    pub estimated_ready_at: Option<DateTime<Utc>>,
    pub actual_ready_at: Option<DateTime<Utc>>,
    pub currency: String,
    pub subtotal: Decimal,
    pub discount_amount: Decimal,
    pub promo_id: Option<Uuid>,
    pub delivery_fee: Decimal,
    pub pickup_fee: Decimal,
    pub tax_amount: Decimal,
    pub platform_fee: Decimal,
    pub grand_total: Decimal,
    pub payment_status: PaymentStatus,
    pub paid_amount: Decimal,
    pub paid_at: Option<DateTime<Utc>>,
    pub special_instructions: Option<String>,
    pub provider_notes: Option<String>,
    pub cancelled_at: Option<DateTime<Utc>>,
    pub cancellation_reason: Option<CancellationReason>,
    pub cancellation_note: Option<String>,
    pub cancelled_by: Option<Uuid>,
    pub data: serde_json::Value,
    pub source: Option<String>,
    pub metadata: serde_json::Value,
}

/// Summary view of Order for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrderSummary {
    pub id: OrderId,
    pub status: OrderStatus,
}

/// Reference to Order for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrderRef {
    pub id: OrderId,
}

// ============================================================================
// ORDERDELIVERY TYPES
// ============================================================================

/// Type-safe ID for OrderDelivery
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct OrderDeliveryId(pub Uuid);

impl OrderDeliveryId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for OrderDeliveryId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<OrderDeliveryId> for Uuid {
    fn from(id: OrderDeliveryId) -> Self {
        id.0
    }
}

/// Data transfer object for OrderDelivery
///
/// This is the public representation of OrderDelivery for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrderDeliveryDto {
    pub id: OrderDeliveryId,
    pub order_id: Uuid,
    pub delivery_type: DeliveryType,
    pub scheduled_date: NaiveDate,
    pub scheduled_time_start: Option<String>,
    pub scheduled_time_end: Option<String>,
    pub time_slot: Option<String>,
    pub customer_requested_date: Option<NaiveDate>,
    pub customer_requested_time_start: Option<String>,
    pub customer_requested_time_end: Option<String>,
    pub address_id: Option<Uuid>,
    pub address_line: String,
    pub address_detail: Option<String>,
    pub landmark: Option<String>,
    pub latitude: Option<f64>,
    pub longitude: Option<f64>,
    pub contact_name: String,
    pub contact_phone: String,
    pub contact_phone_alt: Option<String>,
    pub agent_id: Option<Uuid>,
    pub agent_name: Option<String>,
    pub agent_phone: Option<String>,
    pub assigned_at: Option<DateTime<Utc>>,
    pub status: DeliveryStatus,
    pub dispatched_at: Option<DateTime<Utc>>,
    pub en_route_at: Option<DateTime<Utc>>,
    pub arrived_at: Option<DateTime<Utc>>,
    pub delivered_at: Option<DateTime<Utc>>,
    pub item_count: i32,
    pub bag_count: i32,
    pub bag_numbers: serde_json::Value,
    pub verification_method: Option<String>,
    pub verification_code: Option<String>,
    pub verified_at: Option<DateTime<Utc>>,
    pub photos: serde_json::Value,
    pub proof_photo_url: Option<String>,
    pub signature_url: Option<String>,
    pub signed_by: Option<String>,
    pub relation_to_customer: Option<String>,
    pub delivery_latitude: Option<f64>,
    pub delivery_longitude: Option<f64>,
    pub distance_from_address_meters: Option<i32>,
    pub delivery_fee: Decimal,
    pub express_fee: Decimal,
    pub total_fee: Decimal,
    pub currency: String,
    pub is_cod: bool,
    pub cod_amount: Option<Decimal>,
    pub cod_collected: bool,
    pub cod_collected_at: Option<DateTime<Utc>>,
    pub customer_notes: Option<String>,
    pub agent_notes: Option<String>,
    pub internal_notes: Option<String>,
    pub failure_reason: Option<String>,
    pub failure_code: Option<String>,
    pub attempt_count: i32,
    pub reschedule_count: i32,
    pub original_scheduled_date: Option<NaiveDate>,
    pub reschedule_reason: Option<String>,
    pub delivery_rating: Option<i32>,
    pub rating_comment: Option<String>,
    pub metadata: serde_json::Value,
}

/// Summary view of OrderDelivery for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrderDeliverySummary {
    pub id: OrderDeliveryId,
    pub contact_name: String,
    pub agent_name: Option<String>,
    pub status: DeliveryStatus,
}

/// Reference to OrderDelivery for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrderDeliveryRef {
    pub id: OrderDeliveryId,
}

// ============================================================================
// ORDERITEM TYPES
// ============================================================================

/// Type-safe ID for OrderItem
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct OrderItemId(pub Uuid);

impl OrderItemId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for OrderItemId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<OrderItemId> for Uuid {
    fn from(id: OrderItemId) -> Self {
        id.0
    }
}

/// Data transfer object for OrderItem
///
/// This is the public representation of OrderItem for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrderItemDto {
    pub id: OrderItemId,
    pub order_id: Uuid,
    pub service_id: Option<Uuid>,
    pub item_name: Option<String>,
    pub quantity: i32,
    pub unit_type: UnitType,
    pub unit_price: Decimal,
    pub subtotal: Decimal,
    pub discount: Decimal,
    pub addon_total: Decimal,
    pub total: Decimal,
    pub currency: String,
    pub addons: serde_json::Value,
    pub condition_on_receipt: ItemCondition,
    pub condition_notes: Option<String>,
    pub processing_status: ItemProcessingStatus,
    pub special_instructions: Option<String>,
    pub processing_notes: Option<String>,
    pub delivery_tier_id: Option<Uuid>,
    pub started_at: Option<DateTime<Utc>>,
    pub completed_at: Option<DateTime<Utc>>,
    pub metadata: serde_json::Value,
}

/// Summary view of OrderItem for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrderItemSummary {
    pub id: OrderItemId,
    pub item_name: Option<String>,
}

/// Reference to OrderItem for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrderItemRef {
    pub id: OrderItemId,
}

// ============================================================================
// ORDERPICKUP TYPES
// ============================================================================

/// Type-safe ID for OrderPickup
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct OrderPickupId(pub Uuid);

impl OrderPickupId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for OrderPickupId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<OrderPickupId> for Uuid {
    fn from(id: OrderPickupId) -> Self {
        id.0
    }
}

/// Data transfer object for OrderPickup
///
/// This is the public representation of OrderPickup for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrderPickupDto {
    pub id: OrderPickupId,
    pub order_id: Uuid,
    pub pickup_type: PickupType,
    pub scheduled_date: NaiveDate,
    pub scheduled_time_start: Option<String>,
    pub scheduled_time_end: Option<String>,
    pub time_slot: Option<String>,
    pub customer_requested_date: Option<NaiveDate>,
    pub customer_requested_time_start: Option<String>,
    pub customer_requested_time_end: Option<String>,
    pub address_id: Option<Uuid>,
    pub address_line: String,
    pub address_detail: Option<String>,
    pub landmark: Option<String>,
    pub latitude: Option<f64>,
    pub longitude: Option<f64>,
    pub contact_name: String,
    pub contact_phone: String,
    pub contact_phone_alt: Option<String>,
    pub agent_id: Option<Uuid>,
    pub agent_name: Option<String>,
    pub agent_phone: Option<String>,
    pub assigned_at: Option<DateTime<Utc>>,
    pub status: PickupStatus,
    pub en_route_at: Option<DateTime<Utc>>,
    pub arrived_at: Option<DateTime<Utc>>,
    pub started_at: Option<DateTime<Utc>>,
    pub completed_at: Option<DateTime<Utc>>,
    pub estimated_weight_kg: Option<Decimal>,
    pub actual_weight_kg: Option<Decimal>,
    pub estimated_items: Option<i32>,
    pub actual_items: Option<i32>,
    pub bag_count: i32,
    pub bag_numbers: serde_json::Value,
    pub photos: serde_json::Value,
    pub signature_url: Option<String>,
    pub signed_by: Option<String>,
    pub pickup_latitude: Option<f64>,
    pub pickup_longitude: Option<f64>,
    pub distance_from_address_meters: Option<i32>,
    pub customer_notes: Option<String>,
    pub agent_notes: Option<String>,
    pub internal_notes: Option<String>,
    pub failure_reason: Option<String>,
    pub failure_code: Option<String>,
    pub reschedule_count: i32,
    pub original_scheduled_date: Option<NaiveDate>,
    pub reschedule_reason: Option<String>,
    pub metadata: serde_json::Value,
}

/// Summary view of OrderPickup for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrderPickupSummary {
    pub id: OrderPickupId,
    pub contact_name: String,
    pub agent_name: Option<String>,
    pub status: PickupStatus,
}

/// Reference to OrderPickup for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrderPickupRef {
    pub id: OrderPickupId,
}

// ============================================================================
// ORDERSTATUSTIMELINE TYPES
// ============================================================================

/// Type-safe ID for OrderStatusTimeline
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct OrderStatusTimelineId(pub Uuid);

impl OrderStatusTimelineId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for OrderStatusTimelineId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<OrderStatusTimelineId> for Uuid {
    fn from(id: OrderStatusTimelineId) -> Self {
        id.0
    }
}

/// Data transfer object for OrderStatusTimeline
///
/// This is the public representation of OrderStatusTimeline for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrderStatusTimelineDto {
    pub id: OrderStatusTimelineId,
    pub order_id: Uuid,
    pub entry_type: TimelineEntryType,
    pub from_status: Option<String>,
    pub to_status: Option<String>,
    pub occurred_at: DateTime<Utc>,
    pub actor_type: Option<String>,
    pub actor_id: Option<Uuid>,
    pub actor_name: Option<String>,
    pub actor_role: Option<String>,
    pub title: String,
    pub description: Option<String>,
    pub latitude: Option<f64>,
    pub longitude: Option<f64>,
    pub location_name: Option<String>,
    pub is_customer_visible: bool,
    pub is_provider_visible: bool,
    pub is_agent_visible: bool,
    pub attachments: serde_json::Value,
    pub duration_minutes: Option<i32>,
    pub channel: Option<String>,
    pub device_info: serde_json::Value,
    pub ip_address: Option<String>,
    pub metadata: serde_json::Value,
}

/// Summary view of OrderStatusTimeline for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrderStatusTimelineSummary {
    pub id: OrderStatusTimelineId,
    pub actor_name: Option<String>,
    pub title: String,
    pub location_name: Option<String>,
}

/// Reference to OrderStatusTimeline for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrderStatusTimelineRef {
    pub id: OrderStatusTimelineId,
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

// <<< CUSTOM TYPES START >>>
// Add custom public types here
// <<< CUSTOM TYPES END >>>
