//! Orders Module
//!
//! Generated by backbone-schema. Enhanced with runtime implementations.
//!
//! This module provides:
//! - Domain entities and repositories
//! - Application services
//! - HTTP and gRPC handlers
//! - Route configuration
//! - State machine enforcement
//! - Validation rules runtime
//! - RBAC middleware
//! - Trigger execution system
//! - Computed fields
//! - Workflow orchestrator

// Generated modules
pub mod domain;
pub mod infrastructure;
pub mod application;
pub mod presentation;
pub mod seeders;

// Re-exports for convenience - Domain entities
pub use domain::entity::*;

// Re-exports - Infrastructure
pub use infrastructure::persistence::*;

// Re-exports - Application services
pub use application::service::DeliveryTierService;
pub use application::service::OrderService;
pub use application::service::OrderDeliveryService;
pub use application::service::OrderItemService;
pub use application::service::OrderPickupService;
pub use application::service::OrderStatusTimelineService;

use std::sync::Arc;
use axum::Router;
use sqlx::PgPool;

/// Orders module configuration
///
/// Use the builder pattern to configure and register this module:
///
/// ```text
/// let orders = OrdersModule::builder()
///     .with_database(pool.clone())
///     .build()?;
///
/// let router = orders.routes();
/// ```
pub struct OrdersModule {
    pub delivery_tier_service: Arc<DeliveryTierService>,
    pub order_service: Arc<OrderService>,
    pub order_delivery_service: Arc<OrderDeliveryService>,
    pub order_item_service: Arc<OrderItemService>,
    pub order_pickup_service: Arc<OrderPickupService>,
    pub order_status_timeline_service: Arc<OrderStatusTimelineService>,
}

impl OrdersModule {
    /// Create a new module builder
    pub fn builder() -> OrdersModuleBuilder {
        OrdersModuleBuilder::new()
    }

    /// Configure HTTP routes for this module using Axum
    ///
    /// Returns an Axum Router with all 12 Backbone CRUD endpoints per entity.
    pub fn routes(&self) -> Router {
        use presentation::http::{
            create_delivery_tier_routes,
            create_order_routes,
            create_order_delivery_routes,
            create_order_item_routes,
            create_order_pickup_routes,
            create_order_status_timeline_routes,
        };

        Router::new()
            .merge(create_delivery_tier_routes(self.delivery_tier_service.clone()))
            .merge(create_order_routes(self.order_service.clone()))
            .merge(create_order_delivery_routes(self.order_delivery_service.clone()))
            .merge(create_order_item_routes(self.order_item_service.clone()))
            .merge(create_order_pickup_routes(self.order_pickup_service.clone()))
            .merge(create_order_status_timeline_routes(self.order_status_timeline_service.clone()))
    }
}

/// Builder for OrdersModule
pub struct OrdersModuleBuilder {
    db_pool: Option<PgPool>,
}

impl OrdersModuleBuilder {
    /// Create a new builder
    pub fn new() -> Self {
        Self {
            db_pool: None,
        }
    }

    /// Set the database connection pool
    pub fn with_database(mut self, pool: PgPool) -> Self {
        self.db_pool = Some(pool);
        self
    }

    /// Build the module with configured dependencies
    pub fn build(self) -> anyhow::Result<OrdersModule> {
        let db_pool = self.db_pool
            .ok_or_else(|| anyhow::anyhow!("Database pool not configured"))?;

        // DeliveryTier service
        let delivery_tier_repository = Arc::new(DeliveryTierRepository::new(db_pool.clone()));
        let delivery_tier_service = Arc::new(DeliveryTierService::with_repository(delivery_tier_repository.clone()));

        // Order service
        let order_repository = Arc::new(OrderRepository::new(db_pool.clone()));
        let order_service = Arc::new(OrderService::with_repository(order_repository.clone()));

        // OrderDelivery service
        let order_delivery_repository = Arc::new(OrderDeliveryRepository::new(db_pool.clone()));
        let order_delivery_service = Arc::new(OrderDeliveryService::with_repository(order_delivery_repository.clone()));

        // OrderItem service
        let order_item_repository = Arc::new(OrderItemRepository::new(db_pool.clone()));
        let order_item_service = Arc::new(OrderItemService::with_repository(order_item_repository.clone()));

        // OrderPickup service
        let order_pickup_repository = Arc::new(OrderPickupRepository::new(db_pool.clone()));
        let order_pickup_service = Arc::new(OrderPickupService::with_repository(order_pickup_repository.clone()));

        // OrderStatusTimeline service
        let order_status_timeline_repository = Arc::new(OrderStatusTimelineRepository::new(db_pool.clone()));
        let order_status_timeline_service = Arc::new(OrderStatusTimelineService::with_repository(order_status_timeline_repository.clone()));

        // <<< CUSTOM
        // END CUSTOM

        Ok(OrdersModule {
            delivery_tier_service,
            order_service,
            order_delivery_service,
            order_item_service,
            order_pickup_service,
            order_status_timeline_service,
            // <<< CUSTOM
            // END CUSTOM
        })
    }
}

impl Default for OrdersModuleBuilder {
    fn default() -> Self {
        Self::new()
    }
}
