//! Use case type aliases for DeliveryTier aggregate
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateDeliveryTierDto, UpdateDeliveryTierDto};
use crate::application::service::DeliveryTierService;
use crate::domain::entity::DeliveryTier;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateDeliveryTierUseCase = CreateUseCase<DeliveryTier, CreateDeliveryTierDto, DeliveryTierService>;
pub type UpdateDeliveryTierUseCase = UpdateUseCase<DeliveryTier, UpdateDeliveryTierDto, DeliveryTierService>;
pub type GetDeliveryTierUseCase    = GetUseCase<DeliveryTier, DeliveryTierService>;
pub type DeleteDeliveryTierUseCase = DeleteUseCase<DeliveryTier, DeliveryTierService>;
pub type ListDeliveryTierUseCase   = ListUseCase<DeliveryTier, DeliveryTierService>;

// <<< CUSTOM
// END CUSTOM
