//! Use case type aliases for OrderStatusTimeline aggregate
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateOrderStatusTimelineDto, UpdateOrderStatusTimelineDto};
use crate::application::service::OrderStatusTimelineService;
use crate::domain::entity::OrderStatusTimeline;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateOrderStatusTimelineUseCase = CreateUseCase<OrderStatusTimeline, CreateOrderStatusTimelineDto, OrderStatusTimelineService>;
pub type UpdateOrderStatusTimelineUseCase = UpdateUseCase<OrderStatusTimeline, UpdateOrderStatusTimelineDto, OrderStatusTimelineService>;
pub type GetOrderStatusTimelineUseCase    = GetUseCase<OrderStatusTimeline, OrderStatusTimelineService>;
pub type DeleteOrderStatusTimelineUseCase = DeleteUseCase<OrderStatusTimeline, OrderStatusTimelineService>;
pub type ListOrderStatusTimelineUseCase   = ListUseCase<OrderStatusTimeline, OrderStatusTimelineService>;

// <<< CUSTOM
// END CUSTOM
