//! Use case type aliases for OrderItem aggregate
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateOrderItemDto, UpdateOrderItemDto};
use crate::application::service::OrderItemService;
use crate::domain::entity::OrderItem;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateOrderItemUseCase = CreateUseCase<OrderItem, CreateOrderItemDto, OrderItemService>;
pub type UpdateOrderItemUseCase = UpdateUseCase<OrderItem, UpdateOrderItemDto, OrderItemService>;
pub type GetOrderItemUseCase    = GetUseCase<OrderItem, OrderItemService>;
pub type DeleteOrderItemUseCase = DeleteUseCase<OrderItem, OrderItemService>;
pub type ListOrderItemUseCase   = ListUseCase<OrderItem, OrderItemService>;

// <<< CUSTOM
// END CUSTOM
