//! Use case type aliases for Order aggregate
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateOrderDto, UpdateOrderDto};
use crate::application::service::OrderService;
use crate::domain::entity::Order;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateOrderUseCase = CreateUseCase<Order, CreateOrderDto, OrderService>;
pub type UpdateOrderUseCase = UpdateUseCase<Order, UpdateOrderDto, OrderService>;
pub type GetOrderUseCase    = GetUseCase<Order, OrderService>;
pub type DeleteOrderUseCase = DeleteUseCase<Order, OrderService>;
pub type ListOrderUseCase   = ListUseCase<Order, OrderService>;

// <<< CUSTOM
// END CUSTOM
