//! Use case type aliases for OrderDelivery aggregate
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateOrderDeliveryDto, UpdateOrderDeliveryDto};
use crate::application::service::OrderDeliveryService;
use crate::domain::entity::OrderDelivery;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateOrderDeliveryUseCase = CreateUseCase<OrderDelivery, CreateOrderDeliveryDto, OrderDeliveryService>;
pub type UpdateOrderDeliveryUseCase = UpdateUseCase<OrderDelivery, UpdateOrderDeliveryDto, OrderDeliveryService>;
pub type GetOrderDeliveryUseCase    = GetUseCase<OrderDelivery, OrderDeliveryService>;
pub type DeleteOrderDeliveryUseCase = DeleteUseCase<OrderDelivery, OrderDeliveryService>;
pub type ListOrderDeliveryUseCase   = ListUseCase<OrderDelivery, OrderDeliveryService>;

// <<< CUSTOM
// END CUSTOM
