//! HTTP handlers
//!
//! Auto-generated by backbone-schema. Do not edit manually.
//!
//! These handlers use Axum and backbone-core's BackboneCrudHandler
//! to provide all 12 standard Backbone CRUD endpoints.

pub mod delivery_tier_handler;
pub mod order_handler;
pub mod order_delivery_handler;
pub mod order_item_handler;
pub mod order_pickup_handler;
pub mod order_status_timeline_handler;

// <<< CUSTOM
// END CUSTOM

// Re-exports
pub use delivery_tier_handler::create_delivery_tier_routes;
pub use order_handler::create_order_routes;
pub use order_delivery_handler::create_order_delivery_routes;
pub use order_item_handler::create_order_item_routes;
pub use order_pickup_handler::create_order_pickup_routes;
pub use order_status_timeline_handler::create_order_status_timeline_routes;
// <<< CUSTOM
// END CUSTOM
