//! HTTP route configuration
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! This module provides consolidated Axum route configuration using backbone-core's
//! BackboneCrudHandler for all 12 standard Backbone CRUD endpoints per entity.

use axum::Router;
use std::sync::Arc;

use super::{
    delivery_tier_handler::create_delivery_tier_routes,
    order_handler::create_order_routes,
    order_delivery_handler::create_order_delivery_routes,
    order_item_handler::create_order_item_routes,
    order_pickup_handler::create_order_pickup_routes,
    order_status_timeline_handler::create_order_status_timeline_routes,
};

use crate::application::service::{
    DeliveryTierService,
    OrderService,
    OrderDeliveryService,
    OrderItemService,
    OrderPickupService,
    OrderStatusTimelineService,
};

/// Services collection for all CRUD endpoints
pub struct HttpServices {
    pub delivery_tier: Arc<DeliveryTierService>,
    pub order: Arc<OrderService>,
    pub order_delivery: Arc<OrderDeliveryService>,
    pub order_item: Arc<OrderItemService>,
    pub order_pickup: Arc<OrderPickupService>,
    pub order_status_timeline: Arc<OrderStatusTimelineService>,
}

/// Configure all HTTP routes for this module using Axum and BackboneCrudHandler.
///
/// Each entity gets 12 standard Backbone CRUD endpoints:
/// 1. GET /api/v1/{collection} - List with pagination
/// 2. POST /api/v1/{collection} - Create
/// 3. GET /api/v1/{collection}/:id - Get by ID
/// 4. PUT /api/v1/{collection}/:id - Full update
/// 5. PATCH /api/v1/{collection}/:id - Partial update
/// 6. DELETE /api/v1/{collection}/:id - Soft delete
/// 7. POST /api/v1/{collection}/bulk - Bulk create
/// 8. POST /api/v1/{collection}/upsert - Upsert
/// 9. GET /api/v1/{collection}/trash - List deleted
/// 10. POST /api/v1/{collection}/:id/restore - Restore
/// 11. DELETE /api/v1/{collection}/empty - Empty trash
/// 12. GET /api/v1/{collection}/:id/deleted - Get deleted by ID
pub fn configure_routes(services: HttpServices) -> Router {
    Router::new()
        // DeliveryTier routes (12 Backbone endpoints)
        .merge(create_delivery_tier_routes(services.delivery_tier))
        // Order routes (12 Backbone endpoints)
        .merge(create_order_routes(services.order))
        // OrderDelivery routes (12 Backbone endpoints)
        .merge(create_order_delivery_routes(services.order_delivery))
        // OrderItem routes (12 Backbone endpoints)
        .merge(create_order_item_routes(services.order_item))
        // OrderPickup routes (12 Backbone endpoints)
        .merge(create_order_pickup_routes(services.order_pickup))
        // OrderStatusTimeline routes (12 Backbone endpoints)
        .merge(create_order_status_timeline_routes(services.order_status_timeline))
}

/// Create an individual entity's routes (for modular configuration)
pub mod individual {
    use super::*;

    pub fn delivery_tier_routes(service: Arc<DeliveryTierService>) -> Router {
        create_delivery_tier_routes(service)
    }

    pub fn order_routes(service: Arc<OrderService>) -> Router {
        create_order_routes(service)
    }

    pub fn order_delivery_routes(service: Arc<OrderDeliveryService>) -> Router {
        create_order_delivery_routes(service)
    }

    pub fn order_item_routes(service: Arc<OrderItemService>) -> Router {
        create_order_item_routes(service)
    }

    pub fn order_pickup_routes(service: Arc<OrderPickupService>) -> Router {
        create_order_pickup_routes(service)
    }

    pub fn order_status_timeline_routes(service: Arc<OrderStatusTimelineService>) -> Router {
        create_order_status_timeline_routes(service)
    }

}
